---
tags: []
title: Problem Set 4
---

*Deadline: Fri 10/15, 5:00am*

For this problem set, you should do the below:

1.  View your students' Wufoo forms at
https://www.cs50.net/tools/wufoo/pset4.php[https://www.cs50.net/tools/wufoo/pset4.php].
2.  Fetch your students' and render PDFs on the cloud.
3.  Grab copies of the *cs50/2010/pset4/username* and
*cs50/2010/hacker4/username* Google Spreadsheets. Hover over Column A
cells that have orange triangles to see comments.
4.  Assign Correctness, Design, and Style scores in each.
5.  Record grades at http://www.cs50.net/tools/[cs50.net/tools].
6.  Email your students their PDFs. Hang on to the PDFs too; we'll
eventually upload them to the cloud for archival.


How to Fetch and Render
^^^^^^^^^^^^^^^^^^^^^^^

---------------------------------
export PATH=~cs50/staff/bin:$PATH
mkdir both4
fetch pset4 both4
fetch hacker4 both4
render pset4 both4/*.pset4
render hacker4 both4/*.hacker4
---------------------------------


How to Run Grading Scripts
^^^^^^^^^^^^^^^^^^^^^^^^^^

From inside a student's submission directory you should run:

------------------------------------------------------
~mtucker/personal/scripts/trunk/pset4-scripts/pset4.py
------------------------------------------------------

This script will attempt to rebuild the student's `sudoku` using `make`
and then attempt to play a series of games checking the generated
`log.txt` file after each set of inputs is played. If the input/output
log at the end of a test case doesn't match the solution's log, then the
`diff` of the two files will be output along with a message that might
look like:

-----------------------------------------------------------------------------------------------------------------------------------
test periodblanked.txt: failed [n00b 1] blanking with period
--- log.txt     2010-10-10 12:06:14.000000000 -0400
+++ /home/mtucker/personal/scripts/trunk/pset4-scripts/sudoku_test_cases/periodblanked.txt      2010-10-08 00:29:55.000000000 -0400
@@ -13,7 +13,7 @@
 050080160
 800100009
 000090084
-003010700
+003000700
 970050000
 600001003
 085030040
@@ -23,7 +23,7 @@
 050080160
 800100009
 000090084
-003010700
+003000700
 970050000
 600001003
 085030040

sudoku blanking_works   0
-----------------------------------------------------------------------------------------------------------------------------------

This indicates that the student's log didn't match ours (as stored in
`periodblanked.txt`) when we ran the `n00b 1` board, entered a number
and then attempted to blank it with a period/dot character. To
investigate you will want to start by running their program and the test
case manually.

NOTE: Automating user input is a somewhat fragile process, so if you run
into problems, don't hesitate to let Mike Tucker
(mtucker@eecs.harvard.edu) know.
