---
tags: []
title: tunnel50
---

`tunnel50` is a command-line tool with which CS50 staff can connect to
your link:CS50 Appliance[CS50 Appliance] so as to see and even control
your terminal window in order to troubleshoot problems you're having.
CS50 staff can only connect to your appliance if you actually run
`tunnel50` _and_ provide us with the unique ID and temporary password
that `tunnel50` assigns to you upon launch. Once you quit `tunnel50`, we
can no longer connect. And the next time you launch `tunnel50`, it
should assign you a new ID and password so that the old ones no longer
work.

`tunnel50` does not let CS50 staff see your appliance's desktop (and its
menus and icons) or your personal computer's desktop. To share either,
you should use TeamViewer instead.

[[]]
How to Use
~~~~~~~~~~

[[]]
Student
^^^^^^^

1.  Open a terminal window in the link:CS50 Appliance[CS50 Appliance],
as via *Menu > Accessories > Terminal*.
2.  Execute:
+
-------------
sudo tunnel50
-------------
+
Input *crimson* if prompted for *[sudo] password*. You should then be
provided with a 9-digit *ID* as well as a 4-digit *Password* (which is
different from the password that you might have just inputted).
3.  Inform CS50 staff of that ID and password (as via email, IM, or a
private post to http://help.cs50.net/[help.cs50.net]).

As soon as CS50 staff connect to you, the terminal window will clear
itself and your prompt will return. Thereafter, the staff will see
anything you type and vice versa. To quit (and disconnect the staff),
hit *ctl-d*.

[[]]
Staff
^^^^^

1.  Ask student to run `tunnel50`, per the link:#Student[instructions
above], and provide you with his or her 9-digit *ID* and 4-digit
*Password*.
2.  Open a terminal window in the link:CS50 Appliance[CS50 Appliance],
as via *Menu > Accessories > Terminal*.
3.  Execute:
+
----------------
sudo tunnel50 ID
----------------
+
where `ID` is the student's 9-digit ID.
4.  Input *crimson* if prompted for *[sudo] password*.
5.  Input student's 4-digit password when prompted for *Partner's
password*.

As soon as you're connected to the student, the terminal window will
clear itself and your prompt will return. Thereafter, the student will
see anything you type and vice versa. To quit (and disconnect the
student), hit *ctl-d*.

Category:HOWTO
