---
tags: []
title: faqs
---
For other troubleshooting tips, see CS50's link:VirtualBox[installation
instructions for VirtualBox].

[[]]
My cursor won't stop spinning ; I can't move or resize my gedit or
Terminal window
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This problem appears to be a bug in the appliance's operating system,
but you should be able to fix it as follows:

1.  Open a terminal window.
2.  Execute:
+
-----------------
xfwm4 --replace &
-----------------
3.  Close the terminal window.

You should find that your cursor's back to an arrow, and your windows
can be moved and resized.

(We'll fix this bug for you for Problem Set 2 onward now that we know
how to fix it!)

[[]]
My screen is black ; my appliance doesn't boot
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This can happen if your computer doesn't have much RAM (i.e., memory),
among other reasons, especially if your computer is a few years old or
is a small netbook.

By default, the appliance tries to use 768MB of your computer's RAM,
which might be more than it can handle. To try fixing:

1.  Close appliance, if its window is open.
2.  Single-click the appliance in VirtualBox's lefthand menu.
3.  Click *Settings*.
4.  Click *System*
5.  Change *Base Memory* from *768* to *256*.
6.  Click *OK*.
7.  Boot appliance.

If it still won't boot, try:

1.  Close appliance, if its window is open.
2.  If you did not already start working on the problem set (i.e., if
you didn't write any code yet), right-click (PC) or ctrl-click (Mac)
appliance and choose *Remove* then *Delete*. That will delete everything
in that appliance.
3.  Re-import the appliance, per
https://manual.cs50.net/Appliance#VirtualBox.
4.  *Do not boot the newly imported appliance yet.* Instead,
single-click the appliance in VirtualBox's lefthand menu.
5.  Click *Settings*.
6.  Click *System*.
7.  Change *Base Memory* from *768* to *256*.
8.  Click *OK*.
9.  Boot appliance.

If it still doesn't work, email heads@cs50.net explaining your symptoms.

[[]]
My trash can is missing
~~~~~~~~~~~~~~~~~~~~~~~

This problem appears to be a bug in the appliance's operating system,
but you should be able to fix it as follows:

1.  Open a terminal window.
2.  Execute:
+
------------------
xfdesktop --reload
------------------
3.  Close the terminal window.

You should find that your trash can is back.

(We'll fix this bug for you for Problem Set 2 onward now that we know
how to fix it!)

[[]]
"Your project has NOT been submitted. Your Course, Repository, Username,
and/or Password were incorrect."
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* *Course* should be: *cs50* (all lowercase, no spaces)
* *Repository* should be: *pset1* (for standard edition) or *hacker1*
(for Hacker Edition), all lowercase and no spaces
* *Username* should be your CS50 Cloud username (not *jharvard*), which
you should have created at https://cloud.cs50.net/
* *Password* should be your CS50 Cloud password (not *crimson*), which
you should have received along with your CS50 Cloud username

If you're sure you're typing everything correctly:

* Make sure you're running version 2.3 of the appliance, which you can
check by opening a terminal and running:
+
-----------------------
rpmquery cs50-appliance
-----------------------
+
If you see 2.1 (which was Fall 2010's version number) instead of 2.3
(which is Fall 2011's), you need to install 2.3, per the below.
* Make sure you're running version 1.2 or higher of `submit50`, which
you can check by opening a terminal and running:
+
-----------------
rpmquery submit50
-----------------
** If you see 1.1, run:
+
---------------------------------------
sudo yum clean all ; sudo yum -y update
---------------------------------------
+
Input *crimson* if prompted for a password. Then re-try `submit50`.
** If you see "package submit50 is not installed", be sure, again, that
you're running version 2.3 of the appliance, not version 2.1.

If you're indeed running version 2.3 of the appliance and have version
1.2 or higher of submit50 installed:

* Try changing your CS50 Cloud password at https://cloud.cs50.net/ to
something that only contains letters and/or numbers. (That constraint
will soon no longer be necessary.) Then re-run `submit50`.

[[]]
My appliance doesn't have Internet access
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This can happen if you tinkered with the appliance's default network
settings (e.g., when you first installed it, when trying to resolve some
issue).

First, confirm that you do not, in fact, have Internet access as
follows:

1.  Open Firefox inside of the appliance.
2.  Try to visit, e.g., http://www.google.com/.

If you can't reach Google, the appliance indeed does not have Internet
access.

To fix this problem, first try:

1.  Shut down appliance.
2.  Reboot your laptop or desktop.
3.  Start VirtualBox.
4.  Start appliance.
5.  Open Firefox inside of the appliance.
6.  Try to visit, e.g., http://www.google.com/.

If you still can't reach Google:

1.  Shut down appliance.
2.  Single-click appliance in VirtualBox's lefthand menu.
3.  Click Settings
4.  Click Network
5.  Click Adapter 1: make sure it's *NAT*
6.  Click Adapter 2: make sure it's *Host-only Adapter*
7.  Click Adapter 3: make sure it's *Bridged Adapter*
8.  Click OK
9.  Boot appliance
10. Open a terminal and execute:
+
----------------------------------------------------
sudo rm -f /etc/udev/rules.d/70-persistent-net.rules
----------------------------------------------------
+
Input *crimson* if prompted for *jharvard*'s password.
11. Reboot appliance.
12. Open Firefox inside of the appliance.
13. Try to visit, e.g., http://www.google.com/.

If you still can't reach Google, email heads@cs50.net explaining your
symptoms.

[[]]
"Error: Cannot retrieve metalink for repository: fedora. Please verify
its path and try again"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you see this message when trying to update the appliance with `yum`,
it usually means your appliance does not have Internet access.

See link:#My_appliance_doesn.27t_have_Internet_access[My appliance
doesn't have Internet access] for tips.

[[]]
"`initialize': getaddrinfo: Name or service not known (Socket Error)"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you see this message when running `submit50`, it usually means your
appliance does not have Internet access.

See link:#My_appliance_doesn.27t_have_Internet_access[My appliance
doesn't have Internet access] for tips.

[[]]
Error: could not access/read saved transaction
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you see this message when running `yum`, it likely means that a
previous update was somehow interrupted. To fix this problem, open a
terminal window and execute:

---------------------------------
sudo package-cleanup --cleandupes
sudo yum clean all
sudo yum -y update
---------------------------------

Input *crimson* if prompted for a password. Your appliance should then
be updated to the latest version.

Let sysadmins@cs50.net if you run into trouble.

[[]]
I have version 2.1 of the appliance instead of 2.3
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

link:CS50_Appliance_2.1[Version 2.1] of the appliance is intended for
folks who want to follow along with http://cs50.tv/2010/fall/[Fall
2010]'s videos. link:CS50_Appliance_2.3[Version 2.3] is what you'll need
for Fall 2011.

If you're using version 2.1 of the appliance, the simplest way to
upgrade to 2.3 is to:

1.  Email yourself any `.c` files you want to keep from your current
appliance, as by logging into your email account with Firefox within
version 2.1 of the appliance.
2.  Shutdown version 2.1 of the appliance.
3.  Download and install version 2.3 of the appliance, per its
link:CS50_Appliance_2.3[HOWTO].
4.  Start version 2.3 of the appliance.
5.  Log into your email account with Firefox, and download your `.c`
files.

Alternatively, you can use
https://manual.cs50.net/CS50_Appliance_2.3#How_to_Synchronize_Files_with_Dropbox[Dropbox]
or
https://manual.cs50.net/CS50_Appliance_2.3#How_to_Transfer_Files_between_Appliance_and_Your_Computer[SFTP
or file-sharing] to transfer files from the old appliance to your hard
drive, and then from your hard drive to the new appliance.

[[]]
My appliance (or computer) keeps freezing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This problem is usually the result of having a computer with relatively
little RAM (e.g., just 1GB). By default, the appliance tries to use
768MB of your RAM, which may be too much to ask! To find out how much
RAM you have:

* On Mac OS, to find out how much RAM you have, select *About This Mac*
under your Apple menu (in your screen's top-left corner) and look to the
right of *Memory*.
* On Windows, open your Start menu (in your screen's bottom-left
corner), right-click *Computer* (if Running Windows 7) or *My Computer*
(if running Windows XP or Windows Vista), select *Properties*, and look
next to *Installed memory (RAM)* under *System*.

To decrease the appliance's RAM use:

1.  Shut down the appliance, if running.
2.  Single-click the appliance in VirtualBox's lefthand menu.
3.  Click *Settings*.
4.  Click *System*.
5.  Change *Base Memory* from *768* to *256*.
6.  Click *OK*.
7.  Start the appliance.

If the appliance continues to freeze and you're on a PC, try to enable
link:Virtualization[hardware virtualization] if your CPU supports it.

Else email sysadmins@cs50.net for additional help.

[[]]
"Welcome to emergency mode. ... Give root password for maintenance"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If the appliance gets halfway through booting, but then puts you in
emergency mode, it probably means that the virtual machine's "disk" has
become corrupted. (We think this can happen if the host (real) computer
is turned off or put to sleep while the virtual machine is still
running.) Try these steps to recover:

1.  Type the appliance's root password (*crimson*), then press Enter.
(The terminal won't respond while you're typing the password.)
2.  At the prompt (which looks like `root@appliance(~):`), run the
command
+
------
df  -h
------
3.  If the output of the above command makes *no* mention of
`/dev/sda1`, then run this command:
+
--------------------------
fsck.ext4  -fyv  /dev/sda1
--------------------------
+
The `/dev/sda1` argument above refers to a disk partition in the
appliance that doesn't contain your data, but is critical to booting the
virtual machine. The `fsck.ext4` command attempts to repair
inconsistencies in the file system stored on that partition.
4.  If the `fsck.ext4` command appears to finish successfully, try
running
+
------
reboot
------
+
to restart the appliance.

It would be ideal if VirtualBox could always put the appliance into a
safe state when it senses the host computer losing consciousness, but
that sometimes doesn't work. So it's probably a good idea to shut the
appliance down (via the green icon in the bottom right corner of its
screen) before turning off your real computer.
