---
tags: []
title: Week_7
---
_Stacks. Queues. Valgrind. Bitwise operators. Hash tables. Trees. Binary
search trees. Tries._

[[]]
Agenda
------

* Announcements
** Problem Set 4 has been returned.
** Want to do Problem Set 5's scavenger hunt? Ends at 11:59pm on Fri
11/12, but we should submit sooner in case there's a tie!
* Demonstrate how to edit a .c file on the cloud using TextWrangler (if
you have a Mac) or Notepad++ (if you have a PC):
** TextWrangler HOWTO
** link:Notepad%2B%2B[Notepad++] HOWTO
* Demonstrate basics of Mercurial (hg), per
http://www.cs50.net/psets/6/pset6.pdf[Problem Set 6]
* Using Valgrind to chase down memory-related bugs. Demo on a buggy
program with:
** `valgrind -v --leak‐check=full a.out`
* Stacks
* Queues
* Hash Tables
* Binary Search Trees
* Tries

[[]]
References
----------

* http://cdn.cs50.net/2009/fall/sections/7/section7.pdf[Section Notes],
Fall 2009
* http://cdn.cs50.net/2009/fall/sections/7/section7.flv?play[Video],
Fall 2009

[[]]
Materials
---------

[[]]
link:Rose's Section[Rose Cao]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

*Fall '10*:

:* Less comfy Media:0Week7.ppt[Slides]

:** Should be less buggy. =/

*Fall '09*:

:* Less comfy Media:Section 7.ppt[Slides] Buggy! D;

:** Topics: Hash Tables, Tries, Huffman Coding

:** Note that topics are a bit different this year (as if you haven't
noticed it already).

[[]]
User:lloyd[Doug Lloyd]
~~~~~~~~~~~~~~~~~~~~~~

I have always taught a section "for those less comfortable". Here is my
"cheat sheet" for Media:CheatSheet7.pdf[Week 7]. 2010 was the first year
I made these, and I intend to hand them out (1) after section (2) only
to those people who actually attended. These are intended as a two-page
capsule summary of important topics. The goal is to refresh students'
minds on these for quiz-preparation purposes, ie. to remember the syntax
of a loop. If other TFs intend to use them, please keep the attribution
to me, and just send me an email saying that you are using them. These
were prepared using LaTeX.

And here's some Media:Week7lloyd.zip[sample code] *(zip)* that
illustrates the concepts covered in that cheat sheet. Note that within
the .zip is a PDF of all of the code therein.
