---
tags: []
title: Installation
---

In order to install the link:..[CS50 Appliance], you first
need to install a http://en.wikipedia.org/wiki/Hypervisor[hypervisor],
which is a program that will let you run
http://en.wikipedia.org/wiki/Virtual_machine[virtual machines] on your
own computer, whether you run Mac OS, Windows, or Linux.

* If you have a *Mac*, we recommend that you install:
** link:#_vmware_fusion[VMware Fusion] if you are a student at Harvard
** link:#_virtualbox[VirtualBox] if you are not a student at Harvard
* If you have a *PC running Windows*, we recommend that you install:
** link:#_vmware_player[VMware Player]
* If you have a *PC running Linux*, we recommend that you install:
** link:#_virtualbox[VirtualBox]

*Once installed, it's not uncommon for the appliance to take 1 – 2
minutes to boot. But if, once at John Harvard's desktop, the appliance
still feels unbearably slow, you might need to enable
link:Hardware Virtualization[hardware virtualization] on your computer
if it's a PC running Windows or Linux. (Hardware virtualization should
be enabled by default on any Intel-based Mac manufactured in the past
few years.) Even with hardware virtualization enabled, though, virtual
machines might still feel slow if your computer is a few years old, has
a CPU that's only 1GHz or so, or has only 1GB or so of RAM.*


== VirtualBox

Here's how to install the link:CS50_Appliance_3[CS50|Appliance] using
VirtualBox.

1.  Install VirtualBox per
+
+
these instructions
+
+
.
2.  Download the latest appliance at
http://mirror.cs50.net/appliance/3/cs50-appliance-3-12-ovf.zip. Then
unzip it. Do not double-click the files within.
3.  Launch VirtualBox (as by single- or double-clicking its icon,
wherever you installed it).
4.  Select *Import Appliance...* from VirtualBox's *File* menu. Click
*Choose*. Navigate your way to that unzipped *cs50-appliance-3* folder,
highlight the *cs50-appliance-3.ovf* file within, and click *Open*. Then
click *Next*. You should see a summary of the appliance's settings.
Click *Import*. You'll then be prompted to agree to the appliance's
http://creativecommons.org/licenses/by-nc-sa/3.0/[license]. If you click
*Agree*, you'll see *CS50 Appliance 3* in VirtualBox's left-hand menu
after a few seconds or minutes. Click *CS50 Appliance 3* to highlight
it, then click *Start*.

That's it! To learn how to use the appliance, see further
link:#_how_to_use_appliance[instructions] down below!


== VMware Fusion

Here's how to install the appliance using VMware Fusion. These
instructions assume that VMware Fusion is already installed.

1.  Download the latest appliance at
http://mirror.cs50.net/appliance/3/cs50-appliance-3-12-vmx.zip. Then
unzip it. *Do not double-click the files within.*
2.  Launch VMware Fusion (as by double-clicking its icon, which is
likely in *Macintosh HD > Applications*).
3.  Ensure that you have version 4.1.1 or later of VMware Fusion, as by
selecting *VMware Fusion > Check for Updates*. Update and relaunch
VMware Fusion as needed.
4.  Select *File > Open...*. Navigate your way to that unzipped
*cs50-appliance-3* folder, highlight the *cs50-appliance-3.vmx* file
within, and click *Open*. Then click VMware Fusion's ▶ button to start
up the appliance.


== VMware Workstation

Here's how to install the appliance using VMware Workstation. These
instructions assume that VMware Workstation is already installed.

1.  Download the latest appliance at
http://mirror.cs50.net/appliance/3/cs50-appliance-3-12-vmx.zip. Then
unzip it. *Do not double-click the files within.*
2.  Move the unzipped `cs50-appliance-3` folder into the folder in which
VMware Workstation stores your VMs (e.g.,
`C:\Users\username\Documents\Virtual Machines\`, where `username` is
your username on your PC.
3.  Launch VMware Workstation (as by clicking *Start > All Programs >
VMware > VMware Workstation*). Select *Open* from VMWare Workstation's
*File* menu. Navigate your way to the unzipped `cs50-appliance-3`
folder, select the `cs50-appliance-3.vmx` file therein, and click
*Open*. A tab labeled *CS50 Appliance 2.3* should appear in the *VMware
Workstation* window. To start the virtual machine, click *Power on this
virtual machine* in that tab.


== Parallels

Here's how to install the appliance using Parallels. These instructions
assume that Parallels is already installed.

_Coming Soon_


== KVM

Here's how to install the appliance using KVM. These instructions assume
that KVM is already installed.

_Coming Soon_
