---
tags: []
title: HarvardNews_API
---

The HarvardNews API allows you to retrieve channels (i.e., publications)
and items (i.e., articles) from http://news.cs50.net/[HarvardNews] in
http://en.wikipedia.org/wiki/Comma-separated_values[CSV],
http://en.wikipedia.org/wiki/JSON[JSON],
http://en.wikipedia.org/wiki/JSON#JSONP[JSONP],
http://php.net/manual/en/function.serialize.php[serialized PHP], or
http://en.wikipedia.org/wiki/RSS[RSS] format. The API provides a
http://en.wikipedia.org/wiki/Representational_State_Transfer[RESTful]
interface, which means that you can query it using simple HTTP GET
requests.

HarvardNews's database contains items from 2009-08-11 through the
present date.

[[]]
Author
------

To report bugs or request features, contact:

mailto:malan@post.harvard.edu[David J. Malan '99] +
http://www.cs.harvard.edu/malan/

[[]]
License
-------

Use of this API is governed by a
http://creativecommons.org/licenses/by-nc/3.0/[Creative Commons
Attribution-Noncommerical 3.0 Unported] license, which means that you
may use its data for non-commercial purposes so long as you attribute
your data to this API, as by including a link to
http://news.cs50.net/[HarvardNews] in your own work. To discuss
commercial purposes, contact the author.

[[]]
Methods
-------

All methods support
http://en.wikipedia.org/wiki/Cross-Origin_Resource_Sharing[CORS].

[[]]
channels
~~~~~~~~

To query the HarvardNews API for channels, contact the server via URLs
in this format:

`http://news.cs50.net/api/1.1/channels?param1=value1&param2=value2&...`

Supported parameters include:

[cols=",",options="header",]
|=======================================================================
|parameter |description
|callback |_Required iff *output* is *jsonp*_. Callback function with
which response will be padded.

|cid |_Optional._ Comma-separated list of channel IDs. If omitted, all
channels will be returned.

|output |_Required._ Format for output. Must be *csv*, *json*, *jsonp*,
or *php*.

|q |_Optional._ Query string. Supports quotes, +, and -. Be sure to
URL-encode this parameter's value (as with PHP's
http://php.net/manual/en/function.urlencode.php[urlencode]).
|=======================================================================

If any parameters are malformed or any required parameters are omitted,
an empty response will be returned along with, possibly, HTTP status
code
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1[400 Bad
Request].

[[]]
CSV
^^^

If you request channels in CSV format (e.g.,
http://news.cs50.net/api/1.1/channels?output=csv), the response will be
a series of comma-delimited rows, per the below:

[code,text]
----------------------------------------------------------------------------------
cid,title,subtitle,link
1,"Harvard Crimson",News,http://www.thecrimson.com/
2,"Harvard Crimson",Sports,http://www.thecrimson.com/
3,"Harvard Crimson",Arts,http://www.thecrimson.com/
4,"Harvard Crimson",Opinion,http://www.thecrimson.com/
5,"Harvard Crimson",FM,http://www.thecrimson.com/
6,"Harvard Magazine",,http://harvardmagazine.com/
7,"Harvard Independent","Quick Hits",http://www.harvardindy.com/
8,"Harvard Lampoon",,http://harvardlampoon.com/
9,"Harvard Advocate",,http://www.theharvardadvocate.com/
10,"Harvard Political Review",,http://www.hpronline.org/
11,Perspective,,http://www.hcs.harvard.edu/~perspy/
12,"Harvard Salient",,http://www.hcs.harvard.edu/~salient/site/
13,"Harvard University Gazette","Top Stories",http://www.hno.harvard.edu/
14,"Harvard University Gazette",News,http://www.hno.harvard.edu/
15,"Harvard University Gazette","Science and Research",http://www.hno.harvard.edu/
16,"Harvard University Gazette",Profiles,http://www.hno.harvard.edu/
17,"Harvard University Gazette",Community,http://www.hno.harvard.edu/
18,"Harvard University Gazette",Sports,http://www.hno.harvard.edu/
19,"Harvard University Gazette",Campus,http://www.hno.harvard.edu/
20,"Harvard University Gazette",Arts,http://www.hno.harvard.edu/
21,"Harvard University Gazette","Press Releases",http://www.hno.harvard.edu/
22,"Harvard University Gazette","Home Page",http://www.hno.harvard.edu/
23,"Harvard Extension School News",,http://www.extension.harvard.edu/
24,"SEAS Newsfeed",,http://www.seas.harvard.edu/
25,"HLS News",,http://www.law.harvard.edu/
26,"Harvard Summer School News",,http://www.summer.harvard.edu/
27,"Harvard Kennedy School",News,http://www.hks.harvard.edu/
28,"Harvard Kennedy School","Press Releases",http://www.hks.harvard.edu/
29,"Graduate School of Arts and Sciences",,http://www.gsas.harvard.edu/
30,"Harvard Medicine",,http://hms.harvard.edu/
31,"Harvard School of Public Health Press Releases",,http://www.hsph.harvard.edu/
32,"Harvard College Economics Review",,http://www.hcs.harvard.edu/hcer/
33,"The Triple Helix",Features,http://thetriplehelix.org/
34,"The Triple Helix","General News",http://thetriplehelix.org/
35,"Harvard Crimson",FlyByBlog,http://www.flybyblog.com/
36,"Harvard Medical School: News Alerts",,http://hms.harvard.edu/
37,HarvardScience,,http://harvardscience.harvard.edu/
38,"HBS Working Knowledge",,http://hbswk.hbs.edu/
39,"HBS Bulletin",,http://www.alumni.hbs.edu/
40,"HPH NOW",,http://www.hsph.harvard.edu/
41,"On Harvard Time Blog",,http://onharvardtime.blogspot.com/
42,"Harvard College Democrats",,http://www.harvarddems.com/
43,"Office for the Arts at Harvard",,http://ofa.fas.harvard.edu/
44,"Harvard Hooligans",,http://harvardhooligans.com/
45,"Greg Mankiw's Blog",,http://gregmankiw.blogspot.com/
46,"Harvard Gazette Online",,http://news.harvard.edu/gazette/
47,"Berkman Center",Newsfeed,http://cyber.law.harvard.edu/
48,"Berkman Center",Announcements,http://cyber.law.harvard.edu/
49,"Berkman Center",MediaBerkman,http://cyber.law.harvard.edu/
50,Noice,,http://verynoice.com/
----------------------------------------------------------------------------------

Note that the response's first row defines the CSV file's fields.
Fields' order may change over time, so do not hardcode indices into your
own code. Use that first row to determine fields' indices dynamically,
per this article on link:Neat_Tricks#Parsing_CSV[parsing CSV].

[[]]
JSON
^^^^

If you request channels in JSON format (e.g.,
http://news.cs50.net/api/1.1/channels?output=json), the response wil be
an array of objects, per the below:

[code,javascript]
---------------------------------------------------------------
[
   {
      "cid":"1",
      "title":"Harvard Crimson",
      "subtitle":"News",
      "link":"http:\/\/www.thecrimson.com\/"
   },
   {
      "cid":"2",
      "title":"Harvard Crimson",
      "subtitle":"Sports",
      "link":"http:\/\/www.thecrimson.com\/"
   },
   {
      "cid":"3",
      "title":"Harvard Crimson",
      "subtitle":"Arts",
      "link":"http:\/\/www.thecrimson.com\/"
   },
   {
      "cid":"4",
      "title":"Harvard Crimson",
      "subtitle":"Opinion",
      "link":"http:\/\/www.thecrimson.com\/"
   },
   {
      "cid":"5",
      "title":"Harvard Crimson",
      "subtitle":"FM",
      "link":"http:\/\/www.thecrimson.com\/"
   },
   {
      "cid":"6",
      "title":"Harvard Magazine",
      "subtitle":null,
      "link":"http:\/\/harvardmagazine.com\/"
   },
   {
      "cid":"7",
      "title":"Harvard Independent",
      "subtitle":"Quick Hits",
      "link":"http:\/\/www.harvardindy.com\/"
   },
   {
      "cid":"8",
      "title":"Harvard Lampoon",
      "subtitle":null,
      "link":"http:\/\/harvardlampoon.com\/"
   },
   {
      "cid":"9",
      "title":"Harvard Advocate",
      "subtitle":null,
      "link":"http:\/\/www.theharvardadvocate.com\/"
   },
   {
      "cid":"10",
      "title":"Harvard Political Review",
      "subtitle":null,
      "link":"http:\/\/www.hpronline.org\/"
   },
   {
      "cid":"11",
      "title":"Perspective",
      "subtitle":null,
      "link":"http:\/\/www.hcs.harvard.edu\/~perspy\/"
   },
   {
      "cid":"12",
      "title":"Harvard Salient",
      "subtitle":null,
      "link":"http:\/\/www.hcs.harvard.edu\/~salient\/site\/"
   },
   {
      "cid":"13",
      "title":"Harvard University Gazette",
      "subtitle":"Top Stories",
      "link":"http:\/\/www.hno.harvard.edu\/"
   },
   {
      "cid":"14",
      "title":"Harvard University Gazette",
      "subtitle":"News",
      "link":"http:\/\/www.hno.harvard.edu\/"
   },
   {
      "cid":"15",
      "title":"Harvard University Gazette",
      "subtitle":"Science and Research",
      "link":"http:\/\/www.hno.harvard.edu\/"
   },
   {
      "cid":"16",
      "title":"Harvard University Gazette",
      "subtitle":"Profiles",
      "link":"http:\/\/www.hno.harvard.edu\/"
   },
   {
      "cid":"17",
      "title":"Harvard University Gazette",
      "subtitle":"Community",
      "link":"http:\/\/www.hno.harvard.edu\/"
   },
   {
      "cid":"18",
      "title":"Harvard University Gazette",
      "subtitle":"Sports",
      "link":"http:\/\/www.hno.harvard.edu\/"
   },
   {
      "cid":"19",
      "title":"Harvard University Gazette",
      "subtitle":"Campus",
      "link":"http:\/\/www.hno.harvard.edu\/"
   },
   {
      "cid":"20",
      "title":"Harvard University Gazette",
      "subtitle":"Arts",
      "link":"http:\/\/www.hno.harvard.edu\/"
   },
   {
      "cid":"21",
      "title":"Harvard University Gazette",
      "subtitle":"Press Releases",
      "link":"http:\/\/www.hno.harvard.edu\/"
   },
   {
      "cid":"22",
      "title":"Harvard University Gazette",
      "subtitle":"Home Page",
      "link":"http:\/\/www.hno.harvard.edu\/"
   },
   {
      "cid":"23",
      "title":"Harvard Extension School News",
      "subtitle":null,
      "link":"http:\/\/www.extension.harvard.edu\/"
   },
   {
      "cid":"24",
      "title":"SEAS Newsfeed",
      "subtitle":null,
      "link":"http:\/\/www.seas.harvard.edu\/"
   },
   {
      "cid":"25",
      "title":"HLS News",
      "subtitle":null,
      "link":"http:\/\/www.law.harvard.edu\/"
   },
   {
      "cid":"26",
      "title":"Harvard Summer School News",
      "subtitle":null,
      "link":"http:\/\/www.summer.harvard.edu\/"
   },
   {
      "cid":"27",
      "title":"Harvard Kennedy School",
      "subtitle":"News",
      "link":"http:\/\/www.hks.harvard.edu\/"
   },
   {
      "cid":"28",
      "title":"Harvard Kennedy School",
      "subtitle":"Press Releases",
      "link":"http:\/\/www.hks.harvard.edu\/"
   },
   {
      "cid":"29",
      "title":"Graduate School of Arts and Sciences",
      "subtitle":null,
      "link":"http:\/\/www.gsas.harvard.edu\/"
   },
   {
      "cid":"30",
      "title":"Harvard Medicine",
      "subtitle":null,
      "link":"http:\/\/hms.harvard.edu\/"
   },
   {
      "cid":"31",
      "title":"Harvard School of Public Health Press Releases",
      "subtitle":null,
      "link":"http:\/\/www.hsph.harvard.edu\/"
   },
   {
      "cid":"32",
      "title":"Harvard College Economics Review",
      "subtitle":null,
      "link":"http:\/\/www.hcs.harvard.edu\/hcer\/"
   },
   {
      "cid":"33",
      "title":"The Triple Helix",
      "subtitle":"Features",
      "link":"http:\/\/thetriplehelix.org\/"
   },
   {
      "cid":"34",
      "title":"The Triple Helix",
      "subtitle":"General News",
      "link":"http:\/\/thetriplehelix.org\/"
   },
   {
      "cid":"35",
      "title":"Harvard Crimson",
      "subtitle":"FlyByBlog",
      "link":"http:\/\/www.flybyblog.com\/"
   },
   {
      "cid":"36",
      "title":"Harvard Medical School: News Alerts",
      "subtitle":null,
      "link":"http:\/\/hms.harvard.edu\/"
   },
   {
      "cid":"37",
      "title":"HarvardScience",
      "subtitle":null,
      "link":"http:\/\/harvardscience.harvard.edu\/"
   },
   {
      "cid":"38",
      "title":"HBS Working Knowledge",
      "subtitle":null,
      "link":"http:\/\/hbswk.hbs.edu\/"
   },
   {
      "cid":"39",
      "title":"HBS Bulletin",
      "subtitle":null,
      "link":"http:\/\/www.alumni.hbs.edu\/"
   },
   {
      "cid":"40",
      "title":"HPH NOW",
      "subtitle":null,
      "link":"http:\/\/www.hsph.harvard.edu\/"
   },
   {
      "cid":"41",
      "title":"On Harvard Time Blog",
      "subtitle":null,
      "link":"http:\/\/onharvardtime.blogspot.com\/"
   },
   {
      "cid":"42",
      "title":"Harvard College Democrats",
      "subtitle":"",
      "link":"http:\/\/www.harvarddems.com\/"
   },
   {
      "cid":"43",
      "title":"Office for the Arts at Harvard",
      "subtitle":null,
      "link":"http:\/\/ofa.fas.harvard.edu\/"
   },
   {
      "cid":"44",
      "title":"Harvard Hooligans",
      "subtitle":null,
      "link":"http:\/\/harvardhooligans.com\/"
   },
   {
      "cid":"45",
      "title":"Greg Mankiw's Blog",
      "subtitle":null,
      "link":"http:\/\/gregmankiw.blogspot.com\/"
   },
   {
      "cid":"46",
      "title":"Harvard Gazette Online",
      "subtitle":null,
      "link":"http:\/\/news.harvard.edu\/gazette\/"
   },
   {
      "cid":"47",
      "title":"Berkman Center",
      "subtitle":"Newsfeed",
      "link":"http:\/\/cyber.law.harvard.edu\/"
   },
   {
      "cid":"48",
      "title":"Berkman Center",
      "subtitle":"Announcements",
      "link":"http:\/\/cyber.law.harvard.edu\/"
   },
   {
      "cid":"49",
      "title":"Berkman Center",
      "subtitle":"MediaBerkman",
      "link":"http:\/\/cyber.law.harvard.edu\/"
   },
   {
      "cid":"50",
      "title":"Noice",
      "subtitle":null,
      "link":"http:\/\/verynoice.com\/"
   }
]
---------------------------------------------------------------

[[]]
JSONP
^^^^^

If you request channels in JSON format (e.g.,
http://news.cs50.net/api/1.1/channels?output=jsonp&callback=parseResponse),
the response will be a padded array of objects, per the below:

[code,javascript]
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
parseResponse([{"cid":"1","title":"Harvard Crimson","subtitle":"News","link":"http:\/\/www.thecrimson.com\/"},{"cid":"2","title":"Harvard Crimson","subtitle":"Sports","link":"http:\/\/www.thecrimson.com\/"},{"cid":"3","title":"Harvard Crimson","subtitle":"Arts","link":"http:\/\/www.thecrimson.com\/"},{"cid":"4","title":"Harvard Crimson","subtitle":"Opinion","link":"http:\/\/www.thecrimson.com\/"},{"cid":"5","title":"Harvard Crimson","subtitle":"FM","link":"http:\/\/www.thecrimson.com\/"},{"cid":"6","title":"Harvard Magazine","subtitle":null,"link":"http:\/\/harvardmagazine.com\/"},{"cid":"7","title":"Harvard Independent","subtitle":"Quick Hits","link":"http:\/\/www.harvardindy.com\/"},{"cid":"8","title":"Harvard Lampoon","subtitle":null,"link":"http:\/\/harvardlampoon.com\/"},{"cid":"9","title":"Harvard Advocate","subtitle":null,"link":"http:\/\/www.theharvardadvocate.com\/"},{"cid":"10","title":"Harvard Political Review","subtitle":null,"link":"http:\/\/www.hpronline.org\/"},{"cid":"11","title":"Perspective","subtitle":null,"link":"http:\/\/www.hcs.harvard.edu\/~perspy\/"},{"cid":"12","title":"Harvard Salient","subtitle":null,"link":"http:\/\/www.hcs.harvard.edu\/~salient\/site\/"},{"cid":"13","title":"Harvard University Gazette","subtitle":"Top Stories","link":"http:\/\/www.hno.harvard.edu\/"},{"cid":"14","title":"Harvard University Gazette","subtitle":"News","link":"http:\/\/www.hno.harvard.edu\/"},{"cid":"15","title":"Harvard University Gazette","subtitle":"Science and Research","link":"http:\/\/www.hno.harvard.edu\/"},{"cid":"16","title":"Harvard University Gazette","subtitle":"Profiles","link":"http:\/\/www.hno.harvard.edu\/"},{"cid":"17","title":"Harvard University Gazette","subtitle":"Community","link":"http:\/\/www.hno.harvard.edu\/"},{"cid":"18","title":"Harvard University Gazette","subtitle":"Sports","link":"http:\/\/www.hno.harvard.edu\/"},{"cid":"19","title":"Harvard University Gazette","subtitle":"Campus","link":"http:\/\/www.hno.harvard.edu\/"},{"cid":"20","title":"Harvard University Gazette","subtitle":"Arts","link":"http:\/\/www.hno.harvard.edu\/"},{"cid":"21","title":"Harvard University Gazette","subtitle":"Press Releases","link":"http:\/\/www.hno.harvard.edu\/"},{"cid":"22","title":"Harvard University Gazette","subtitle":"Home Page","link":"http:\/\/www.hno.harvard.edu\/"},{"cid":"23","title":"Harvard Extension School News","subtitle":null,"link":"http:\/\/www.extension.harvard.edu\/"},{"cid":"24","title":"SEAS Newsfeed","subtitle":null,"link":"http:\/\/www.seas.harvard.edu\/"},{"cid":"25","title":"HLS News","subtitle":null,"link":"http:\/\/www.law.harvard.edu\/"},{"cid":"26","title":"Harvard Summer School News","subtitle":null,"link":"http:\/\/www.summer.harvard.edu\/"},{"cid":"27","title":"Harvard Kennedy School","subtitle":"News","link":"http:\/\/www.hks.harvard.edu\/"},{"cid":"28","title":"Harvard Kennedy School","subtitle":"Press Releases","link":"http:\/\/www.hks.harvard.edu\/"},{"cid":"29","title":"Graduate School of Arts and Sciences","subtitle":null,"link":"http:\/\/www.gsas.harvard.edu\/"},{"cid":"30","title":"Harvard Medicine","subtitle":null,"link":"http:\/\/hms.harvard.edu\/"},{"cid":"31","title":"Harvard School of Public Health Press Releases","subtitle":null,"link":"http:\/\/www.hsph.harvard.edu\/"},{"cid":"32","title":"Harvard College Economics Review","subtitle":null,"link":"http:\/\/www.hcs.harvard.edu\/hcer\/"},{"cid":"33","title":"The Triple Helix","subtitle":"Features","link":"http:\/\/thetriplehelix.org\/"},{"cid":"34","title":"The Triple Helix","subtitle":"General News","link":"http:\/\/thetriplehelix.org\/"},{"cid":"35","title":"Harvard Crimson","subtitle":"FlyByBlog","link":"http:\/\/www.flybyblog.com\/"},{"cid":"36","title":"Harvard Medical School: News Alerts","subtitle":null,"link":"http:\/\/hms.harvard.edu\/"},{"cid":"37","title":"HarvardScience","subtitle":null,"link":"http:\/\/harvardscience.harvard.edu\/"},{"cid":"38","title":"HBS Working Knowledge","subtitle":null,"link":"http:\/\/hbswk.hbs.edu\/"},{"cid":"39","title":"HBS Bulletin","subtitle":null,"link":"http:\/\/www.alumni.hbs.edu\/"},{"cid":"40","title":"HPH NOW","subtitle":null,"link":"http:\/\/www.hsph.harvard.edu\/"},{"cid":"41","title":"On Harvard Time Blog","subtitle":null,"link":"http:\/\/onharvardtime.blogspot.com\/"},{"cid":"42","title":"Harvard College Democrats","subtitle":"","link":"http:\/\/www.harvarddems.com\/"},{"cid":"43","title":"Office for the Arts at Harvard","subtitle":null,"link":"http:\/\/ofa.fas.harvard.edu\/"},{"cid":"44","title":"Harvard Hooligans","subtitle":null,"link":"http:\/\/harvardhooligans.com\/"},{"cid":"45","title":"Greg Mankiw's Blog","subtitle":null,"link":"http:\/\/gregmankiw.blogspot.com\/"},{"cid":"46","title":"Harvard Gazette Online","subtitle":null,"link":"http:\/\/news.harvard.edu\/gazette\/"},{"cid":"47","title":"Berkman Center","subtitle":"Newsfeed","link":"http:\/\/cyber.law.harvard.edu\/"},{"cid":"48","title":"Berkman Center","subtitle":"Announcements","link":"http:\/\/cyber.law.harvard.edu\/"},{"cid":"49","title":"Berkman Center","subtitle":"MediaBerkman","link":"http:\/\/cyber.law.harvard.edu\/"},{"cid":"50","title":"Noice","subtitle":null,"link":"http:\/\/verynoice.com\/"},{"cid":"51","title":"Harvard Business Review","subtitle":null,"link":"http:\/\/hbr.org\/"},{"cid":"52","title":"CS50 Blog","subtitle":null,"link":"http:\/\/www.cs50.net\/"}])
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[]]
PHP
^^^

If you request channels in serialized PHP format (e.g.,
http://news.cs50.net/api/1.1/channels?output=php), the response will be
a serialized array of associative arrays, per the below:

[code,php]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
a:50:{i:0;a:4:{s:3:"cid";s:1:"1";s:5:"title";s:15:"Harvard Crimson";s:8:"subtitle";s:4:"News";s:4:"link";s:26:"http://www.thecrimson.com/";}i:1;a:4:{s:3:"cid";s:1:"2";s:5:"title";s:15:"Harvard Crimson";s:8:"subtitle";s:6:"Sports";s:4:"link";s:26:"http://www.thecrimson.com/";}i:2;a:4:{s:3:"cid";s:1:"3";s:5:"title";s:15:"Harvard Crimson";s:8:"subtitle";s:4:"Arts";s:4:"link";s:26:"http://www.thecrimson.com/";}i:3;a:4:{s:3:"cid";s:1:"4";s:5:"title";s:15:"Harvard Crimson";s:8:"subtitle";s:7:"Opinion";s:4:"link";s:26:"http://www.thecrimson.com/";}i:4;a:4:{s:3:"cid";s:1:"5";s:5:"title";s:15:"Harvard Crimson";s:8:"subtitle";s:2:"FM";s:4:"link";s:26:"http://www.thecrimson.com/";}i:5;a:4:{s:3:"cid";s:1:"6";s:5:"title";s:16:"Harvard Magazine";s:8:"subtitle";N;s:4:"link";s:27:"http://harvardmagazine.com/";}i:6;a:4:{s:3:"cid";s:1:"7";s:5:"title";s:19:"Harvard Independent";s:8:"subtitle";s:10:"Quick Hits";s:4:"link";s:27:"http://www.harvardindy.com/";}i:7;a:4:{s:3:"cid";s:1:"8";s:5:"title";s:15:"Harvard Lampoon";s:8:"subtitle";N;s:4:"link";s:26:"http://harvardlampoon.com/";}i:8;a:4:{s:3:"cid";s:1:"9";s:5:"title";s:16:"Harvard Advocate";s:8:"subtitle";N;s:4:"link";s:34:"http://www.theharvardadvocate.com/";}i:9;a:4:{s:3:"cid";s:2:"10";s:5:"title";s:24:"Harvard Political Review";s:8:"subtitle";N;s:4:"link";s:25:"http://www.hpronline.org/";}i:10;a:4:{s:3:"cid";s:2:"11";s:5:"title";s:11:"Perspective";s:8:"subtitle";N;s:4:"link";s:35:"http://www.hcs.harvard.edu/~perspy/";}i:11;a:4:{s:3:"cid";s:2:"12";s:5:"title";s:15:"Harvard Salient";s:8:"subtitle";N;s:4:"link";s:41:"http://www.hcs.harvard.edu/~salient/site/";}i:12;a:4:{s:3:"cid";s:2:"13";s:5:"title";s:26:"Harvard University Gazette";s:8:"subtitle";s:11:"Top Stories";s:4:"link";s:27:"http://www.hno.harvard.edu/";}i:13;a:4:{s:3:"cid";s:2:"14";s:5:"title";s:26:"Harvard University Gazette";s:8:"subtitle";s:4:"News";s:4:"link";s:27:"http://www.hno.harvard.edu/";}i:14;a:4:{s:3:"cid";s:2:"15";s:5:"title";s:26:"Harvard University Gazette";s:8:"subtitle";s:20:"Science and Research";s:4:"link";s:27:"http://www.hno.harvard.edu/";}i:15;a:4:{s:3:"cid";s:2:"16";s:5:"title";s:26:"Harvard University Gazette";s:8:"subtitle";s:8:"Profiles";s:4:"link";s:27:"http://www.hno.harvard.edu/";}i:16;a:4:{s:3:"cid";s:2:"17";s:5:"title";s:26:"Harvard University Gazette";s:8:"subtitle";s:9:"Community";s:4:"link";s:27:"http://www.hno.harvard.edu/";}i:17;a:4:{s:3:"cid";s:2:"18";s:5:"title";s:26:"Harvard University Gazette";s:8:"subtitle";s:6:"Sports";s:4:"link";s:27:"http://www.hno.harvard.edu/";}i:18;a:4:{s:3:"cid";s:2:"19";s:5:"title";s:26:"Harvard University Gazette";s:8:"subtitle";s:6:"Campus";s:4:"link";s:27:"http://www.hno.harvard.edu/";}i:19;a:4:{s:3:"cid";s:2:"20";s:5:"title";s:26:"Harvard University Gazette";s:8:"subtitle";s:4:"Arts";s:4:"link";s:27:"http://www.hno.harvard.edu/";}i:20;a:4:{s:3:"cid";s:2:"21";s:5:"title";s:26:"Harvard University Gazette";s:8:"subtitle";s:14:"Press Releases";s:4:"link";s:27:"http://www.hno.harvard.edu/";}i:21;a:4:{s:3:"cid";s:2:"22";s:5:"title";s:26:"Harvard University Gazette";s:8:"subtitle";s:9:"Home Page";s:4:"link";s:27:"http://www.hno.harvard.edu/";}i:22;a:4:{s:3:"cid";s:2:"23";s:5:"title";s:29:"Harvard Extension School News";s:8:"subtitle";N;s:4:"link";s:33:"http://www.extension.harvard.edu/";}i:23;a:4:{s:3:"cid";s:2:"24";s:5:"title";s:13:"SEAS Newsfeed";s:8:"subtitle";N;s:4:"link";s:28:"http://www.seas.harvard.edu/";}i:24;a:4:{s:3:"cid";s:2:"25";s:5:"title";s:8:"HLS News";s:8:"subtitle";N;s:4:"link";s:27:"http://www.law.harvard.edu/";}i:25;a:4:{s:3:"cid";s:2:"26";s:5:"title";s:26:"Harvard Summer School News";s:8:"subtitle";N;s:4:"link";s:30:"http://www.summer.harvard.edu/";}i:26;a:4:{s:3:"cid";s:2:"27";s:5:"title";s:22:"Harvard Kennedy School";s:8:"subtitle";s:4:"News";s:4:"link";s:27:"http://www.hks.harvard.edu/";}i:27;a:4:{s:3:"cid";s:2:"28";s:5:"title";s:22:"Harvard Kennedy School";s:8:"subtitle";s:14:"Press Releases";s:4:"link";s:27:"http://www.hks.harvard.edu/";}i:28;a:4:{s:3:"cid";s:2:"29";s:5:"title";s:36:"Graduate School of Arts and Sciences";s:8:"subtitle";N;s:4:"link";s:28:"http://www.gsas.harvard.edu/";}i:29;a:4:{s:3:"cid";s:2:"30";s:5:"title";s:16:"Harvard Medicine";s:8:"subtitle";N;s:4:"link";s:23:"http://hms.harvard.edu/";}i:30;a:4:{s:3:"cid";s:2:"31";s:5:"title";s:46:"Harvard School of Public Health Press Releases";s:8:"subtitle";N;s:4:"link";s:28:"http://www.hsph.harvard.edu/";}i:31;a:4:{s:3:"cid";s:2:"32";s:5:"title";s:32:"Harvard College Economics Review";s:8:"subtitle";N;s:4:"link";s:32:"http://www.hcs.harvard.edu/hcer/";}i:32;a:4:{s:3:"cid";s:2:"33";s:5:"title";s:16:"The Triple Helix";s:8:"subtitle";s:8:"Features";s:4:"link";s:26:"http://thetriplehelix.org/";}i:33;a:4:{s:3:"cid";s:2:"34";s:5:"title";s:16:"The Triple Helix";s:8:"subtitle";s:12:"General News";s:4:"link";s:26:"http://thetriplehelix.org/";}i:34;a:4:{s:3:"cid";s:2:"35";s:5:"title";s:15:"Harvard Crimson";s:8:"subtitle";s:9:"FlyByBlog";s:4:"link";s:25:"http://www.flybyblog.com/";}i:35;a:4:{s:3:"cid";s:2:"36";s:5:"title";s:35:"Harvard Medical School: News Alerts";s:8:"subtitle";N;s:4:"link";s:23:"http://hms.harvard.edu/";}i:36;a:4:{s:3:"cid";s:2:"37";s:5:"title";s:14:"HarvardScience";s:8:"subtitle";N;s:4:"link";s:34:"http://harvardscience.harvard.edu/";}i:37;a:4:{s:3:"cid";s:2:"38";s:5:"title";s:21:"HBS Working Knowledge";s:8:"subtitle";N;s:4:"link";s:21:"http://hbswk.hbs.edu/";}i:38;a:4:{s:3:"cid";s:2:"39";s:5:"title";s:12:"HBS Bulletin";s:8:"subtitle";N;s:4:"link";s:26:"http://www.alumni.hbs.edu/";}i:39;a:4:{s:3:"cid";s:2:"40";s:5:"title";s:7:"HPH NOW";s:8:"subtitle";N;s:4:"link";s:28:"http://www.hsph.harvard.edu/";}i:40;a:4:{s:3:"cid";s:2:"41";s:5:"title";s:20:"On Harvard Time Blog";s:8:"subtitle";N;s:4:"link";s:34:"http://onharvardtime.blogspot.com/";}i:41;a:4:{s:3:"cid";s:2:"42";s:5:"title";s:25:"Harvard College Democrats";s:8:"subtitle";s:0:"";s:4:"link";s:27:"http://www.harvarddems.com/";}i:42;a:4:{s:3:"cid";s:2:"43";s:5:"title";s:30:"Office for the Arts at Harvard";s:8:"subtitle";N;s:4:"link";s:27:"http://ofa.fas.harvard.edu/";}i:43;a:4:{s:3:"cid";s:2:"44";s:5:"title";s:17:"Harvard Hooligans";s:8:"subtitle";N;s:4:"link";s:28:"http://harvardhooligans.com/";}i:44;a:4:{s:3:"cid";s:2:"45";s:5:"title";s:18:"Greg Mankiw's Blog";s:8:"subtitle";N;s:4:"link";s:31:"http://gregmankiw.blogspot.com/";}i:45;a:4:{s:3:"cid";s:2:"46";s:5:"title";s:22:"Harvard Gazette Online";s:8:"subtitle";N;s:4:"link";s:32:"http://news.harvard.edu/gazette/";}i:46;a:4:{s:3:"cid";s:2:"47";s:5:"title";s:14:"Berkman Center";s:8:"subtitle";s:8:"Newsfeed";s:4:"link";s:29:"http://cyber.law.harvard.edu/";}i:47;a:4:{s:3:"cid";s:2:"48";s:5:"title";s:14:"Berkman Center";s:8:"subtitle";s:13:"Announcements";s:4:"link";s:29:"http://cyber.law.harvard.edu/";}i:48;a:4:{s:3:"cid";s:2:"49";s:5:"title";s:14:"Berkman Center";s:8:"subtitle";s:12:"MediaBerkman";s:4:"link";s:29:"http://cyber.law.harvard.edu/";}i:49;a:4:{s:3:"cid";s:2:"50";s:5:"title";s:5:"Noice";s:8:"subtitle";N;s:4:"link";s:21:"http://verynoice.com/";}}
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Once you http://php.net/manual/en/function.unserialize.php[unserialize]
that response, you'll have the below in memory:

[code,php]
---------------------------------------------------------------------
Array
(
    [0] => Array
        (
            [cid] => 1
            [title] => Harvard Crimson
            [subtitle] => News
            [link] => http://www.thecrimson.com/
        )

    [1] => Array
        (
            [cid] => 2
            [title] => Harvard Crimson
            [subtitle] => Sports
            [link] => http://www.thecrimson.com/
        )

    [2] => Array
        (
            [cid] => 3
            [title] => Harvard Crimson
            [subtitle] => Arts
            [link] => http://www.thecrimson.com/
        )

    [3] => Array
        (
            [cid] => 4
            [title] => Harvard Crimson
            [subtitle] => Opinion
            [link] => http://www.thecrimson.com/
        )

    [4] => Array
        (
            [cid] => 5
            [title] => Harvard Crimson
            [subtitle] => FM
            [link] => http://www.thecrimson.com/
        )

    [5] => Array
        (
            [cid] => 6
            [title] => Harvard Magazine
            [subtitle] => 
            [link] => http://harvardmagazine.com/
        )

    [6] => Array
        (
            [cid] => 7
            [title] => Harvard Independent
            [subtitle] => Quick Hits
            [link] => http://www.harvardindy.com/
        )

    [7] => Array
        (
            [cid] => 8
            [title] => Harvard Lampoon
            [subtitle] => 
            [link] => http://harvardlampoon.com/
        )

    [8] => Array
        (
            [cid] => 9
            [title] => Harvard Advocate
            [subtitle] => 
            [link] => http://www.theharvardadvocate.com/
        )

    [9] => Array
        (
            [cid] => 10
            [title] => Harvard Political Review
            [subtitle] => 
            [link] => http://www.hpronline.org/
        )

    [10] => Array
        (
            [cid] => 11
            [title] => Perspective
            [subtitle] => 
            [link] => http://www.hcs.harvard.edu/~perspy/
        )

    [11] => Array
        (
            [cid] => 12
            [title] => Harvard Salient
            [subtitle] => 
            [link] => http://www.hcs.harvard.edu/~salient/site/
        )

    [12] => Array
        (
            [cid] => 13
            [title] => Harvard University Gazette
            [subtitle] => Top Stories
            [link] => http://www.hno.harvard.edu/
        )

    [13] => Array
        (
            [cid] => 14
            [title] => Harvard University Gazette
            [subtitle] => News
            [link] => http://www.hno.harvard.edu/
        )

    [14] => Array
        (
            [cid] => 15
            [title] => Harvard University Gazette
            [subtitle] => Science and Research
            [link] => http://www.hno.harvard.edu/
        )

    [15] => Array
        (
            [cid] => 16
            [title] => Harvard University Gazette
            [subtitle] => Profiles
            [link] => http://www.hno.harvard.edu/
        )

    [16] => Array
        (
            [cid] => 17
            [title] => Harvard University Gazette
            [subtitle] => Community
            [link] => http://www.hno.harvard.edu/
        )

    [17] => Array
        (
            [cid] => 18
            [title] => Harvard University Gazette
            [subtitle] => Sports
            [link] => http://www.hno.harvard.edu/
        )

    [18] => Array
        (
            [cid] => 19
            [title] => Harvard University Gazette
            [subtitle] => Campus
            [link] => http://www.hno.harvard.edu/
        )

    [19] => Array
        (
            [cid] => 20
            [title] => Harvard University Gazette
            [subtitle] => Arts
            [link] => http://www.hno.harvard.edu/
        )

    [20] => Array
        (
            [cid] => 21
            [title] => Harvard University Gazette
            [subtitle] => Press Releases
            [link] => http://www.hno.harvard.edu/
        )

    [21] => Array
        (
            [cid] => 22
            [title] => Harvard University Gazette
            [subtitle] => Home Page
            [link] => http://www.hno.harvard.edu/
        )

    [22] => Array
        (
            [cid] => 23
            [title] => Harvard Extension School News
            [subtitle] => 
            [link] => http://www.extension.harvard.edu/
        )

    [23] => Array
        (
            [cid] => 24
            [title] => SEAS Newsfeed
            [subtitle] => 
            [link] => http://www.seas.harvard.edu/
        )

    [24] => Array
        (
            [cid] => 25
            [title] => HLS News
            [subtitle] => 
            [link] => http://www.law.harvard.edu/
        )

    [25] => Array
        (
            [cid] => 26
            [title] => Harvard Summer School News
            [subtitle] => 
            [link] => http://www.summer.harvard.edu/
        )

    [26] => Array
        (
            [cid] => 27
            [title] => Harvard Kennedy School
            [subtitle] => News
            [link] => http://www.hks.harvard.edu/
        )

    [27] => Array
        (
            [cid] => 28
            [title] => Harvard Kennedy School
            [subtitle] => Press Releases
            [link] => http://www.hks.harvard.edu/
        )

    [28] => Array
        (
            [cid] => 29
            [title] => Graduate School of Arts and Sciences
            [subtitle] => 
            [link] => http://www.gsas.harvard.edu/
        )

    [29] => Array
        (
            [cid] => 30
            [title] => Harvard Medicine
            [subtitle] => 
            [link] => http://hms.harvard.edu/
        )

    [30] => Array
        (
            [cid] => 31
            [title] => Harvard School of Public Health Press Releases
            [subtitle] => 
            [link] => http://www.hsph.harvard.edu/
        )

    [31] => Array
        (
            [cid] => 32
            [title] => Harvard College Economics Review
            [subtitle] => 
            [link] => http://www.hcs.harvard.edu/hcer/
        )

    [32] => Array
        (
            [cid] => 33
            [title] => The Triple Helix
            [subtitle] => Features
            [link] => http://thetriplehelix.org/
        )

    [33] => Array
        (
            [cid] => 34
            [title] => The Triple Helix
            [subtitle] => General News
            [link] => http://thetriplehelix.org/
        )

    [34] => Array
        (
            [cid] => 35
            [title] => Harvard Crimson
            [subtitle] => FlyByBlog
            [link] => http://www.flybyblog.com/
        )

    [35] => Array
        (
            [cid] => 36
            [title] => Harvard Medical School: News Alerts
            [subtitle] => 
            [link] => http://hms.harvard.edu/
        )

    [36] => Array
        (
            [cid] => 37
            [title] => HarvardScience
            [subtitle] => 
            [link] => http://harvardscience.harvard.edu/
        )

    [37] => Array
        (
            [cid] => 38
            [title] => HBS Working Knowledge
            [subtitle] => 
            [link] => http://hbswk.hbs.edu/
        )

    [38] => Array
        (
            [cid] => 39
            [title] => HBS Bulletin
            [subtitle] => 
            [link] => http://www.alumni.hbs.edu/
        )

    [39] => Array
        (
            [cid] => 40
            [title] => HPH NOW
            [subtitle] => 
            [link] => http://www.hsph.harvard.edu/
        )

    [40] => Array
        (
            [cid] => 41
            [title] => On Harvard Time Blog
            [subtitle] => 
            [link] => http://onharvardtime.blogspot.com/
        )

    [41] => Array
        (
            [cid] => 42
            [title] => Harvard College Democrats
            [subtitle] => 
            [link] => http://www.harvarddems.com/
        )

    [42] => Array
        (
            [cid] => 43
            [title] => Office for the Arts at Harvard
            [subtitle] => 
            [link] => http://ofa.fas.harvard.edu/
        )

    [43] => Array
        (
            [cid] => 44
            [title] => Harvard Hooligans
            [subtitle] => 
            [link] => http://harvardhooligans.com/
        )

    [44] => Array
        (
            [cid] => 45
            [title] => Greg Mankiw's Blog
            [subtitle] => 
            [link] => http://gregmankiw.blogspot.com/
        )

    [45] => Array
        (
            [cid] => 46
            [title] => Harvard Gazette Online
            [subtitle] => 
            [link] => http://news.harvard.edu/gazette/
        )

    [46] => Array
        (
            [cid] => 47
            [title] => Berkman Center
            [subtitle] => Newsfeed
            [link] => http://cyber.law.harvard.edu/
        )

    [47] => Array
        (
            [cid] => 48
            [title] => Berkman Center
            [subtitle] => Announcements
            [link] => http://cyber.law.harvard.edu/
        )

    [48] => Array
        (
            [cid] => 49
            [title] => Berkman Center
            [subtitle] => MediaBerkman
            [link] => http://cyber.law.harvard.edu/
        )

    [49] => Array
        (
            [cid] => 50
            [title] => Noice
            [subtitle] => 
            [link] => http://verynoice.com/
        )

)
---------------------------------------------------------------------

[[]]
items
~~~~~

To query the HarvardNews API for items, contact the server via URLs in
this format:

`http://news.cs50.net/api/1.1/items?param1=value1&param2=value2&...`

Supported parameters include:

[cols=",",options="header",]
|=======================================================================
|parameter |description
|callback |_Required iff *output* is *jsonp*_. Callback function with
which response will be padded.

|cid |channel IDs]]. If omitted, all channels will be searched.

|edt |_Optional._ An end date/time in *YYYY-MM-DD* or
*YYYY-MM-DDTHH:MM:SS* format, where *HH* is in 24-hour time. (Don't
overlook the *T* between *YYYY-MM-DD* and *HH:MM:SS* in the latter.)
Items published before or on this date/time will be returned. If
omitted, no end date/time will be assumed.

|output |_Required._ Format for output. Must be *csv*, *json*, *jsonp*,
*php*, or *rss*.

|q |_Optional._ Query string. Supports quotes, +, and -. Be sure to
URL-encode this parameter's value (as with PHP's
http://php.net/manual/en/function.urlencode.php[urlencode]).

|sdt |_Optional._ A start date/time in *YYYY-MM-DD* or
*YYYY-MM-DDTHH:MM:SS* format, where *HH* is in 24-hour time. (Don't
overlook the *T* between *YYYY-MM-DD* and *HH:MM:SS* in the latter.)
Items published on or after this date/time will be returned. If omitted,
the current date/time will be assumed.
|=======================================================================

If any parameters are malformed or any required parameters are omitted,
an empty response will be returned along with, possibly, HTTP status
code
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1[400 Bad
Request].

Responses include no more than 256 items.

[[]]
CSV
^^^

If you request items in CSV format (e.g.,
http://news.cs50.net/api/1.1/items?cid=23&output=csv), the response will
be a series of comma-delimited rows, per the below:

[code,text]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
title,link,description,pubDate,cid
"In memoriam: Karel Liem",http://feedproxy.google.com/~r/harvardextension/~3/b-zOk9Izi4M/liem.jsp,"Biologist Karel F. Liem, PhD, the Henry Bryant Bigelow Professor of Ichthyology at Harvard and long-time Extension School faculty member passed away this summer after a long illness.",2009-10-26T00:00:00,23
"Pfister honored for work with fungi",http://feedproxy.google.com/~r/harvardextension/~3/SaPl0v01SmU/pfister.jsp,"The Northeast Mycological Federation has presented the Amicus Tironum Award to Donald Pfister, Asa Gray Professor of Systematic Botany at Harvard, curator of Harvards Farlow Library and Herbarium, and Harvard Extension School faculty member.",2009-10-26T00:00:00,23
"Read the new student blogs",http://feedproxy.google.com/~r/harvardextension/~3/quYHjJ_fzjY/,"Extension School students are blogging. Read what they have to say about coursework, faculty, and balancing the pursuit of a degree with careers, families, and everything in between.",2009-10-19T00:00:00,23
"Students launch food and clothing drive",http://feedproxy.google.com/~r/harvardextension/~3/5TbjieLr5tY/food.jsp,"Boston and Cambridge food pantries and homeless and womens shelters will receive much-needed assistance this fall through the charitable efforts of members of the Harvard Extension Service and Leadership Society (a subgroup of the Harvard Extension Student Association).",2009-10-19T00:00:00,23
"Harvard monitoring H1N1 influenza, provides tips to avoid it",http://feedproxy.google.com/~r/harvardextension/~3/BP0BqdQqZSw/h1n1.jsp,"Harvard University officials are monitoring the H1N1 influenza (swine flu) and have provided tips for students to help avoid catching or spreading the flu this fall.",2009-10-07T13:45:01,23
"Registration open: US-Pakistan Foreign Relations Conference",http://feedproxy.google.com/~r/harvardextension/~3/I-w_NE3JqQE/foreignrelations.jsp,"Through October 10, you can register for the United States-Pakistan Foreign Relations Conference, which features keynote speakers such as Massachusetts Congressman John F. Tierney and Pakistans ambassador to the United States, Husain Haqqani, and several well-known panelists.
 ",2009-10-07T13:45:01,23
"Watch the videos of Centennial Academic Convocation",http://feedproxy.google.com/~r/harvardextension/~3/iny6dYoSKFs/convovideo.jsp,"Watch the video stream of our Centennial Academic Convocation that was on September 25.
 ",2009-10-07T13:45:01,23
"Check out the free career, academic, and graduate school workshops",http://feedproxy.google.com/~r/harvardextension/~3/OxGE9aGHrMI/,"Throughout the year CARC offers more than 60 free academic, graduate school, and career workshops. The sessions include topics like how to improve your reading strategies, how to write a solid graduate application essay, and how to leverage your degree in your current career. ",2009-08-31T00:00:00,23
"Late registration with fee continues through Sept. 13",http://feedproxy.google.com/~r/harvardextension/~3/v2z8rgKcfY8/,"You can still register for courses, with a $50 late fee, through September 13. ",2009-08-31T00:00:00,23
"New bioengineering and nanotechnologies offerings keep biotech program current",http://feedproxy.google.com/~r/harvardextension/~3/yGfGxkOLliQ/biotech.jsp,"The biotechnology program at the Harvard Extension School continues to find itself at the leading edge of science education, this year offering several new courses and a new masters concentration in the hot topic area of bioengineering and nanotechnologies. ",2009-08-31T00:00:00,23
"Discounted gym membership available to Extension School students through October 20",http://feedproxy.google.com/~r/harvardextension/~3/ybKWdvjxlm0/gym.jsp,"Until October 20th Extension School students will receive 50 percent off the enrollment fee and $60 dollars off per month at Wellbridge Athletic Club. Students will need to present a valid ID or a copy of their registration in order to receive the special rates. ",2009-08-29T23:41:49,23
"Gary King named University Professor",http://feedproxy.google.com/~r/harvardextension/~3/wnFYP_Y5h7U/king.jsp,"Gary King, the David Florence Professor of Government in the Faculty of Arts and Sciences and Extension School faculty, is one of 2 Harvard faculty members to have recently been named University Professor, Harvards highest professorial distinction. ",2009-08-29T23:41:49,23
"Management class project nets record donations for School on Wheels",http://feedproxy.google.com/~r/harvardextension/~3/yfH8DdGCx30/croteau.jsp,"The spring 2009 students of MGMT E-4000 collected child backpacks and adult school bags to make a record donation to School on Wheels as part of a class project. ",2009-08-29T23:41:49,23
"Pizzagalli makes strides to understand impact of childhood adversity",http://feedproxy.google.com/~r/harvardextension/~3/iIcGTUt2k8I/pizzagalli.jsp,"A new study by Harvard Extension School faculty member Diego Pizzagalli, the John and Ruth Hazel Associate Professor of the Social Sciences in the Department of Psychology at Harvard, and Daniel Dillion, a Harvard postdoctoral researcher, found that people who faced adversity in their childhoods are less likely to respond in the reward-processing regions of their brains. ",2009-08-29T23:41:49,23
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Note that the response's first row defines the CSV file's fields.
Fields' order may change over time, so do not hardcode indices into your
own code. Use that first row to determine fields' indices dynamically,
per this article on link:Neat_Tricks#Parsing_CSV[parsing CSV].

[[]]
JSON
^^^^

If you request items in JSON format (e.g.,
http://news.cs50.net/api/1.1/items?cid=23&output=json), the response wil
be an array of objects, per the below:

[code,javascript]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[
   {
      "title":"In memoriam: Karel Liem",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/b-zOk9Izi4M\/liem.jsp",
      "description":"Biologist Karel F. Liem, PhD, the Henry Bryant Bigelow Professor of Ichthyology at Harvard and long-time Extension School faculty member passed away this summer after a long illness.",
      "pubDate":"2009-10-26T00:00:00",
      "cid":"23"
   },
   {
      "title":"Pfister honored for work with fungi",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/SaPl0v01SmU\/pfister.jsp",
      "description":"The Northeast Mycological Federation has presented the Amicus Tironum Award to Donald Pfister, Asa Gray Professor of Systematic Botany at Harvard, curator of Harvard\u2019s Farlow Library and Herbarium, and Harvard Extension School faculty member.",
      "pubDate":"2009-10-26T00:00:00",
      "cid":"23"
   },
   {
      "title":"Read the new student blogs",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/quYHjJ_fzjY\/",
      "description":"Extension School students are blogging. Read what they have to say about coursework, faculty, and balancing the pursuit of a degree with careers, families, and everything in between.",
      "pubDate":"2009-10-19T00:00:00",
      "cid":"23"
   },
   {
      "title":"Students launch food and clothing drive",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/5TbjieLr5tY\/food.jsp",
      "description":"Boston and Cambridge food pantries and homeless and women\u2019s shelters will receive much-needed assistance this fall through the charitable efforts of members of the Harvard Extension Service and Leadership Society (a subgroup of the Harvard Extension Student Association).",
      "pubDate":"2009-10-19T00:00:00",
      "cid":"23"
   },
   {
      "title":"Harvard monitoring H1N1 influenza, provides tips to avoid it",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/BP0BqdQqZSw\/h1n1.jsp",
      "description":"Harvard University officials are monitoring the H1N1 influenza (swine flu) and have provided tips for students to help avoid catching or spreading the flu this fall.",
      "pubDate":"2009-10-07T13:45:01",
      "cid":"23"
   },
   {
      "title":"Registration open: US-Pakistan Foreign Relations Conference",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/I-w_NE3JqQE\/foreignrelations.jsp",
      "description":"Through October 10, you can register for the United States-Pakistan Foreign Relations Conference, which features keynote speakers such as Massachusetts Congressman John F. Tierney and Pakistan\u2019s ambassador to the United States, Husain Haqqani, and several well-known panelists.\n ",
      "pubDate":"2009-10-07T13:45:01",
      "cid":"23"
   },
   {
      "title":"Watch the videos of Centennial Academic Convocation",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/iny6dYoSKFs\/convovideo.jsp",
      "description":"Watch the video stream of our Centennial Academic Convocation that was on September 25.\n ",
      "pubDate":"2009-10-07T13:45:01",
      "cid":"23"
   },
   {
      "title":"Check out the free career, academic, and graduate school workshops",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/OxGE9aGHrMI\/",
      "description":"Throughout the year CARC offers more than 60 free academic, graduate school, and career workshops. The sessions include topics like how to improve your reading strategies, how to write a solid graduate application essay, and how to leverage your degree in your current career. ",
      "pubDate":"2009-08-31T00:00:00",
      "cid":"23"
   },
   {
      "title":"Late registration with fee continues through Sept. 13",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/v2z8rgKcfY8\/",
      "description":"You can still register for courses, with a $50 late fee, through September 13. ",
      "pubDate":"2009-08-31T00:00:00",
      "cid":"23"
   },
   {
      "title":"New bioengineering and nanotechnologies offerings keep biotech program current",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/yGfGxkOLliQ\/biotech.jsp",
      "description":"The biotechnology program at the Harvard Extension School continues to find itself at the leading edge of science education, this year offering several new courses and a new master\u2019s concentration in the hot topic area of bioengineering and nanotechnologies. ",
      "pubDate":"2009-08-31T00:00:00",
      "cid":"23"
   },
   {
      "title":"Discounted gym membership available to Extension School students through October 20",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/ybKWdvjxlm0\/gym.jsp",
      "description":"Until October 20th Extension School students will receive 50 percent off the enrollment fee and $60 dollars off per month at Wellbridge Athletic Club. Students will need to present a valid ID or a copy of their registration in order to receive the special rates. ",
      "pubDate":"2009-08-29T23:41:49",
      "cid":"23"
   },
   {
      "title":"Gary King named University Professor",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/wnFYP_Y5h7U\/king.jsp",
      "description":"Gary King, the David Florence Professor of Government in the Faculty of Arts and Sciences and Extension School faculty, is one of 2 Harvard faculty members to have recently been named University Professor, Harvard\u2019s highest professorial distinction. ",
      "pubDate":"2009-08-29T23:41:49",
      "cid":"23"
   },
   {
      "title":"Management class project nets record donations for School on Wheels",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/yfH8DdGCx30\/croteau.jsp",
      "description":"The spring 2009 students of MGMT E-4000 collected child backpacks and adult school bags to make a record donation to School on Wheels as part of a class project. ",
      "pubDate":"2009-08-29T23:41:49",
      "cid":"23"
   },
   {
      "title":"Pizzagalli makes strides to understand impact of childhood adversity",
      "link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/iIcGTUt2k8I\/pizzagalli.jsp",
      "description":"A new study by Harvard Extension School faculty member Diego Pizzagalli, the John and Ruth Hazel Associate Professor of the Social Sciences in the Department of Psychology at Harvard, and Daniel Dillion, a Harvard postdoctoral researcher, found that people who faced adversity in their childhoods are less likely to respond in the reward-processing regions of their brains. ",
      "pubDate":"2009-08-29T23:41:49",
      "cid":"23"
   }
]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[]]
JSONP
^^^^^

If you request items in JSONP format (e.g.,
http://news.cs50.net/api/1.1/items?cid=23&output=jsonp&callback=parseResponse),
the response will be a padded array of objects, per the below:

[code,javascript]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
parseResponse([{"title":"Centennial event Feb. 19: Panel discussion on the challenges of writing history","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/KYCmGthW9Ps\/","description":"A symposium on the challenges and new frontiers of writing history\u2014from how new technology facilitates research to the question of how to shape the narrative for the general versus the specialist audience.","pubDate":"2010-02-03T00:00:00","cid":"23"},{"title":"Dean wins Frandson Award for The Gates Unbarred","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/NL4U5zIZbEU\/frandson.jsp","description":"It has been announced that Dean Michael Shinagel has won the 2009 Frandson Award for Literature, given annually by the University Continuing Education Association (UCEA) for his book The Gates Unbarred: A History of University Extension at Harvard, 1910\u20132009.","pubDate":"2010-02-03T00:00:00","cid":"23"},{"title":"Artist Chisholm donates paintingss","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/4guGrMhkIYg\/chisholm.jsp","description":"Acclaimed local artist and veteran drawing instructor James Ross Chisholm generously donated 2 of his works to the Harvard Extension School during an informal ceremony held in the Grossman Common Room.","pubDate":"2009-12-22T15:30:01","cid":"23"},{"title":"Jan. 20: Attend a faculty panel discussion on spring courses","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/4xBuQSj_5_I\/facpanel.jsp","description":"Come hear a panel of instructors talk about their spring courses and how they became interested in their area of expertise.","pubDate":"2009-12-22T15:30:01","cid":"23"},{"title":"President Faust receives certificate from food drive coordinator","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/FbW3L9edRrI\/foodfaust.jsp","description":"Management degree candidate Diane Hopson, on behalf of the Commonwealth of Massachusetts House of Representatives, presented President Drew G. Faust with a congratulatory certificate in recognition of her leadership in encouraging public service in the Harvard University community.","pubDate":"2009-12-22T15:30:01","cid":"23"},{"title":"Marshall Scholars have Extension ties","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/IiTc1VWCej8\/kalt.jsp","description":"Anne Kalt, candidate for diploma in premedical studies in the Harvard Extension School Health Careers Program, and Samuel Bjork, a teaching assistant for CHEM E-2a Organic Chemistry this fall, are 2 of 35 new Marshall Scholars nationwide.","pubDate":"2009-12-10T12:00:01","cid":"23"},{"title":"Register late","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/hrlRUrby5K0\/","description":"Register for spring 2010 courses with an additional $50 late fee until Feb. 7.","pubDate":"2009-12-10T12:00:01","cid":"23"},{"title":"In memoriam: Karel Liem","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/b-zOk9Izi4M\/liem.jsp","description":"Biologist Karel F. Liem, PhD, the Henry Bryant Bigelow Professor of Ichthyology at Harvard and long-time Extension School faculty member passed away this summer after a long illness.","pubDate":"2009-10-26T00:00:00","cid":"23"},{"title":"Pfister honored for work with fungi","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/SaPl0v01SmU\/pfister.jsp","description":"The Northeast Mycological Federation has presented the Amicus Tironum Award to Donald Pfister, Asa Gray Professor of Systematic Botany at Harvard, curator of Harvard\u2019s Farlow Library and Herbarium, and Harvard Extension School faculty member.","pubDate":"2009-10-26T00:00:00","cid":"23"},{"title":"Read the new student blogs","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/quYHjJ_fzjY\/","description":"Extension School students are blogging. Read what they have to say about coursework, faculty, and balancing the pursuit of a degree with careers, families, and everything in between.","pubDate":"2009-10-19T00:00:00","cid":"23"},{"title":"Students launch food and clothing drive","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/5TbjieLr5tY\/food.jsp","description":"Collection bins are placed at various convenient locations around campus. Requested donations include: canned, dried, or evaporated milk; dried or canned fruit; oatmeal; whole grain rice; all types of pasta; high fiber cereals such as Cheerios or Raisin Bran.","pubDate":"2009-10-19T00:00:00","cid":"23"},{"title":"Harvard monitoring H1N1 influenza, provides tips to avoid it","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/BP0BqdQqZSw\/h1n1.jsp","description":"Harvard University officials are monitoring the H1N1 influenza (swine flu) and have provided tips for students to help avoid catching or spreading the flu this fall.","pubDate":"2009-10-07T13:45:01","cid":"23"},{"title":"Registration open: US-Pakistan Foreign Relations Conference","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/I-w_NE3JqQE\/foreignrelations.jsp","description":"Through October 10, you can register for the United States-Pakistan Foreign Relations Conference, which features keynote speakers such as Massachusetts Congressman John F. Tierney and Pakistan\u2019s ambassador to the United States, Husain Haqqani, and several well-known panelists.\n ","pubDate":"2009-10-07T13:45:01","cid":"23"},{"title":"Watch the videos of Centennial Academic Convocation","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/iny6dYoSKFs\/convovideo.jsp","description":"Watch the video stream of our Centennial Academic Convocation that was on September 25.\n ","pubDate":"2009-10-07T13:45:01","cid":"23"},{"title":"Check out the free career, academic, and graduate school workshops","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/OxGE9aGHrMI\/","description":"Throughout the year CARC offers more than 60 free academic, graduate school, and career workshops. The sessions include topics like how to improve your reading strategies, how to write a solid graduate application essay, and how to leverage your degree in your current career. ","pubDate":"2009-08-31T00:00:00","cid":"23"},{"title":"Late registration with fee continues through Sept. 13","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/v2z8rgKcfY8\/","description":"You can still register for courses, with a $50 late fee, through September 13. ","pubDate":"2009-08-31T00:00:00","cid":"23"},{"title":"New bioengineering and nanotechnologies offerings keep biotech program current","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/yGfGxkOLliQ\/biotech.jsp","description":"The biotechnology program at the Harvard Extension School continues to find itself at the leading edge of science education, this year offering several new courses and a new master\u2019s concentration in the hot topic area of bioengineering and nanotechnologies. ","pubDate":"2009-08-31T00:00:00","cid":"23"},{"title":"Discounted gym membership available to Extension School students through February 16","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/ybKWdvjxlm0\/gym.jsp","description":"Through February 16, Extension School students can enroll for $29 at Wellbridge Athletic Club and receive $60 off per month on a flexible month-to-month membership. Also included is a $190 training package.","pubDate":"2009-08-29T23:41:49","cid":"23"},{"title":"Gary King named University Professor","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/wnFYP_Y5h7U\/king.jsp","description":"Gary King, the David Florence Professor of Government in the Faculty of Arts and Sciences and Extension School faculty, is one of 2 Harvard faculty members to have recently been named University Professor, Harvard\u2019s highest professorial distinction. ","pubDate":"2009-08-29T23:41:49","cid":"23"},{"title":"Management class project nets record donations for School on Wheels","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/yfH8DdGCx30\/croteau.jsp","description":"The spring 2009 students of MGMT E-4000 collected child backpacks and adult school bags to make a record donation to School on Wheels as part of a class project. ","pubDate":"2009-08-29T23:41:49","cid":"23"},{"title":"Pizzagalli makes strides to understand impact of childhood adversity","link":"http:\/\/feedproxy.google.com\/~r\/harvardextension\/~3\/iIcGTUt2k8I\/pizzagalli.jsp","description":"A new study by Harvard Extension School faculty member Diego Pizzagalli, the John and Ruth Hazel Associate Professor of the Social Sciences in the Department of Psychology at Harvard, and Daniel Dillion, a Harvard postdoctoral researcher, found that people who faced adversity in their childhoods are less likely to respond in the reward-processing regions of their brains. ","pubDate":"2009-08-29T23:41:49","cid":"23"}])
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[]]
PHP
^^^

If you request items in serialized PHP format (e.g.,
http://news.cs50.net/api/1.1/items?cid=23&output=php), the response will
be a serialized array of associative arrays, ordered by date/time, per
the below:

[code,php]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
a:14:{i:0;a:5:{s:5:"title";s:23:"In memoriam: Karel Liem";s:4:"link";s:71:"http://feedproxy.google.com/~r/harvardextension/~3/b-zOk9Izi4M/liem.jsp";s:11:"description";s:182:"Biologist Karel F. Liem, PhD, the Henry Bryant Bigelow Professor of Ichthyology at Harvard and long-time Extension School faculty member passed away this summer after a long illness.";s:7:"pubDate";s:19:"2009-10-26T00:00:00";s:3:"cid";s:2:"23";}i:1;a:5:{s:5:"title";s:35:"Pfister honored for work with fungi";s:4:"link";s:74:"http://feedproxy.google.com/~r/harvardextension/~3/SaPl0v01SmU/pfister.jsp";s:11:"description";s:244:"The Northeast Mycological Federation has presented the Amicus Tironum Award to Donald Pfister, Asa Gray Professor of Systematic Botany at Harvard, curator of Harvards Farlow Library and Herbarium, and Harvard Extension School faculty member.";s:7:"pubDate";s:19:"2009-10-26T00:00:00";s:3:"cid";s:2:"23";}i:2;a:5:{s:5:"title";s:26:"Read the new student blogs";s:4:"link";s:63:"http://feedproxy.google.com/~r/harvardextension/~3/quYHjJ_fzjY/";s:11:"description";s:182:"Extension School students are blogging. Read what they have to say about coursework, faculty, and balancing the pursuit of a degree with careers, families, and everything in between.";s:7:"pubDate";s:19:"2009-10-19T00:00:00";s:3:"cid";s:2:"23";}i:3;a:5:{s:5:"title";s:39:"Students launch food and clothing drive";s:4:"link";s:71:"http://feedproxy.google.com/~r/harvardextension/~3/5TbjieLr5tY/food.jsp";s:11:"description";s:273:"Boston and Cambridge food pantries and homeless and womens shelters will receive much-needed assistance this fall through the charitable efforts of members of the Harvard Extension Service and Leadership Society (a subgroup of the Harvard Extension Student Association).";s:7:"pubDate";s:19:"2009-10-19T00:00:00";s:3:"cid";s:2:"23";}i:4;a:5:{s:5:"title";s:60:"Harvard monitoring H1N1 influenza, provides tips to avoid it";s:4:"link";s:71:"http://feedproxy.google.com/~r/harvardextension/~3/BP0BqdQqZSw/h1n1.jsp";s:11:"description";s:165:"Harvard University officials are monitoring the H1N1 influenza (swine flu) and have provided tips for students to help avoid catching or spreading the flu this fall.";s:7:"pubDate";s:19:"2009-10-07T13:45:01";s:3:"cid";s:2:"23";}i:5;a:5:{s:5:"title";s:59:"Registration open: US-Pakistan Foreign Relations Conference";s:4:"link";s:83:"http://feedproxy.google.com/~r/harvardextension/~3/I-w_NE3JqQE/foreignrelations.jsp";s:11:"description";s:281:"Through October 10, you can register for the United States-Pakistan Foreign Relations Conference, which features keynote speakers such as Massachusetts Congressman John F. Tierney and Pakistans ambassador to the United States, Husain Haqqani, and several well-known panelists.
 ";s:7:"pubDate";s:19:"2009-10-07T13:45:01";s:3:"cid";s:2:"23";}i:6;a:5:{s:5:"title";s:51:"Watch the videos of Centennial Academic Convocation";s:4:"link";s:77:"http://feedproxy.google.com/~r/harvardextension/~3/iny6dYoSKFs/convovideo.jsp";s:11:"description";s:89:"Watch the video stream of our Centennial Academic Convocation that was on September 25.
 ";s:7:"pubDate";s:19:"2009-10-07T13:45:01";s:3:"cid";s:2:"23";}i:7;a:5:{s:5:"title";s:66:"Check out the free career, academic, and graduate school workshops";s:4:"link";s:63:"http://feedproxy.google.com/~r/harvardextension/~3/OxGE9aGHrMI/";s:11:"description";s:277:"Throughout the year CARC offers more than 60 free academic, graduate school, and career workshops. The sessions include topics like how to improve your reading strategies, how to write a solid graduate application essay, and how to leverage your degree in your current career. ";s:7:"pubDate";s:19:"2009-08-31T00:00:00";s:3:"cid";s:2:"23";}i:8;a:5:{s:5:"title";s:53:"Late registration with fee continues through Sept. 13";s:4:"link";s:63:"http://feedproxy.google.com/~r/harvardextension/~3/v2z8rgKcfY8/";s:11:"description";s:79:"You can still register for courses, with a $50 late fee, through September 13. ";s:7:"pubDate";s:19:"2009-08-31T00:00:00";s:3:"cid";s:2:"23";}i:9;a:5:{s:5:"title";s:78:"New bioengineering and nanotechnologies offerings keep biotech program current";s:4:"link";s:74:"http://feedproxy.google.com/~r/harvardextension/~3/yGfGxkOLliQ/biotech.jsp";s:11:"description";s:261:"The biotechnology program at the Harvard Extension School continues to find itself at the leading edge of science education, this year offering several new courses and a new masters concentration in the hot topic area of bioengineering and nanotechnologies. ";s:7:"pubDate";s:19:"2009-08-31T00:00:00";s:3:"cid";s:2:"23";}i:10;a:5:{s:5:"title";s:83:"Discounted gym membership available to Extension School students through October 20";s:4:"link";s:70:"http://feedproxy.google.com/~r/harvardextension/~3/ybKWdvjxlm0/gym.jsp";s:11:"description";s:263:"Until October 20th Extension School students will receive 50 percent off the enrollment fee and $60 dollars off per month at Wellbridge Athletic Club. Students will need to present a valid ID or a copy of their registration in order to receive the special rates. ";s:7:"pubDate";s:19:"2009-08-29T23:41:49";s:3:"cid";s:2:"23";}i:11;a:5:{s:5:"title";s:36:"Gary King named University Professor";s:4:"link";s:71:"http://feedproxy.google.com/~r/harvardextension/~3/wnFYP_Y5h7U/king.jsp";s:11:"description";s:252:"Gary King, the David Florence Professor of Government in the Faculty of Arts and Sciences and Extension School faculty, is one of 2 Harvard faculty members to have recently been named University Professor, Harvards highest professorial distinction. ";s:7:"pubDate";s:19:"2009-08-29T23:41:49";s:3:"cid";s:2:"23";}i:12;a:5:{s:5:"title";s:67:"Management class project nets record donations for School on Wheels";s:4:"link";s:74:"http://feedproxy.google.com/~r/harvardextension/~3/yfH8DdGCx30/croteau.jsp";s:11:"description";s:162:"The spring 2009 students of MGMT E-4000 collected child backpacks and adult school bags to make a record donation to School on Wheels as part of a class project. ";s:7:"pubDate";s:19:"2009-08-29T23:41:49";s:3:"cid";s:2:"23";}i:13;a:5:{s:5:"title";s:68:"Pizzagalli makes strides to understand impact of childhood adversity";s:4:"link";s:77:"http://feedproxy.google.com/~r/harvardextension/~3/iIcGTUt2k8I/pizzagalli.jsp";s:11:"description";s:374:"A new study by Harvard Extension School faculty member Diego Pizzagalli, the John and Ruth Hazel Associate Professor of the Social Sciences in the Department of Psychology at Harvard, and Daniel Dillion, a Harvard postdoctoral researcher, found that people who faced adversity in their childhoods are less likely to respond in the reward-processing regions of their brains. ";s:7:"pubDate";s:19:"2009-08-29T23:41:49";s:3:"cid";s:2:"23";}}
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Once you http://php.net/manual/en/function.unserialize.php[unserialize]
that response, you'll have the below in memory:

[code,php]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Array
(
    [0] => Array
        (
            [title] => In memoriam: Karel Liem
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/b-zOk9Izi4M/liem.jsp
            [description] => Biologist Karel F. Liem, PhD, the Henry Bryant Bigelow Professor of Ichthyology at Harvard and long-time Extension School faculty member passed away this summer after a long illness.
            [pubDate] => 2009-10-26T00:00:00
            [cid] => 23
        )

    [1] => Array
        (
            [title] => Pfister honored for work with fungi
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/SaPl0v01SmU/pfister.jsp
            [description] => The Northeast Mycological Federation has presented the Amicus Tironum Award to Donald Pfister, Asa Gray Professor of Systematic Botany at Harvard, curator of Harvards Farlow Library and Herbarium, and Harvard Extension School faculty member.
            [pubDate] => 2009-10-26T00:00:00
            [cid] => 23
        )

    [2] => Array
        (
            [title] => Read the new student blogs
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/quYHjJ_fzjY/
            [description] => Extension School students are blogging. Read what they have to say about coursework, faculty, and balancing the pursuit of a degree with careers, families, and everything in between.
            [pubDate] => 2009-10-19T00:00:00
            [cid] => 23
        )

    [3] => Array
        (
            [title] => Students launch food and clothing drive
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/5TbjieLr5tY/food.jsp
            [description] => Boston and Cambridge food pantries and homeless and womens shelters will receive much-needed assistance this fall through the charitable efforts of members of the Harvard Extension Service and Leadership Society (a subgroup of the Harvard Extension Student Association).
            [pubDate] => 2009-10-19T00:00:00
            [cid] => 23
        )

    [4] => Array
        (
            [title] => Harvard monitoring H1N1 influenza, provides tips to avoid it
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/BP0BqdQqZSw/h1n1.jsp
            [description] => Harvard University officials are monitoring the H1N1 influenza (swine flu) and have provided tips for students to help avoid catching or spreading the flu this fall.
            [pubDate] => 2009-10-07T13:45:01
            [cid] => 23
        )

    [5] => Array
        (
            [title] => Registration open: US-Pakistan Foreign Relations Conference
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/I-w_NE3JqQE/foreignrelations.jsp
            [description] => Through October 10, you can register for the United States-Pakistan Foreign Relations Conference, which features keynote speakers such as Massachusetts Congressman John F. Tierney and Pakistans ambassador to the United States, Husain Haqqani, and several well-known panelists.
 
            [pubDate] => 2009-10-07T13:45:01
            [cid] => 23
        )

    [6] => Array
        (
            [title] => Watch the videos of Centennial Academic Convocation
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/iny6dYoSKFs/convovideo.jsp
            [description] => Watch the video stream of our Centennial Academic Convocation that was on September 25.
 
            [pubDate] => 2009-10-07T13:45:01
            [cid] => 23
        )

    [7] => Array
        (
            [title] => Check out the free career, academic, and graduate school workshops
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/OxGE9aGHrMI/
            [description] => Throughout the year CARC offers more than 60 free academic, graduate school, and career workshops. The sessions include topics like how to improve your reading strategies, how to write a solid graduate application essay, and how to leverage your degree in your current career. 
            [pubDate] => 2009-08-31T00:00:00
            [cid] => 23
        )

    [8] => Array
        (
            [title] => Late registration with fee continues through Sept. 13
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/v2z8rgKcfY8/
            [description] => You can still register for courses, with a $50 late fee, through September 13. 
            [pubDate] => 2009-08-31T00:00:00
            [cid] => 23
        )

    [9] => Array
        (
            [title] => New bioengineering and nanotechnologies offerings keep biotech program current
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/yGfGxkOLliQ/biotech.jsp
            [description] => The biotechnology program at the Harvard Extension School continues to find itself at the leading edge of science education, this year offering several new courses and a new masters concentration in the hot topic area of bioengineering and nanotechnologies. 
            [pubDate] => 2009-08-31T00:00:00
            [cid] => 23
        )

    [10] => Array
        (
            [title] => Discounted gym membership available to Extension School students through October 20
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/ybKWdvjxlm0/gym.jsp
            [description] => Until October 20th Extension School students will receive 50 percent off the enrollment fee and $60 dollars off per month at Wellbridge Athletic Club. Students will need to present a valid ID or a copy of their registration in order to receive the special rates. 
            [pubDate] => 2009-08-29T23:41:49
            [cid] => 23
        )

    [11] => Array
        (
            [title] => Gary King named University Professor
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/wnFYP_Y5h7U/king.jsp
            [description] => Gary King, the David Florence Professor of Government in the Faculty of Arts and Sciences and Extension School faculty, is one of 2 Harvard faculty members to have recently been named University Professor, Harvards highest professorial distinction. 
            [pubDate] => 2009-08-29T23:41:49
            [cid] => 23
        )

    [12] => Array
        (
            [title] => Management class project nets record donations for School on Wheels
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/yfH8DdGCx30/croteau.jsp
            [description] => The spring 2009 students of MGMT E-4000 collected child backpacks and adult school bags to make a record donation to School on Wheels as part of a class project. 
            [pubDate] => 2009-08-29T23:41:49
            [cid] => 23
        )

    [13] => Array
        (
            [title] => Pizzagalli makes strides to understand impact of childhood adversity
            [link] => http://feedproxy.google.com/~r/harvardextension/~3/iIcGTUt2k8I/pizzagalli.jsp
            [description] => A new study by Harvard Extension School faculty member Diego Pizzagalli, the John and Ruth Hazel Associate Professor of the Social Sciences in the Department of Psychology at Harvard, and Daniel Dillion, a Harvard postdoctoral researcher, found that people who faced adversity in their childhoods are less likely to respond in the reward-processing regions of their brains. 
            [pubDate] => 2009-08-29T23:41:49
            [cid] => 23
        )

)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[]]
RSS
^^^

If you request data in RSS format (e.g.,
http://news.cs50.net/api/1.1/items?cid=23&output=rss), the response will
be an RSS feed, per the below:

[code,xml]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>
<rss version='2.0'>
  <channel>
    <title>HarvardNews</title>
    <description>Property of CS50</description>
    <link>http://news.cs50.net/</link>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/b-zOk9Izi4M/liem.jsp</guid>
      <title>In memoriam: Karel Liem</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/b-zOk9Izi4M/liem.jsp</link>
      <description>Biologist Karel F. Liem, PhD, the Henry Bryant Bigelow Professor of Ichthyology at Harvard and long-time Extension School faculty member passed away this summer after a long illness.</description>
      <category></category>
      <pubDate>Mon, 26 Oct 2009 00:00:00 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/SaPl0v01SmU/pfister.jsp</guid>
      <title>Pfister honored for work with fungi</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/SaPl0v01SmU/pfister.jsp</link>
      <description>The Northeast Mycological Federation has presented the Amicus Tironum Award to Donald Pfister, Asa Gray Professor of Systematic Botany at Harvard, curator of Harvard&#226;&#8364;&#8482;s Farlow Library and Herbarium, and Harvard Extension School faculty member.</description>
      <category></category>
      <pubDate>Mon, 26 Oct 2009 00:00:00 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/quYHjJ_fzjY/</guid>
      <title>Read the new student blogs</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/quYHjJ_fzjY/</link>
      <description>Extension School students are blogging. Read what they have to say about coursework, faculty, and balancing the pursuit of a degree with careers, families, and everything in between.</description>
      <category></category>
      <pubDate>Mon, 19 Oct 2009 00:00:00 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/5TbjieLr5tY/food.jsp</guid>
      <title>Students launch food and clothing drive</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/5TbjieLr5tY/food.jsp</link>
      <description>Boston and Cambridge food pantries and homeless and women&#226;&#8364;&#8482;s shelters will receive much-needed assistance this fall through the charitable efforts of members of the Harvard Extension Service and Leadership Society (a subgroup of the Harvard Extension Student Association).</description>
      <category></category>
      <pubDate>Mon, 19 Oct 2009 00:00:00 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/BP0BqdQqZSw/h1n1.jsp</guid>
      <title>Harvard monitoring H1N1 influenza, provides tips to avoid it</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/BP0BqdQqZSw/h1n1.jsp</link>
      <description>Harvard University officials are monitoring the H1N1 influenza (swine flu) and have provided tips for students to help avoid catching or spreading the flu this fall.</description>
      <category></category>
      <pubDate>Wed, 07 Oct 2009 13:45:01 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/I-w_NE3JqQE/foreignrelations.jsp</guid>
      <title>Registration open: US-Pakistan Foreign Relations Conference</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/I-w_NE3JqQE/foreignrelations.jsp</link>
      <description>Through October 10, you can register for the United States-Pakistan Foreign Relations Conference, which features keynote speakers such as Massachusetts Congressman John F. Tierney and Pakistan&#226;&#8364;&#8482;s ambassador to the United States, Husain Haqqani, and several well-known panelists.</description>
      <category></category>
      <pubDate>Wed, 07 Oct 2009 13:45:01 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/iny6dYoSKFs/convovideo.jsp</guid>
      <title>Watch the videos of Centennial Academic Convocation</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/iny6dYoSKFs/convovideo.jsp</link>
      <description>Watch the video stream of our Centennial Academic Convocation that was on September 25.</description>
      <category></category>
      <pubDate>Wed, 07 Oct 2009 13:45:01 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/OxGE9aGHrMI/</guid>
      <title>Check out the free career, academic, and graduate school workshops</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/OxGE9aGHrMI/</link>
      <description>Throughout the year CARC offers more than 60 free academic, graduate school, and career workshops. The sessions include topics like how to improve your reading strategies, how to write a solid graduate application essay, and how to leverage your degree in your current career.</description>
      <category></category>
      <pubDate>Mon, 31 Aug 2009 00:00:00 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/v2z8rgKcfY8/</guid>
      <title>Late registration with fee continues through Sept. 13</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/v2z8rgKcfY8/</link>
      <description>You can still register for courses, with a $50 late fee, through September 13.</description>
      <category></category>
      <pubDate>Mon, 31 Aug 2009 00:00:00 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/yGfGxkOLliQ/biotech.jsp</guid>
      <title>New bioengineering and nanotechnologies offerings keep biotech program current</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/yGfGxkOLliQ/biotech.jsp</link>
      <description>The biotechnology program at the Harvard Extension School continues to find itself at the leading edge of science education, this year offering several new courses and a new master&#226;&#8364;&#8482;s concentration in the hot topic area of bioengineering and nanotechnologies.</description>
      <category></category>
      <pubDate>Mon, 31 Aug 2009 00:00:00 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/ybKWdvjxlm0/gym.jsp</guid>
      <title>Discounted gym membership available to Extension School students through October 20</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/ybKWdvjxlm0/gym.jsp</link>
      <description>Until October 20th Extension School students will receive 50 percent off the enrollment fee and $60 dollars off per month at Wellbridge Athletic Club. Students will need to present a valid ID or a copy of their registration in order to receive the special rates.</description>
      <category></category>
      <pubDate>Sat, 29 Aug 2009 23:41:49 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/wnFYP_Y5h7U/king.jsp</guid>
      <title>Gary King named University Professor</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/wnFYP_Y5h7U/king.jsp</link>
      <description>Gary King, the David Florence Professor of Government in the Faculty of Arts and Sciences and Extension School faculty, is one of 2 Harvard faculty members to have recently been named University Professor, Harvard&#226;&#8364;&#8482;s highest professorial distinction.</description>
      <category></category>
      <pubDate>Sat, 29 Aug 2009 23:41:49 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/yfH8DdGCx30/croteau.jsp</guid>
      <title>Management class project nets record donations for School on Wheels</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/yfH8DdGCx30/croteau.jsp</link>
      <description>The spring 2009 students of MGMT E-4000 collected child backpacks and adult school bags to make a record donation to School on Wheels as part of a class project.</description>
      <category></category>
      <pubDate>Sat, 29 Aug 2009 23:41:49 -0400</pubDate>
    </item>
    <item>
      <guid isPermaLink='false'>http://feedproxy.google.com/~r/harvardextension/~3/iIcGTUt2k8I/pizzagalli.jsp</guid>
      <title>Pizzagalli makes strides to understand impact of childhood adversity</title>
      <link>http://feedproxy.google.com/~r/harvardextension/~3/iIcGTUt2k8I/pizzagalli.jsp</link>
      <description>A new study by Harvard Extension School faculty member Diego Pizzagalli, the John and Ruth Hazel Associate Professor of the Social Sciences in the Department of Psychology at Harvard, and Daniel Dillion, a Harvard postdoctoral researcher, found that people who faced adversity in their childhoods are less likely to respond in the reward-processing regions of their brains.</description>
      <category></category>
      <pubDate>Sat, 29 Aug 2009 23:41:49 -0400</pubDate>
    </item>
  </channel>
</rss>
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[]]
Examples
--------

* Returns all channels:
** http://news.cs50.net/api/1.1/channels?output=csv
** http://news.cs50.net/api/1.1/channels?output=json
**
http://news.cs50.net/api/1.1/channels?output=jsonp&callback=parseResponse
** http://news.cs50.net/api/1.1/channels?output=php
* Returns most recent items:
** http://news.cs50.net/apis/1.1/items?output=csv
** http://news.cs50.net/apis/1.1/items?output=json
**
http://news.cs50.net/apis/1.1/items?output=jsonp&callback=parseResponse
** http://news.cs50.net/apis/1.1/items?output=php
** http://news.cs50.net/apis/1.1/items?output=rss
* Returns items published on 11 November 2009:
**
http://news.cs50.net/api/1.1/items?sdt=2009-11-11&edt=2009-11-11&output=csv
**
http://news.cs50.net/api/1.1/items?sdt=2009-11-11&edt=2009-11-11&output=json
**
http://news.cs50.net/api/1.1/items?sdt=2009-11-11&edt=2009-11-11&output=jsonp&callback=parseResponse
**
http://news.cs50.net/api/1.1/items?sdt=2009-11-11&edt=2009-11-11&output=php
**
http://news.cs50.net/api/1.1/items?sdt=2009-11-11&edt=2009-11-11&output=rss
* Returns items published between noon on 11 November 2009 and noon on
12 November 2009, inclusive:
**
http://news.cs50.net/api/1.1/items?sdt=2009-11-11T12:00:00&edt=2009-11-12T12:00:00&output=csv
**
http://news.cs50.net/api/1.1/items?sdt=2009-11-11T12:00:00&edt=2009-11-12T12:00:00&output=json
**
http://news.cs50.net/api/1.1/items?sdt=2009-11-11T12:00:00&edt=2009-11-12T12:00:00&output=jsonp&callback=parseResponse
**
http://news.cs50.net/api/1.1/items?sdt=2009-11-11T12:00:00&edt=2009-11-12T12:00:00&output=php
**
http://news.cs50.net/api/1.1/items?sdt=2009-11-11T12:00:00&edt=2009-11-12T12:00:00&output=rss
* Returns most recent items published by the Harvard Crimson:
** http://news.cs50.net/api/1.1/items?cid=1,2,3,4,5&output=csv
** http://news.cs50.net/api/1.1/items?cid=1,2,3,4,5&output=json
**
http://news.cs50.net/api/1.1/items?cid=1,2,3,4,5&output=jsonp&callback=parseResponse
** http://news.cs50.net/api/1.1/items?cid=1,2,3,4,5&output=php
** http://news.cs50.net/api/1.1/items?cid=1,2,3,4,5&output=rss
* Returns items about CS50:
** http://news.cs50.net/api/1.1/items?q=cs50&output=csv
** http://news.cs50.net/api/1.1/items?q=cs50&output=json
**
http://news.cs50.net/api/1.1/items?q=cs50&output=jsonp&callback=parseResponse
** http://news.cs50.net/api/1.1/items?q=cs50&output=php
** http://news.cs50.net/api/1.1/items?q=cs50&output=rss

[[]]
See Also
--------

* link:Neat_Tricks#Parsing_CSV[Parsing CSV]
* link:Neat_Tricks#Parsing_Dates.2FTimes[Parsing Dates/Times]
* link:Neat_Tricks#Parsing_JSON[Parsing JSON]
* link:Neat_Tricks#Parsing_RSS[Parsing RSS]
* link:Neat_Tricks#Unserializing_PHP[Unserializing PHP]

[[]]
Related APIs
------------

* link:HarvardCourses API[HarvardCourses API]
* link:HarvardEnergy API[HarvardEnergy API]
* link:HarvardEvents API[HarvardEvents API]
* link:HarvardFood API[HarvardFood API]
* link:HarvardMaps API[HarvardMaps API]
* link:HarvardTweets API[HarvardTweets API]
* link:Shuttleboy API[Shuttleboy API]

[[]]
External Links
--------------

* http://en.wikipedia.org/wiki/Comma-separated_values[Comma-separated
values]
* http://en.wikipedia.org/wiki/JSON[JSON]
* http://en.wikipedia.org/wiki/JSON#JSONP[JSONP]
* http://php.net/manual/en/function.serialize.php[PHP: serialize]
* http://php.net/manual/en/function.unserialize.php[PHP: unserialize]
* http://en.wikipedia.org/wiki/RSS[RSS]

[[]]
Changelog
---------

* http://wiki.cs50.net.php?title=HarvardNews_API&oldid=1008[1.0]
* 1.1
** Added support for JSONP.

Category:API
