---
tags: []
title: render50
---

`render50` is a command-line tool that we use in http://cs50.tv/[CS50]
to render a students' source code as PDFs on which the teaching fellows
(TFs) can provide feedback (as with
http://www.adobe.com/products/acrobat.html[Adobe Acrobat],
http://www.bluebeam.com/web07/us/products/revu/standard/[Bluebeam PDF
Revu], or
http://www.tracker-software.com/product/pdf-xchange-lite[PDF-XChange
Lite]). For example, were you to render the
http://cdn.cs50.net/2010/fall/psets/3/pset3.zip[distribution code] from
http://cdn.cs50.net/2010/fall/[Fall 2010]'s
http://cdn.cs50.net/2010/fall/psets/3/pset3.pdf[Problem Set 3], you'd
get link:Render50.pdf[a PDF like this].

The tool's features include:

* Source code is syntax-highlighted.
* PDFs are in landscape mode so that there's more room for TFs'
comments.
* Source files' names appear atop each page.
* Each source file is bookmarked within the PDF so that TFs can quickly
seek from file to file.
* Directories are searched recursively for source files.
* Source files can be included or excluded via their names or even
patterns (e.g., `*.c`).


Author
------

mailto:malan@harvard.edu[David J. Malan '99] +
http://www.cs.harvard.edu/malan/

Thanks to Glenn Holloway and Keito Uchiyama '11 for this tool's
predecessors.


License
-------

This software is governed by a
http://www.gnu.org/licenses/gpl-2.0.html[GNU General Public License,
version 2], which means that you may modify or redistribute it so long
as you yourself adhere to that same license's terms.

http://qbnz.com/highlighter/license.php[GeSHi] and
http://mpdf.bpm1.com/licence[mPDF], which `render50` includes, are also
governed by that same license.


Installation
------------


Linux
~~~~~

No matter your OS, perform the steps as root (as via `sudo`).


CentOS, RedHat
^^^^^^^^^^^^^^

[source,bash]
--------------------------------------------------------------
wget http://mirror.cs50.net/render50/render50-1.5-1.noarch.rpm
rpm -ivh render50-1.5-1.noarch.rpm
rm -f render50-1.5-1.noarch.rpm
--------------------------------------------------------------


Debian, Ubuntu
^^^^^^^^^^^^^^

[source,bash]
-----------------------------------------------------
apt-get install php5 php5-mbstring
wget http://mirror.cs50.net/render50/render50-1.5.zip
unzip render50-1.5.zip
rm -f render50-1.5.zip
-----------------------------------------------------

Then move `render50-1.5` wherever you'd like.


Fedora
^^^^^^

[source,bash]
---------------------------------------------------------------------
yum install http://mirror.cs50.net/render50/render50-1.5-1.noarch.rpm
---------------------------------------------------------------------


Mac OS
~~~~~~

1.  Install http://www.php.net/manual/en/install.php[PHP 5.0.0] or
higher, if not already installed.
2.  Download http://mirror.cs50.net/render50/render50-1.5.zip, unzip it,
and move `render50-1.5` wherever you'd like.


Windows
~~~~~~~

1.  Install http://www.php.net/manual/en/install.php[PHP 5.0.0] or
higher, if not already installed.
2.  Download http://mirror.cs50.net/render50/render50-1.5.zip, unzip it,
and move `render50-1.5` wherever you'd like.


Usage
-----

If you execute `render50` without any command-line arguments, you'll see
that its usage is defined as

`render50 output [inputs] [-i includes] [-x excludes]`

where

* `output` is the name of the PDF to be outputted; if `output` itself
does not end in `.pdf`, the extension will be automatically appended
* `inputs` is a space-separated list of files and/or directories to be
rendered (unless implicitly excluded by `-i` or implicitly excluded by
`-x`); if `inputs` is just `--`, the list of files and/or directories
will be read from standard input, one per line
* `-i includes` is a space-separated list of paths (that may include
wildcards, `*`) to be included in rendering to the exclusion of files
otherwise implied by `inputs`, as in
+
--------------------------------------
render50 output.pdf directory -i *.php
--------------------------------------
* `-x excludes` is a space-separated list of paths (that may include
wildcards, `*`) to be excluded from rendering, even if otherwise implied
by `inputs`, as in
+
-------------------------------------------
render50 output.pdf directory -x *.css *.js
-------------------------------------------

Depending on your operating system, you may be able to execute
`render50` in different ways. Note that `render50.bat`, `render50.php`,
and `render50.php` all live in `render50-1.4/bin`.


Linux
~~~~~


CentOS, RedHat
^^^^^^^^^^^^^^

Assuming you installed `render50` via `rpm`, open a terminal window and
then execute:

`render50`

Otherwise, assuming `php` is in your `PATH`, open a terminal window and
then execute:

`php /path/to/render50-1.4/bin/render50.php`


Debian, Ubuntu
^^^^^^^^^^^^^^

Assuming `php` is in your `PATH`, open a terminal window and then
execute:

`php /path/to/render50-1.4/bin/render50.php`


Fedora
^^^^^^

Assuming you installed `render50` via `yum`, open a terminal window and
then execute:

`render50`

Otherwise, assuming `php` is in your `PATH`, open a terminal window and
then execute:

`php /path/to/render50-1.4/bin/render50.php`


Mac OS
^^^^^^

Assuming `php` is in your `PATH`, open a terminal window and then
execute

`php /path/to/render50-1.4/bin/render50.php`

or just

`/path/to/render50-1.4/bin/render50.sh`


Windows
^^^^^^^

On Windows, open a command prompt (as by running `cmd`), and then
execute:

`/path/to/php.exe /path/to/render50-1.4/bin/render50.php`

If `php.exe` is in your `%PATH%`, you can instead run

`php /path/to/render50-1.4/bin/render50.php`

or just

`php /path/to/render50-1.4/bin/render50.bat`


Supported Languages
-------------------

`render50` supports every language that
http://qbnz.com/highlighter/[GeSHi] itself supports, including, but not
limited to:

* C
* CSS
* C#
* C++
* HTML
* Java
* JavaScript
* Objective-C
* Perl
* PHP
* Python
* Ruby
* SQL
* XML
* http://qbnz.com/highlighter/[more...]


Examples
--------

These examples assume that `render50` has been installed in such a way
that it suffices to execute `render50` via its name alone (as will be
the case if installed for link:#_linux[Linux] via `yum`), per the tool's
link:#_usage[usage]. Be sure to quote any patterns that contain wildcards
(`*`) if you want to prevent your shell from
http://en.wikipedia.org/wiki/Glob_(programming)[globbing] them.

* Render all files in `directory`
** `render50 output.pdf directory/`

* Render all files in `directory` but exclude all files in
`subdirectory`
** `render50 output.pdf directory/ -x directory/subdirectory/`

* Render all files in `directory` except for `foo.c` and `foo.h`
** `render50 output.pdf directory -x foo.{c,h}`

* Render all C files in `directory`
** `render50 output.pdf directory/*.c`

* Render all C files in and below `directory`
** `render50 output.pdf directory/ -i "*.c"`

* Render all Objective-C files in and below `directory`
** `render50 output.pdf directory/ -i "*.h" "*.m"`

* Render all files in and below `directory` but exclude anything called
`main.m` or `*.pch`
** `render50 output.pdf directory/ -x "*/main.m" "*/*.pch"`

* Render all CSS, HTML, and JavaScript files in `directory`
** `render50 output.pdf directory/ -i "*.css" "*.html" "*.js"`


Implementation Details
----------------------

`render50` uses http://qbnz.com/highlighter/[GeSHi] to transform source
code into syntax-highlighted HTML and http://mpdf.bpm1.com/[mPDF] to
transform that HTML into a PDF. To minimize mPDF's memory usage, we
followed
http://www.mpdf1.com/mpdf/forum/comments.php?DiscussionID=579&page=1[these
directions] and then
http://mpdf1.com/manual.php?tid=406&searchstring=compress.php[these
directions], enabling only these options:

* `LISTS`
* `HTMLHEADERS-FOOTERS`
* `BOOKMARKS`

The resulting, "compressed" file is included with `render50` as
`render50-1.4/lib/mpdf/mpdf.php`; the original file (after deletions,
per
http://www.mpdf1.com/mpdf/forum/comments.php?DiscussionID=579&page=1[these
directions]) is also included as
`render50-1.4/lib/mpdf/mpdf_source.php`.

It's worth noting that "compressing" `mpdf.php` in this manner reduced
`render50`'s memory usage on Windows (under PHP 5.3.5) by an order of
magnitude (e.g., from over 500MB to just over 10MB when rendering the
http://cdn.cs50.net/2010/fall/psets/3/pset3.zip[distribution code] from
http://cdn.cs50.net/2010/fall/[Fall 2010]'s
http://cdn.cs50.net/2010/fall/psets/3/pset3.pdf[Problem Set 3]), the
result, presumably, of a memory leak in mPDF or a bug in `php.exe`
itself. The gains on Linux and Mac OS were far less significant.


How to Annotate PDFs
--------------------

CS50's TFs use the tools below to annotate PDFs.


Linux
~~~~~

* http://www.tracker-software.com/product/pdf-xchange-lite[PDF-XChange].
*Free*. Download the _Non Commercial Release_. Install it under
http://www.winehq.org/[WINE].


Mac OS
~~~~~~

* http://www.adobe.com/products/acrobat.html[Adobe Acrobat].
*Commercial*.
* http://en.wikipedia.org/wiki/Preview_(software)[Preview]. *Free*.
Comes with Mac OS.


Windows
~~~~~~~

* http://www.adobe.com/products/acrobat.html[Adobe Acrobat].
*Commercial*.
* http://www.bluebeam.com/web07/us/products/revu/standard/[Bluebeam PDF
Revu]. *Commercial*.
* http://www.tracker-software.com/product/pdf-xchange-lite[PDF-XChange].
*Free*. Download the _Non Commercial Release_.


Support
-------

To ask questions or report bugs, even if you're not a student at
Harvard, join
http://groups.google.com/group/cs50-discuss/topics[cs50-discuss], the
course's Google Group!


Changelog
---------

* https://wiki.cs50.net.php?title=render50&oldid=4021[1.0]
* 1.1
** Fixed bug whereby warnings were generated when using PHP < 5.2.0.
Fixed (related) bug whereby *.txt wasn't whitelisted.
** Upgraded mPDF from 5.0 to 5.1.
** Renamed directories in lib/ to include libraries' version numbers.
** Changed all non-0 exit codes to 1.
** User is now prompted whether to create output directory if it doesn't
exist.
** Binary files are now skipped (with high probability) by ignoring
input files with 0x00 (which is non-printable).
** PHP 5.0.0 or higher is now required.
* 1.2
** Changed `lib/` to `share/`.
* 1.3
** Changed usage instructions from `php /path/to/render50.php` to just
`render50`.
** Added support for `rpm` and `yum`.
* 1.4
** Updated exit codes.
* 1.5
** Files and directories specified explicitly at the command line are
now rendered in the order in which they appear.
** Fixed bug whereby those directories' descendants weren't naturally
sorted case-insensitively.


Future Work
-----------

* Add man page.
* Ensure scripts with shebangs can be rendered.
* Reduce memory usage.

Category:Software
