---
tags: [HOWTO]
title: VMware Player
---

Here's how to install the link:..[CS50 Appliance] using
VMware Player for link:#_installation[Windows].


== Installation

1.  Download VMware Player for free from
http://www.vmware.com/go/downloadplayer/.
2.  Double-click the file you just downloaded (which is likely in your
*Downloads* folder) in order launch VMware Player's installer.
3.  If a window entitled *User Account Control* appears, click *Yes*.
4.  A window entitled *VMware Player Setup* should appear. Click *Next*.
5.  When prompted to select a *Destination Folder*, click *Next*.
6.  When prompted about *Shortcuts*, click *Next*. (Uncheck *Desktop*
and/or *Start Menu Programs folder* if you'd like.)
7.  When prompted to *Perform the Requested Operations*, click
*Continue*.
8.  Once you see *Setup Wizard Complete*, click *Restart Now* if
prompted, else *Continue*.
4.  Download the Appliance's OVA file of CS50 Appliance at
http://mirror.cs50.net/appliance50/19/i386/appliance50-19-vmware.ova
(http://mirror.cs50.net/appliance50/19/i386/appliance50-19-vmware.ova?torrent[torrent]).
That OVA file is over 1GB in size, so it might take a while to download.
5. Drag that cs50-appliance-19 file somewhere safe, where you won't accidentally delete it. Do not leave it in your Downloads folder.
6.  Launch VMware Player, as by double-clicking its icon, which should
be in your *Applications* folder. If prompted with a *Software License
Agreement*, click *Agree*. If prompted for *Licensing*, paste in your
license key, then click *OK*. If prompted to *Create New*, *Convert VM*,
or *Migrate PC*, simply click *Skip*. If you do not yet have a license key, begin the
trial. You may need to input an email address to proceed.
7.  Ensure that you have version 5.0.1 or later of VMware Fusion, as by
selecting *VMware Player > Check for Updates...*. Update and relaunch
VMware Player as needed.
8.  Select *File > Import...*. Navigate your way to that *appliance50-19-vmware.ova*
file (wherever you moved it for safe-keeping), highlight the
*appliance50-17.vmx* file within, and click *Open*.
9. Click VMware Player's ▶ button to start up the appliance. If
prompted to "upgrade this virtual machine," click *Upgrade*.

The appliance should then boot! If you see a black-and-white screen
entitled *GNU GRUB*, no need to do anything; the appliance will continue
to boot after a few seconds!

== Troubleshooting


=== Binary translation is incompatible with long mode on this platform

If you see this message, you might need to enable
link:../../Hardware_Virtualization[hardware virtualization] on your computer.
