== 1Password

CS50 has a "site license" for https://agilebits.com/onepassword[1Password], which means that CS50 students and staff may use 1Password for free, even after the course ends. To request a license for 1Password, submit https://cs50.harvard.edu/1password[this form].

== DreamSpark

Microsoft has donated a https://www.dreamspark.com/[DreamSpark]
membership to Harvard. All Harvard undergraduates are eligible, as are
other students currently enrolled in CS50. *Unfortunately, CS50x
students are not eligible.* DreamSpark entitles you to most of
Microsoft's development software free of charge. The available titles
include Windows 8.1, Visual Studio, OneNote, Visio, and many other
applications. The program does *not* offer the core applications of the
Office suite (Word, Excel, PowerPoint, or Outlook).

To sign up for DreamSpark, simply send a nice note from your Harvard
email address to sysadmins@cs50.harvard.edu explaining your eligibility.

== iOS University Program

See link:../iOS_University_Program[iOS University Program].

