---
tags: []
title: VMware Fusion
---

Here's how to install the link:..[CS50 Appliance] using
VMware Fusion for link:#_installation[Mac OS].


== Installation

////
1.  Download VMware Fusion as follows:
* If you're a student or course staff member at Harvard,
https://docs.google.com/spreadsheet/viewform?hl=en_US&formkey=dHoyMG5LNTgxeGFhakNaaE9CdTlkbWc6MQ[apply
for the VMware Academic Program] (VMAP) in order to obtain a username
and password with which you can download VMware Fusion for free from
http://vmap.cs50.net/, along with a serial number.
* If you're not a student at Harvard, you can download a 30-day trial of
VMware Fusion from http://www.vmware.com/products/fusion/overview.html.
After 30 days, you'll need to
http://www.vmware.com/a/buylink/10[purchase a license] for $49.99.
////
1. Download VMware Fusion as follows:
* Download the 30-day trial of VMware Fusion 6 at http://www.vmware.com/go/tryfusion. (If a Harvard student, we'll provide you with a longer-lasting license within 30 days.)  
2.  Double-click the file you just downloaded (which is likely in your
*Downloads* folder) in order to "mount" VMware Fusion's icon on your
desktop.
3.  A window should open. Drag the *VMware Fusion* (or *VMware
Fusion.app*) icon in that window to your *Applications* folder.
4.  Download the Appliance's OVA file at
http://mirror.cs50.net/appliance50/19/i386/appliance50-19-vmware.ova
(http://mirror.cs50.net/appliance50/19/i386/appliance50-19-vmware.ova?torrent[torrent]).
That OVA file is over 1GB in size, so it might take a while to download.
5. Drag that *appliance50-19-vmware.ova file somewhere safe, where you won't accidentally delete it. Do not leave it in your *Downloads* folder.
6.  Launch VMware Fusion, as by double-clicking its icon, which should
be in your *Applications* folder. If prompted with a *Software License
Agreement*, click *Agree*. If prompted for *Licensing*, paste in your
license key, then click *OK*. If prompted to *Create New*, *Convert VM*,
or *Migrate PC*, simply click *Skip*. If you do not yet have a license key, begin the
trial. You may need to input an email address to proceed.
7.  Ensure that you have version 6 or later of VMware Fusion, as by
selecting *VMware Fusion > Check for Updates...*. Update and relaunch
VMware Fusion as needed.
8.  Select *File > Import...*. Navigate your way to that *appliance50-19-vmware.ova*
file (wherever you moved it for safe-keeping) and select it.
9. Click VMware Fusion's ▶ button to start up the appliance. If
prompted to "upgrade this virtual machine," click *Upgrade*.

The appliance should then boot! If you see a black-and-white screen
entitled *GNU GRUB*, no need to do anything; the appliance will continue
to boot after a few seconds!
