= VMware Player
:toc: left

Here's how to install the link:..[CS50 Appliance] using VMware Player for link:#installation[Windows].

== Installation

. Download VMware Player for Windows (or for Linux, but only if your own computer is running Linux) for free from
http://www.vmware.com/go/downloadplayer/. 
. Double-click the file you just downloaded (which is likely in your
*Downloads* folder) in order launch VMware Player's installer.
. If a window entitled *User Account Control* appears, click *Yes*.
. A window entitled *VMware Player Setup* should appear. Click *Next*.
. When prompted to select a *Destination Folder*, click *Next*.
. When prompted about *Shortcuts*, click *Next*. (Uncheck *Desktop*
and/or *Start Menu Programs folder* if you'd like.)
. When prompted to *Perform the Requested Operations*, click
*Continue*.
. Once you see *Setup Wizard Complete*, click *Restart Now* if
prompted, else *Continue*.
. Download the CS50 Appliance itself at
http://mirror.cs50.net/appliance50/19/i386/appliance50-19-vmware.ova
(http://mirror.cs50.net/appliance50/19/i386/appliance50-19-vmware.ova.torrent[torrent]).
That file is over 1GB in size, so it might take a while to download.
. Launch VMware Player, as by double-clicking its icon, which should
be in your *Applications* folder. If prompted with a *Software License
Agreement*, click *Agree*. If prompted for *Licensing*, paste in your
license key, then click *OK*. If prompted to *Create New*, *Convert VM*,
or *Migrate PC*, simply click *Skip*. If you do not yet have a license key, begin the
trial. You may need to input an email address to proceed.
. Select *File > Open...*. Navigate your way to that *appliance50-19-vmware.ova* and click *Open*.
. Click VMware Player's &#9654; button to start up the appliance. If
prompted to "upgrade this virtual machine," click *Upgrade*.

The appliance should then boot! If you see a black-and-white screen
entitled *GNU GRUB*, no need to do anything; the appliance will continue
to boot after a few seconds!

== Troubleshooting

=== Binary translation is incompatible with long mode on this platform

If you see this message, you might need to enable
link:/virtualization/[hardware virtualization] on your computer.
