---
tags: []
title: CS50 Hackathon
---

The CS50 Hackathon is an epic all-nighter at
http://microsoftcambridge.com/[Microsoft NERD] in Kendall Square during
which you can dive into your final project's implementation alongside
classmates and staff. If you choose to partake, you’ll be asked to
propose three milestones for yourself that evening: a "good" one that
you intend to achieve no matter what; a "better" one that you think you
can achieve; and a "best" one that you hope to achieve. Pizza will be
served around 9:00pm; Chinese food will be served around 1:00am; and
those still standing at 5:00am will be treated to breakfast at IHOP.
Snacks and drinks will be served throughout the evening.

*Space is limited, so attendance is lotteried. If you RSVPed for a spot
at this year's Hackathon, you should have heard from the CS50 Bot
already as to whether you have a spot or were waitlisted. If not, email
hackathon@cs50.net to inquire.*


== How to get there

CS50 Shuttles will take us from Harvard to NERD, per the tables below.
Upon arrival at Lamont (or the Quad), look for CS50 staff to be sure
you're in the right place (and on the right shuttle). If you arrive late
and miss the last shuttle, not to worry; simply take the T to Kendall
Square and
http://maps.google.com/maps?saddr=Kendall%2FMIT+Station,\+Main+Street,+Cambridge,+MA+02142+(red+line+-+inbound))&daddr=1+Memorial+Dr,+Cambridge,+MA+02142&hl=en&ll=42.361398,-71.083667&spn=0.006088,0.010686&sll=42.362555,-71.084075&sspn=0.006088,0.010686&geocode=FXtmhgIdoE_D-ynRrUxFr3DjiTFc6rv1CQuU9A%3BFcthhgIdGmPD-yklGNYjpHDjiTFfD45X0nLZGw&vpsrc=6&gl=us&dirflg=w&mra=ltm&t=m&z=17[walk to 1 Memorial Drive], then check in with the guard in the lobby.
Call 617-BUG-CS50, option 0, if you find yourself lost. We'll do our
best to stick to the schedule below, but please forgive if traffic
results in some waiting.

*If you can't make your prescribed time below or if you want to travel
with your partner(s), that's fine; catch whichever shuttle you can but
let hackathon@cs50.net know in advance so we know when to expect you.*

[cols=",",options="header",]
|==========================================
|If your LAST name starts with... |go to...
|A – G |Lamont at 7:35pm on Wed 12/5
|H – N |Lamont at 8:05pm on Wed 12/5
|O – Z |Lamont at 8:35pm on Wed 12/5
|==========================================

[cols=",",options="header",]
|=======================================================================
|Unless... |in which case...
|you live in the Quad |go to the Quad shuttle stop at 7:30pm on Wed 12/5

|you live off-campus and don't need a ride |go to
http://maps.google.com/maps?q=1+Memorial+Drive,+Cambridge+MA&hl=en&sll=37.0625,-95.677068&sspn=52.902929,87.539063&vpsrc=0&hnear=1+Memorial+Dr,+Cambridge,+Middlesex,+Massachusetts+02142&t=m&z=16[1 Memorial Drive]; check in with the guard in the lobby

|you missed the shuttle or were confirmed for late arrival by the CS50
Bot |take a taxi to
http://maps.google.com/maps?q=1+Memorial+Drive,\+Cambridge+MA&hl=en&sll=37.0625,-95.677068&sspn=52.902929,87.539063&vpsrc=0&hnear=1+Memorial+Dr,+Cambridge,+Middlesex,+Massachusetts+02142&t=m&z=16[1 Memorial Drive]
OR take the T to Kendall Square and
http://maps.google.com/maps?saddr=Kendall%2FMIT+Station,+Main+Street,+Cambridge,+MA+02142+(red+line+-+inbound))&daddr=1+Memorial+Dr,+Cambridge,+MA+02142&hl=en&ll=42.361398,-71.083667&spn=0.006088,0.010686&sll=42.362555,-71.084075&sspn=0.006088,0.010686&geocode=FXtmhgIdoE_D-ynRrUxFr3DjiTFc6rv1CQuU9A%3BFcthhgIdGmPD-yklGNYjpHDjiTFfD45X0nLZGw&vpsrc=6&gl=us&dirflg=w&mra=ltm&t=m&z=17[walk to 1 Memorial Drive]; check in with the guard in the lobby
|=======================================================================


What to bring
~~~~~~~~~~~~~


You must bring...
^^^^^^^^^^^^^^^^^

* Harvard ID (unless you don't have one, in which case bring a printout
of the CS50 Bot's confirmation of your spot)
* Laptop (that supports Wi-­Fi) plus power adapter
* A signed http://cdn.cs50.net/2012/fall/events/release.pdf[release
form] (we'll have blank copies on the shuttles)
* Excitement


You might also want to bring...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

* Camera
* Contact lens case/solution; eyeglasses
* Headphones; iPod
* Phone with charger
* Sweater/sweatshirt


You may not bring...
^^^^^^^^^^^^^^^^^^^^

* Alcohol, etc.


== FAQs


=== Can I attend?

Space is limited, so attendance is lotteried. If you registered for a
spot at this year's Hackathon, you should have heard from the CS50 Bot
by Tue 12/4 as to whether you have a spot! If not, email
hackathon@cs50.net to inquire.


=== Can I arrive late?

Yes, but only if you receive an email from the CS50 Bot confirming a
"late arrival" for you. (Space is limited, so we try to give preference
to those who can partake for the entire time.)


=== Can I leave early?

For those who'd like sleep, some CS50 Shuttles will depart NERD at 5am
for Harvard. For those who'd like pancakes, other CS50 Shuttles will
depart NERD at 5am for IHOP and will return to Harvard by 7am. If you
need to return to Harvard before 5am, you'll need to take a taxi, as the
T doesn't start running until after 5:15am.


=== What if I can't attend after all?

If the CS50 Bot confirmed your spot but you can no longer attend, please
email hackathon@cs50.net right away so that we can give your spot to
someone who's waitlisted.


=== What if my partner was waitlisted but I wasn't?

Let hackathon@cs50.net know.


=== Will there be food and drinks?

Yes. Lots. Often.


=== Will there be office hours?

Yes, but one-on-one help will be limited, as a goal of the Hackathon is
to remove the last of CS50's training wheels! TFs and CAs will be
present for guidance, but they'll also be hacking away on projects of
their own! CS50 Queue won't be in use, but there will be a staff area
for Q&A, and we'll keep an eye on
http://cs50.net/discuss[cs50.net/discuss].


=== Will there be Wi-Fi?

Yes. But best to download anything big (e.g., software, movies, etc.)
beforehand at Harvard, lest Internet speeds be a bit slow with so many
people on it!
