= CS50 Hackathon
:toc: left

The CS50 Hackathon is an epic all-nighter in the http://shepleybulfinch.com/images/hub_images/sb_home_944x583_harvard_hi_2.jpg[HBS Hives] atop the http://i-lab.harvard.edu/[i-lab] at https://maps.google.com/maps?t=m&q=125+Western+Avenue%2C+Boston+MA&output=classic[125 Western Avenue] during
which you can dive into your final project's implementation alongside
classmates and staff. If you choose to partake, you'll be asked to
propose three milestones for yourself that evening: a "good" one that
you intend to achieve no matter what; a "better" one that you think you
can achieve; and a "best" one that you hope to achieve. Felipe's will be
served around 9pm; Dominos will be served around 1am; and
those still standing at 5am will be treated to breakfast at IHOP.
Snacks and drinks will be served throughout the evening.

*Space is limited, so attendance is lotteried. If you RSVPed for a spot
at this year's Hackathon, you should have heard from the CS50 Bot
already as to whether you have a spot or were waitlisted. If not, email
mailto:heads@cs50.harvard.edu[heads@cs50.harvard.edu] to inquire.*

*Space at IHOP is even more limited, so attendance at breakfast may be lotteried separately, depending on how many classmates are still awake at 5am!*

== When to get there

So that check-in isn't overwhelmed (and you aren't stuck waiting in line), do arrive at the HBS Hives per the times below (unless you've been confirmed by the CS50 Bot for late arrival, in which case just arrive asap).  If you can't make your prescribed time or if you want to travel with your partner(s), that's fine; just let mailto:heads@cs50.harvard.edu[heads@cs50.harvard.edu] know in advance so we know when to expect you.

[options=header,width=75%]
|===
| If your LAST name starts with... | arrive at HBS Hives at...
| A – G | 7:00pm
| H – N | 7:15pm
| O – Z | 7:30pm
|===

== How to get there

* If *walking* from, say, Out of Town News, link:https://www.google.com/maps/dir/Harvard+Square,+18+Brattle+St+%23352,+Cambridge,+MA+02138/125+Western+Ave,+Allston,+Boston,+MA/@42.3686033,-71.1295785,15z/data=!4m19!4m18!1m10!1m1!1s0x89e37742bc65ca79:0x59ca183286a63b76!2m2!1d-71.11896!2d42.373532!3m4!1m2!1d-71.1254162!2d42.3666013!3s0x89e377610cfd3869:0x1025a278cd0f4aa5!1m5!1m1!1s0x89e37761d7d4572b:0xaf083e816c6fc10c!2m2!1d-71.124626!2d42.363655!3e2[follow this route]. Odds are the walk will take 20+ minutes.
* If *taking the shuttle*, take the Allston Express to the i-lab (which is where the HBS Hives are), per the schedule for the http://www.transportation.harvard.edu/shuttle-van-services/shuttles-schedule/evening-nights-monday-friday[Allston Campus Express PM]; consult the column called *Hi Lab*. Those are regularly scheduled shuttles, not CS50 Shuttles, so space will be limited.  Odds are the trip will take 10+ minutes.
* If *driving*, drive to https://maps.google.com/maps?t=m&q=125+Western+Avenue%2C+Boston+MA&output=classic[125 Western Avenue] in Allston (aka Boston).  Metered parking is available *behind* the i-lab, in the lot whose entrance is on Western Avenue itself.

If you find yourself lost, call 617-BUG-CS50, option H, and tell us what you see around you!

== What to bring 

=== You must bring...

* Harvard ID (unless you don't have one, in which case bring a printout
of the CS50 Bot's confirmation of your spot)
* Laptop (that supports Wi-Fi) plus power adapter

=== You might also want to bring...

* Blanket; pillow
* Camera
* Contact lens case/solution; eyeglasses
* Headphones; iPod
* Phone with charger
* Sweater/sweatshirt
* Water bottle

=== You may not bring...

* Alcohol, etc.

== FAQs

=== Can I attend?

Space is limited, so attendance is lotteried. If you registered for a
spot at this year's Hackathon, you should have heard from the CS50 Bot
by Tue 12/2 as to whether you have a spot! If not, email
mailto:heads@cs50.harvard.edu[heads@cs50.harvard.edu] to inquire.

=== Can I arrive late?

Yes, but only if you receive an email from the CS50 Bot confirming a
"late arrival" for you. (Space is limited, so we try to give preference
to those who can partake for the entire time.)

=== Can I leave early?

If you really, really want to, yes.  If you leave before 3am, call the http://www.transportation.harvard.edu/shuttle-van-services/evening-van-service[Evening Van Service] at 617-495-0400 before 2:30am to arrange for pick-up. If you leave between 3am and 5am, best to use https://www.uber.com/[Uber] or call 617-782-5500 for a taxi. If leaving on foot, be sure to walk with multiple friends.

=== When does it end?

By 5am for folks who're sleepy and by 7am for folks who're awake (and hungry!) for IHOP, though <<can_i_go_to_ihop,attendance at breakfast may be lotteried>>.

=== When does it start?

Around 7pm, but do check <<when_to_get_there,when to get there>>.

=== Will there be shuttles?

*If, because of mobility impairment or medical condition, you find it difficult or impossible to use Harvard's shuttles, do contact the http://www.transportation.harvard.edu/shuttle-van-services/evening-van-service[Evening Van Service] in advance of the Hackathon to make arrangements to and from the Hackathon.  Just let mailto:heads@cs50.harvard.edu[heads@cs50.harvard.edu] know if you need a hand.*

==== To the Hackathon?

Yes, via regularly scheduled shuttles. But space will be limited, so it's probably best to walk to the Hackathon instead with friends.

With that said, you can take the Allston Express to the i-lab (which is where the HBS Hives are), per the schedule for the   http://www.transportation.harvard.edu/shuttle-van-services/shuttles-schedule/evening-nights-monday-friday[Allston Campus Express PM]; consult the column called *Hi Lab*. Those are regularly scheduled shuttles, not CS50 Shuttles, so space will be limited. Odds are the trip will take 10+ minutes.

==== From the Hackathon?

Yes, via chartered CS50 Shuttles. Some of the shuttles will head to IHOP around 5am, depending on how many classmates are (still!) hungry, and some shuttles will head to the River houses, Yard, and Quad.

With that said, space will still be limited, even though we've literally reserved every shuttle that Harvard owns! So the shuttles destined for the River houses, Yard, and Quad might make multiple loops, in which case there might be a bit of a wait. But you're welcome to walk home with friends if you'd rather not wait!

Please forgive, especially if weary or grumpy at that hour, if we can't quite fit everyone into shuttles all at once!

=== Can I go to IHOP?

Space at IHOP is even more limited than the Hackathon itself, so attendance at breakfast may be lotteried separately, depending on how many classmates are still awake at 5am!

Please forgive if we can't accommodate everyone who'd like to go!

=== What if I can't attend after all?

If the CS50 Bot confirmed your spot but you can no longer attend, please
email mailto:heads@cs50.harvard.edu[heads@cs50.harvard.edu] right away so that we can give your spot to
someone who's waitlisted.

=== What if my partner was waitlisted but I wasn't?

Let mailto:heads@cs50.harvard.edu[heads@cs50.harvard.edu] know.

=== Will there be food and drinks?

Yes! But we're literally maxing out the capacities of two Dominos plus Felipe's, so do be gentle with quantities. We thought it best to de-waitlist as many classmates as possible, albeit at a risk of running low on food!

=== Will there be office hours?

Yes, but one-on-one help will be limited, as a goal of the Hackathon is
to remove the last of CS50's training wheels! TFs and CAs will be
present for guidance, but they'll also be working on projects of their own!

If really in need of help, though, look for staff by the stairs where you checked in!

=== Will there be Wi-Fi?

Yes. But best to download anything big (e.g., software, movies, etc.)
beforehand, lest Wi-Fi at HBS be a bit slow with so many
people on it!

=== Will there be a live video stream?

Yes, periodically throughout the evening. Head to http://live.cs50.net/ during the Hackathon if you'd like to see what's going on outside of your hive!
