= Discounts
:toc: left

Below are some discounts available to Harvard affiliates. See http://www.procurement.harvard.edu/news.shtml[Harvard Strategic Procurement] and https://outingsandinnings.harvard.edu/[Outings & Innings] for more!

== B&H Photo and Video

Harvard gets (significant) discounts on audio and video goods from http://www.procurement.harvard.edu/secure/goods/av_general.shtml[B&H].

== DriveSavers

*http://www.drivesavers.com/*

"DriveSavers is the worldwide leader in data recovery services and
provides the fastest, most secure and reliable data recovery service
available."

Harvard's discount code is *DS19771*.

== ESPN3

*http://espn.go.com/espn3/*

http://espn.go.com/espn3/[ESPN3] is a broadband network for live sports
programming. . . . http://espn.go.com/espn3/[ESPN3] is available free to
fans accessing the site from a college campus network in the United
States. . . ."

So long as you're within (or https://vpn.fas.harvard.edu/[VPNed] into)
harvard.edu (i.e., your IP address starts with `140.247.`), you should
have access to http://espn.go.com/espn3/[ESPN3].

== Harvard University Technology Services

Harvard gets http://personal.huitproducts.harvard.edu/[discounts from Apple and Dell],
but realize that you can get (some of) those same discounts from an
http://www.apple.com/retail/[Apple Store] directly by showing your
Harvard ID at checkout. 

== Personal Cellular Services

http://huit.harvard.edu/buy-cell-phones-and-smartphones
