= VMware Fusion

Here's how to install the link:..[CS50 Appliance] using
VMware Fusion for link:#_installation[Mac OS].

== Installation

. Download VMware Fusion as follows:
* If you are a student taking CS50x through edX or CS50's certificate option through Harvard Extension School, email software@cs50.net to request a 365-day license.  Within a few minutes, you should receive a reply with further instructions on how to download VMware Fusion.
* If you are a student at Harvard College or at Harvard Extension School (taking a course for credit), https://docs.google.com/spreadsheet/viewform?hl=en_US&formkey=dHoyMG5LNTgxeGFhakNaaE9CdTlkbWc6MQ[apply for the VMware Academic Program] (VMAP) in order to obtain a username and password with which you can download VMware Fusion for free from http://vmap.cs50.net/, along with a serial number.
.  Double-click the file you just downloaded (which is likely in your
*Downloads* folder) in order to "mount" VMware Fusion's icon on your
desktop.
.  A window should open. Drag the *VMware Fusion* (or *VMware
Fusion.app*) icon in that window to your *Applications* folder.
.  Download the CS50 Appliance itself at
http://mirror.cs50.net/appliance50/19/i386/appliance50-19-vmware.ova
(http://mirror.cs50.net/appliance50/19/i386/appliance50-19-vmware.ova?torrent[torrent]).
That file is over 1GB in size, so it might take a while to download.
. Once the file has finished downloading, check whether its name ends in *.ova* or *.ovf*.  There appears to be a bug in Chrome whereby *.ova* is incorrectly changed to *.ovf*, so if the file's name does now end in *.ovf*, change it back as follows:
* Single-click the file.
* Hit Enter.
* Change *.ovf* to *.ova*.
* Hit Enter.
. Next, launch VMware Fusion, as by double-clicking its icon, which should
be in your *Applications* folder. If prompted with a *Software License
Agreement*, click *Agree*. If prompted to provide a license, select the 30-day trial instead.
If prompted to *Create New*, *Convert VM*, or *Migrate PC*, simply click *Skip*. 
7.  Ensure that you have the latest version of VMware Fusion, as by
selecting *VMware Fusion > Check for Updates...*. Update and relaunch
VMware Fusion as needed.
8.  Select *File > Import...*. Navigate your way to that *appliance50-19-vmware.ova*
file (which is probably still in *Downloads*) and select it.
9. Click VMware Fusion's &#9654; button to start the appliance. If
prompted to "upgrade this virtual machine," click *Upgrade*.

The appliance should then boot! If you see a black-and-white screen
entitled *GNU GRUB*, no need to do anything; the appliance will continue
to boot after a few seconds!
