= VMware Fusion

Here's how to install the link:..[CS50 Appliance] using VMware Fusion for link:#installation[Mac OS].

== Installation

. link:https://docs.google.com/spreadsheet/viewform?hl=en_US&formkey=dHoyMG5LNTgxeGFhakNaaE9CdTlkbWc6MQ[Apply for the VMware Academic Program] (VMAP) in order to obtain a username and password with which you'll eventually be able to download a license key for VMware Fusion from link:https://e5.onthehub.com/WebStore/Security/Signin.aspx?ws=340f7ddc-c740-de11-b696-0030485a8df0&vsro=8&rurl=%2fWebStore%2fProductsByMajorVersionList.aspx%3fws%3d340f7ddc-c740-de11-b696-0030485a8df0%26vsro%3d8&JSEnabled=1[OnTheHub]. Odds are you won't need that license key just yet, since VMware Fusion offers a 30-day trial that you can use in the meantime.
. In your Mac's top-left corner, select *&#63743; > About This Mac* to determine determine which version of Mac OS you have.
+
--
* If running Mac OS 10.8 or later, link:http://www.vmware.com/go/try-fusion-en[download VMware Fusion 7].
* If running Mac OS 10.7, link:https://my.vmware.com/web/vmware/details?downloadGroup=FUS-604&productId=361&rPId=6092[download VMware Fusion 6]. (Click *Download Now* to the right of *VMware Fusion 6 Only*. If prompted to log in, select the *Register* tab and register for a vmware.com account, which will be separate from your VMAP account.)
* If running Mac OS 10.6, link:https://my.vmware.com/web/vmware/details?downloadGroup=FUS-505&productId=294&rPId=6208[download VMware Fusion 5]. (Click *Download Now* to the right of *Download including only VMware Fusion 5.0.5 software*. If prompted to log in, select the *Register* tab and register for a vmware.com account, which will be separate from your VMAP account.)
--
+
. Double-click the file you just downloaded (which is likely in your *Downloads* folder) in order to "mount" VMware Fusion's icon on your desktop.
. A window should open. Double-click the *VMware Fusion* (or *VMware Fusion.app*) icon in that window, click *Open* if prompted, and type your password if prompted.
. When prompted for a license key, select *I want to try VMware Fusion 7 for 30 days* (unless you already have a VMAP account, in which case you can paste your own license key), and then click *Continue*.
. When prompted for your email address, type your email address, ensure that *Try VMware Fusion 7* is selected (and not *Try VMware Fusion 7 Professional*), and then click *Continue*.
. Type your password if prompted, and then click *OK*.
. Click *Done*.
. Download the CS50 Appliance itself at http://mirror.cs50.net/appliance50/2014/releases/0/appliance50-2014-vmware.ova (http://mirror.cs50.net/appliance50/2014/releases/0/appliance50-2014-vmware.ova?torrent[torrent]).  That file is nearly 2GB in size, so it might take a while to download.
. Once the file has finished downloading, check whether its name ends in *.ova* or *.ovf*. There appears to be a bug in some versions of Chrome whereby *.ova* is incorrectly changed to *.ovf*, so if the file's name does now end in *.ovf*, change it back as follows:
* Single-click the file.
* Hit Enter.
* Change *.ovf* to *.ova*.
* Hit Enter.
. Next, launch VMware Fusion, as by double-clicking its icon, which should
be in your *Applications* folder.  If prompted to *Create New*, *Convert VM*, or *Migrate PC*, simply click *Skip*. 
.  Ensure that you have the latest version of VMware Fusion, as by selecting *VMware Fusion > Check for Updates...*. Update and relaunch VMware Fusion as needed.
.  Select *File > Import...*. Click *Choose File...*, and then navigate your way to that *appliance50-2014-vmware.ova* file (which is probably still in *Downloads*) and select it.
. When prompted with *Finish*, click *Finish*.
. The appliance should start to boot. (If it doesn't, click VMware Fusion's &#9654; button.) If prompted to "upgrade this virtual machine," click *Upgrade*. Don't worry if you see *fail* in red a couple times as the appliance starts.
. When prompted to register, follow the on-screen prompts.
