= VMware Fusion

Here's how to install the link:..[CS50 Appliance] using VMware Fusion for link:#installation[Mac OS].

== Installation

. link:https://docs.google.com/spreadsheet/viewform?hl=en_US&formkey=dHoyMG5LNTgxeGFhakNaaE9CdTlkbWc6MQ[Apply for the VMware Academic Program] (VMAP) in order to obtain a username and password with which you'll eventually be able to download a serial number for VMware Fusion 7 from link:https://e5.onthehub.com/WebStore/Security/Signin.aspx?ws=340f7ddc-c740-de11-b696-0030485a8df0&vsro=8&rurl=%2fWebStore%2fProductsByMajorVersionList.aspx%3fws%3d340f7ddc-c740-de11-b696-0030485a8df0%26vsro%3d8&JSEnabled=1[OnTheHub]. You won't need that serial number just yet, since VMware Fusion 7 offers a 30-day trial that you can use in the meantime.
. link:http://www.vmware.com/go/try-fusion-en[Download a 30-day trial of VMware Fusion 7].
. Double-click the file you just downloaded (which is likely in your *Downloads* folder) in order to "mount" VMware Fusion's icon on your desktop.
.  A window should open. Double-click the *VMware Fusion* (or *VMware Fusion.app*) icon in that window, click *Open* if prompted, and  and follow to your *Applications* folder.
.  Download the CS50 Appliance itself at http://mirror.cs50.net/appliance50/2014/releases/0/appliance50-2014-vmware.ova (http://mirror.cs50.net/appliance50/2014/releases/0/appliance50-2014-vmware.ova?torrent[torrent]).
That file is over 2GB in size, so it might take a while to download.
. Once the file has finished downloading, check whether its name ends in *.ova* or *.ovf*. There appears to be a bug in some versions of Chrome whereby *.ova* is incorrectly changed to *.ovf*, so if the file's name does now end in *.ovf*, change it back as follows:
* Single-click the file.
* Hit Enter.
* Change *.ovf* to *.ova*.
* Hit Enter.
. Next, launch VMware Fusion, as by double-clicking its icon, which should
be in your *Applications* folder. If prompted with a *Software License
Agreement*, click *Agree*. If prompted to provide a license, select the 30-day trial instead.
If prompted to *Create New*, *Convert VM*, or *Migrate PC*, simply click *Skip*. 
7.  Ensure that you have the latest version of VMware Fusion, as by
selecting *VMware Fusion > Check for Updates...*. Update and relaunch
VMware Fusion as needed.
8.  Select *File > Import...*. Navigate your way to that *appliance50-19-vmware.ova*
file (which is probably still in *Downloads*) and select it.
9. Click VMware Fusion's &#9654; button to start the appliance. If
prompted to "upgrade this virtual machine," click *Upgrade*.

The appliance should then boot! If you see a black-and-white screen
entitled *GNU GRUB*, no need to do anything; the appliance will continue
to boot after a few seconds!
