= VMware Fusion

Here's how to install the link:..[CS50 Appliance] using VMware Fusion for Mac OS X.

== Installation

. VMware is supporting CS50 and CS50x by providing evaluation licenses for VMware Fusion 7 at no cost to students. These will be active throughout 2015.
* If you are enrolled in CS50 at Harvard College or CSCI E-50 through the Harvard Extension School, visit the link:https://cs50.harvard.edu/vmware[VMware Software Center for CS50] and sign in with your Harvard University ID number and pin. You will automatically receive an account at the Software Center. Its user name and initial email address will both be your Harvard email address.
* If you are enrolled in CS50x, the on-line offering through edX, visit the link:http://cs50.edX.org/vmware[VMware Software Center for CS50x] and sign in with your edX user name and password. You will automatically receive an account at the Software Center. Its user name will be your edX user name. Its initial email address will be the one you've registered with edX.

+
In either case, you can change your preferred email address later if you wish, but leave the user name unchanged (even if it's an email address that you no longer use).
. The VMware Software Center is set up like a store. On the "store front" page, click on VMware Fusion 7. If you see both free and non-free offerings of the product, choose the free one. (It's the same Fusion 7 Pro software, but it expires after 2015.) Click the *Add to Cart* button, then proceed through the check-out process until you reach a screen with a *Start Download* button. After a momentary delay, your unique product key should appear in red on that screen. Copy that key into a place where you keep software serial numbers and license keys. You'll need it to install Fusion 7 now and to reinstall it later if the need arises.
+
Click the *Start Download* button to download the installer for Fusion 7.
. Double-click the file you just downloaded (which is likely in your *Downloads* folder) in order to "mount" VMware Fusion's icon on your desktop.
. A window should open. Double-click the *VMware Fusion* (or *VMware Fusion.app*) icon in that window, click *Open* if prompted, and type your password if prompted. Follow the instructions to install Fusion 7. When prompted for a license key, use the product key generated for you by the VMware Software Center.
. Download the CS50 Appliance itself at http://mirror.cs50.net/appliance50/2014/releases/24/appliance50-2014-vmware.ova (http://mirror.cs50.net/appliance50/2014/releases/24/appliance50-2014-vmware.ova.torrent[torrent]).  That file is nearly 2GB in size, so it might take a while to download.
. Once the file has finished downloading, check whether its name ends in *.ova* or *.ovf*. There appears to be a bug in some versions of Chrome whereby *.ova* is incorrectly changed to *.ovf*, so if the file's name does now end in *.ovf*, change it back as follows:
* Single-click the file.
* Hit Enter.
* Change *.ovf* to *.ova*.
* Hit Enter.
. Next, launch VMware Fusion, as by double-clicking its icon, which should
be in your *Applications* folder.  If prompted to *Create New*, *Convert VM*, or *Migrate PC*, simply click *Skip*. 
.  Ensure that you have the latest version of VMware Fusion, as by selecting *VMware Fusion > Check for Updates...*. Update and relaunch VMware Fusion as needed.
.  Select *File > Import...*. Click *Choose File...*, and then navigate your way to that *appliance50-2014-vmware.ova* file (which is probably still in *Downloads*) and select it.
. When prompted with *Finish*, click *Finish*.
. The appliance should start to boot. (If it doesn't, click VMware Fusion's &#9654; button.) If prompted to "upgrade this virtual machine," click *Upgrade*. Don't worry if you see *fail* in red a couple of times as the appliance starts.
. When prompted to register, follow the on-screen prompts.
