= VMware Workstation
:toc: left

Here's how to install the link:..[CS50 Appliance] using VMware Workstation for link:#windows[Windows] or link:#linux[Linux].

[[windows]]
== Windows

=== Installation

. VMware is supporting CS50 and CS50x by providing evaluation licenses for VMware Workstation 11 at no cost to students. These will be active throughout 2015.
* If you are enrolled in CS50 at Harvard College or CSCI E-50 through the Harvard Extension School, visit the link:https://cs50.harvard.edu/vmware[VMware Software Center for CS50] and sign in with your Harvard University ID number and pin. You will automatically receive an account at the Software Center. Its user name and initial email address will both be your Harvard email address.
* If you are enrolled in CS50x, the on-line offering through edX, visit the link:http://cs50.edX.org/vmware[VMware Software Center for CS50x] and sign in with your edX user name and password. You will automatically receive an account at the Software Center. Its user name will be your edX user name. Its initial email address will be the one you've registered with edX.

+
In either case, you can change your preferred email address later if you wish, but leave the user name unchanged (even if it's an email address that you no longer use).
. The VMware Software Center is set up like a store. On the "store front" page, click on VMware Workstation 11. If you see both a free and a non-free offering of the product, choose the free one. In the drop-down menu labeled *Choose a platform*, make sure that *Windows* is selected. Click the *Add to Cart* button, then proceed through the check-out process until you reach a screen with a *Start Download* button. After a momentary delay, your unique product key should appear in red on that screen. Copy that key into a place where you keep software serial numbers and license keys. You'll need it to install Workstation 11 now and to reinstall it later if the need arises.
+
Click the *Start Download* button to download the installer for Workstation 11.
. Double-click the file you just downloaded (which is likely in your *Downloads* folder) in order launch VMware Workstation's installer.
. If you are asked whether to allow the installer to make changes to your computer, click *Yes*.
. A window entitled *VMware Workstation Setup* should appear. Click *Next*.
. When prompted with a license agreement, select *I accept the terms in the license agreement*, then click *Next*.
. When prompted to select a *Setup Type*, click *Typical*.
. When prompted for a *Destination Folder*, click *Next*.
. When prompted about *Software Updates*, decide whether to check or uncheck *Check for product updates on startup*, and then click *Next*.
. When prompted about the *User Experience Improvement Program*, decide whether to check or uncheck the box, then click *Next*.
. When prompted about *Shortcuts*, decide whether to check or uncheck the boxes, then click *Next*.
. When asked whether you're *Ready to Perform the Requested Operations*, click *Continue*.
. Once you see *Enter License Key*, paste in the license key you saved earlier, then click *Enter >*.
. You should see *Setup Wizard Complete*. Click *Finish*.
. You don't need to keep the Workstation installer after a successful installation. You can download it again later if you need it.
. Download the CS50 Appliance itself from http://mirror.cs50.net/appliance50/2014/releases/24/appliance50-2014-vmware.ova (http://mirror.cs50.net/appliance50/2014/releases/24/appliance50-2014-vmware.ova.torrent[torrent]). That file is nearly 2GB in size, so it might take a while to download.
. Launch VMware Workstation 11 and select *Open...* from the *File* menu, then navigate to *appliance50-2014-vmware.ova* (which is likely in your *Downloads* folder) and select it. Click *Open*.
. When prompted for a name and local storage path, you can change the defaults if you wish. Then click *Import*.
. If you see a warning that the import failed because the file "did not pass OVF specification conformance or virtual hardware compliance checks," don't worry. Just click *Retry*, and the import should succeed.
. In the new tab describing the CS50 Appliance, click *&#9654; Power on this virtual machine*. If prompted about removable devices, decide whether to check or uncheck *Do not show this hint again*, then click *OK*.

=== Troubleshooting

==== Binary translation is incompatible with long mode on this platform

If you see this message, you should try to enable link:/virtualization[hardware virtualization] on your computer. However, if your system doesn't support hardware virtualization, you can still run the CS50 Appliance because it doesn't require "long mode", which is needed for 64-bit virtual machines.

== Linux

=== Installation

. VMware is supporting CS50 and CS50x by providing evaluation licenses for VMware Workstation 11 at no cost to students. These will be active throughout 2015.
* If you are enrolled in CS50 at Harvard College or CSCI E-50 through the Harvard Extension School, visit the link:https://cs50.harvard.edu/vmware[VMware Software Center for CS50] and sign in with your Harvard University ID number and pin. You will automatically receive an account at the Software Center. Its user name and initial email address will both be your Harvard email address.
* If you are enrolled in CS50x, the on-line offering through edX, visit the link:http://cs50.edX.org/vmware[VMware Software Center for CS50x] and sign in with you edX user name and password. You will automatically receive an account at the Software Center. Its user name will be your edX user name. Its initial email address will be the one you've registered with edX.

+
In either case, you can change your preferred email address later if you wish, but leave the user name unchanged (even if it's an email address that you no longer use).

. The VMware Software Center is set up like a store. On the "store front" page, click on VMware Workstation 11. If you see both a free and a non-free offering of the product, choose the free one. In the drop-down menu labeled *Choose a platform*, make sure that *Linux* is selected. Click the *Add to Cart* button, then proceed through the check-out process until you reach a screen with a *Start Download* button. After a momentary delay, your unique product key should appear in red on that screen. Copy that key into a place where you keep software serial numbers and license keys. You'll need it to install Workstation 11 now and to reinstall it later if the need arises.
+
Click the *Start Download* button to download the installer for Workstation 11.
. Install VMware Workstation.
. Download the CS50 Appliance from http://mirror.cs50.net/appliance50/2014/releases/24/appliance50-2014-vmware.ova (http://mirror.cs50.net/appliance50/2014/releases/24/appliance50-2014-vmware.ova.torrent[torrent]).
. Import the CS50 Appliance into VMware Workstation.
