= Seminars
:toc: left

Each fall, CS50 offers a series of seminars. Led by the course's own
https://cs50.harvard.edu/staff[staff] as well as by
http://huit.harvard.edu/[HUIT staff] and
http://www.abcd.harvard.edu/[ABCD members], CS50 seminars are designed
to equip students with skills and savvy beyond the scope of the course's
own https://cs50.harvard.edu/syllabus[syllabus]. Below are seminars from
this year and past years.

== Fall 2014

Click a seminar's title to see its description and location. No need to register to attend. Each seminar will be streamed live at https://live.cs50.net/[live.cs50.net] and then posted here a few days after it's held!

++++
<iframe src="https://www.google.com/calendar/embed?showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=9q5vbacbfsvejq8g84j66gn14o%40group.calendar.google.com&amp;color=%235229A3&amp;ctz=America%2FNew_York" style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe>
++++

=== 3D Modeling and Manufacture

_by Ansel Duff_

The software/hardware harmony brings code to life. This seminar aims to familiarize students with elementary manufacturing techniques and provide students with access to CS50's 3D printers. Whether you're designing a holder for a mobile phone payment platform or reinventing the Hue lighting system, customized mechanical components transform a purely software backend to a physical product.

* video coming soon

=== Amazing Web Apps with Ruby on Rails

_by Gabriel Guimaraes, Stephen Turban and Zack Chauvin_

Ruby on Rails is an awesome framework that lets you create web applications really fast, without having to worry about unnecessary details. In this seminar we will take a look at the Model View Controller paradigm and how this way of thinking can be applied to web programming, specifically using Rails. We will also discuss what a web framework does for you (and what it doesn't do) showing an example of how Rails can solve many tasks of web programming automatically, leaving you more time to work on the real world problems your application is actually trying to solve.

* video coming soon

=== Android 101

_by Fred Widjaja_

Learn the basics of building apps on Android, the world's most popular mobile platform! We'll also be going through how to code in Java and how to use development tools like Android Studio.

* video coming soon

=== Breaking Through The (Google) Glass Ceiling

_by Christopher Bartholomew_

Do you have an interest in creating apps for the most controversial piece of wearable technology today? The rise and success of any wearable technology depends on one major element: apps. In this seminar, we’ll overview Google Glass’s three application design patterns: Periodic Notifications using Glass’s Mirror API, Immersion using the Glass Developer Kit (GDK), and Ongoing Tasks which utilize both the Mirror API and GDK. We’ll also provide helpful resources on interacting with and implementing REST web services, creating database structures for Google’s Open Authorization (OAuth), and setting up a standard Integrated Development Environment (IDE) for your chosen design pattern. If you’re planning on creating a Google Glass application, then this seminar will help you get started.

* http://cs50.tv/2014/fall/seminars/glass/[Video]
* http://cdn.cs50.net/2014/fall/seminars/glass/glass.pdf[Slides]
* http://cdn.cs50.net/2014/fall/seminars/glass/setup_and_playground.pdf[Setup Instructions]

=== Build Tomorrow's Library

_by Jeffrey Licht_

Get your hands on the full bibliographic data about virtually all of the 12.7 million items in the Harvard Library collection, plus millions of images, plus some extremely anonymized usage data, and more. All of this can be put to use in the apps you'll learn to write that use the API of Harvard Library Cloud, a new open metadata server. Library metadata is rich, complex, and very human, so let's dig in!

* video coming soon

=== Building Dynamic Web Apps with Laravel

_by Eric Ouyang_

Laravel is a powerful and elegant PHP web development framework for building interactive websites, such as CS50's own site! Learn about how to leverage this cutting edge development tool to create everything from simple APIs to sophisticated modern web applications.

* video coming soon

=== CSS: Awesome Style and Design

_by Allison Buchholtz-Au and Tomas Reimers_

CSS allows for the stylization of websites. This seminar will cover basic principles for web design from selecting HTML elements with CSS to positioning elements on the page and fully understanding the "box model." Additionally, we will cover common aesthetic improvements seen on websites such as rounding corners, background images, and custom fonts.

* video coming soon

=== Data Analysis in R

_by Dusin Tran_

Data has increasingly become crucial for solving problems in industry and research. R provides a powerful and flexible toolkit for this sort of analysis: statistical modeling, machine learning, visualization, and the fundamental process of importing and manipulating data. This seminar will provide a quick introduction to using R and show the tremendous capabilities that the language has to offer.

* video coming soon

=== Data Visualization and D3

_by David Chouinard_

Learn to convey valuable insights through interactive maps, charts and diagrams. We’ll explore D3, a JavaScript library, and learn the tools for producing interactive web-based data visualization.

* video coming soon

=== Essential Scale-Out Computing

_by James Cuff_

Each day you interact with thousands upon thousands of processors, servers, storage systems and high-speed networks. You don't see them, and you don't physically touch them, but they are there, making everything happen behind the scenes. Everything is powered by advanced computing, from your morning news, movie and video streams, phone conversations, currency, financial markets, pharmaceuticals, navigation, traffic, weather, email and of course all of our social media updates.  Each of us consumes vast amounts of data and computation on a daily basis. We also continue to push the boundaries of our science and discovery. Using ever more complex computer models to peer into the darkness of space or to understanding the genetic basis as to why were are human. All of this needs computing for it to work correctly, and it also needs advanced infrastructure and distributed computing architectures to work quickly.  James Cuff is the Assistant Dean for Research Computing here at Harvard. His group runs more than sixty thousand high performance computing processors and more than fourteen petabytes of storage for science. On a global scale, this system is tiny. However, he will show you real world examples of the advances in computation science, physical infrastructure and distributed computing systems we are using each day, whether you are a particle physicist trying to reverse engineer the very fabric of the universe – or maybe you are just updating your selfie...  So what will you learn from this seminar? You are all designing software for your final project. Facebook for example, was originally designed as a small single server PHP application. In order to make it scale to today’s hundreds of thousands of servers and billions of users took years. James will explain how both datacenter and systems architectures that now surpass electrical power usage of 10-20 megawatts – (enough to power more than 20,000 houses, nearly half of the City of Cambridge) enable today’s applications to scale. Each computation, be it add, subtract, multiply, divide, strcmp(), grep or memory hash lookup you make in your application now matters. You will be shown not only how distributed computing factors into your applications, but also how the actual energy efficiency of your algorithms matters. Designing, and thinking about how your application will scale from the beginning to potentially manage 10,000’s of page impressions a second is now the new normal.

* video coming soon

=== Exposing Digital Photography

_by Dan Armendariz_

This seminar is a fast-paced introduction to photography. We'll cover exposure, the impact of exposure values on a photograph, metering, the impact of the human visual system (illusions), and a discussion of modern digital imaging technology including sensor types, sensor sizes, and the limitations that arise from these properties. By the end, you should have a better understanding of the compromises that make up all forms of digital photography from smartphones to digital SLRs and walk away with some tools to find the balance that captures the photograph you want.

* video coming soon

=== Futuristic User Interactions: An Introduction to Leap Motion

_by Armaghan Behlum and Tomas Reimers_

The leap motion is a device that allows users to interact with the computer by moving their hands in front of it. Students will learn how to write code that takes advantage of the leap motion and build websites that the user can interact with using simple hand gestures.

* video coming soon

=== How to Build Innovative Technologies

_by Abby Fichtner_

Ever wonder how startups are able to create innovative, disruptive technologies that are successful in the market? In this seminar, you'll learn lean startup and agile development practices that can be seen time and again in the small percentage of startups that make it big. Using examples from Facebook, Dropbox, Pinterest and more, you'll learn tips for how to find your initial users and validate your ideas. As well as techniques like kanban, emergent design and continuous deployment to help you build your product and get it out there as quickly and efficiently as possible.

* http://cs50.tv/2014/fall/seminars/innovative_technologies/[Video]

=== Introduction to Amazon Web Services

_by Leo Zhadanovsky_

Learn about cloud computing with Amazon Web Services. During this talk, we will discuss the various Networking, Compute, Database, Storage, Application, Deployment and Management services that AWS offers. We will demonstrate how to launch a full three tier LAMP stack in minutes, as well as how to setup a simple web server on AWS. We will also discuss several use-cases, demonstrating how customers such as Enterprises, Startups, and Government Agencies are using AWS to power their computing needs.

* http://cs50.tv/2014/fall/seminars/aws/[Video]
* http://cdn.cs50.net/2014/fall/seminars/aws/aws.pdf[Slides]

=== iOS App Development with Swift

_by Dan Armendariz_

An introduction to iOS programming using Swift, Apple's new programming language for Macs and iOS devices. We will cover the basics of the language, using APIs in your app, and deploying your app to an iOS device. Development requires a recent Mac with OS X 10.9.4 or later and, optional (but recommended), a device running iOS 7 or later.

* video coming soon

=== Learning iOS: Create your own app with Objective-C!

_by Tianyu Liu_

Ever wanted to build your own iOS app with Objective-C but didn't know where to start? Learn the basic introduction to iOS and get started making your cool apps on the App Store.

* video coming soon

=== Light Your World (with Hue Bulbs)

_by Dan Bradley_

As seen in the first week of lecture, Hue bulbs are light bulbs you can control wirelessly. They can do pretty amazing things, if you know how to program them properly. In this seminar, we'll create a small JavaScript web app that can turn Hue bulbs on and off as well as change their color. We'll also more broadly touch on APIs and Ajax calls.

* http://cs50.tv/2014/fall/seminars/hue_bulbs/[Video]

=== Meteor: a better way to build apps

_by Roger Zurawicki_

This is a hands-on introduction to Meteor, a JavaScript and Node.js framework built for the future. Meteor is an open-source platform for building top-quality web apps in a fraction of the time, whether you're an expert developer or just getting started. Meter rocks because: you write in the same language on both the server and the browser; 50 lines of code gets you a working chat app; your app will work in real time; you get an awesome package system; and you can run your app natively on iOS and Android. Find out more at https://www.meteor.com/ 

* video coming soon
	
=== Teach Your Computer to See: Augmented Reality with OpenCV

_by Joshua Meier_

In this seminar, we explore the field of computer vision using the powerful library OpenCV. We’ll learn how to build programs that use your phone/computer's camera in order to interact with the real-world, augment reality, figure out who’s in the picture, and more. Come learn about the technology powering the world’s most popular and entertaining apps.

* video coming soon

== Fall 2013

=== Amazing Web Apps with Ruby on Rails

_by Gabriel Guimaraes_

Ruby on Rails is an awesome framework that lets you create web applications really fast, without having to worry about unnecessary details!

* http://cdn.cs50.net/2013/fall/seminars/ruby_on_rails/ruby_on_rails.pdf[Slides]
* http://cs50.tv/2013/fall/seminars/ruby_on_rails/[Video]


=== Computational Linguistics

_by Lucas Freitas_

As computers become more and more present in our lives, making our interactions with them more intuitive and natural is essential. Computational linguistics refers to the field of computer science that uses computer science to do interesting things with natural language. Examples of large computational linguistic projects are Siri, the Jeopardy winner Watson, and Google Translate. This seminar will give a brief introduction to the field, and will include Python demos to show the potential of that area.

* http://cdn.cs50.net/2013/fall/seminars/computational_linguistics/computational_linguistics.pdf[Slides]
* http://cdn.cs50.net/2013/fall/seminars/computational_linguistics/computational_linguistics.zip[Source]
* http://cs50.tv/2013/fall/seminars/computational_linguistics/[Video]


=== Introduction to iOS

_by Rhed Shi_

Learn how to program iOS applications using Objective-C and XCode 5.

* http://cdn.cs50.net/2013/fall/seminars/intro_to_ios/intro_to_ios.pdf[Slides]
* http://cdn.cs50.net/2013/fall/seminars/intro_to_ios/intro_to_ios.zip[Source Code]
* http://cs50.tv/2013/fall/seminars/intro_to_ios/[Video]
	

=== JavaScript for Web Apps

_by Tomas Reimers and Mike Rizzo_

Learn about APIs and libraries available in Javascript that are useful when writing web applications. 

* http://tomasreimers.github.io/cs50-seminar/[Slides]
* http://cdn.cs50.net/2013/fall/seminars/javascript_for_web_apps/javascript_for_web_apps.zip[Source]
* http://cs50.tv/2013/fall/seminars/javascript_for_web_apps/[Video]


=== Leap Motion SDK

_by Dan Gill and Michael Sutherland_

Getting Started. Important Details. Tools and helpful tips. Community developments. Community resources. How to engage with Leap for help Q&A.

* http://cdn.cs50.net/2013/fall/seminars/leap_motion/leap_motion.pdf[Slides]
* http://cs50.tv/2013/fall/seminars/leap_motion/[Video]


=== meteor.js: JavaScript on the back end 

_by Roger Zurawicki_

A better way to build apps.  Meteor is an open-source platform for building top-quality web apps in a fraction of the time, regardless of your comfort level. 
We will cover the basics of server-side JavaScript and how to get started building cool real-time web apps!  More information at http://www.meteor.com/.

* http://cdn.cs50.net/2013/fall/seminars/meteorjs/meteorjs.pdf[Slides]
* http://cdn.cs50.net/2013/fall/seminars/meteorjs/meteorjs.zip[Source Code]
* http://cs50.tv/2013/fall/seminars/meteorjs/[Video]


=== Node.js

_by Kevin Schmid_

Node.js is a powerful JavaScript library that allows you to create programs that deal with input and output.  That includes network data and file streams, so it's great for creating web servers! Come hear all about Node.js: how it works, where it works best, and how you could use a Node.js server in your final project! In this seminar, we'll show some examples of Node.js servers and discuss server performance.

* http://cdn.cs50.net/2013/fall/seminars/nodejs/nodejs.pdf[Slides]
* http://cdn.cs50.net/2013/fall/seminars/nodejs/nodejs.zip[Source Code]
* http://cs50.tv/2013/fall/seminars/nodejs/[Video]


=== Sleek Android Design

_by Jordan Jozwiak_

Learn about Android design patterns and how to deal with so many different device versions, sizes, and pixel densities.  We will talk about fundamental mobile designs principles, Android-specific concerns, and responsive design for phones and tablets.

* http://cdn.cs50.net/2013/fall/seminars/sleek_android_design/sleek_android_design.pdf[Slides]
* http://cs50.tv/2013/fall/seminars/sleek_android_design/[Video]


=== Web Security: Active Defense

_by Luciano Arango_

Is my new website, or web application secure? How do I make sure it's secure or test if its not? In this seminar we'll put up a website that's not yet, ahem, ready, and split the attendees into two teams. Team one's job: exploit all the vulnerabilities in the code; team two's job: patch them up before team one gets there. We'll be guiding the challenge by exposing the different mistakes that become security problems, how to spot them quickly, and how to patch them up correctly.

* http://cdn.cs50.net/2013/fall/seminars/web_security/web_security.pdf[Slides]
* http://cs50.tv/2013/fall/seminars/web_security/[Video]


== Fall 2012

=== A Programmer's Introduction to APIs

_by Billy Janitsch '15_

APIs allow you to programmatically access data from websites in a useful
form. Facebook, Flickr, Tumblr, Google Maps, Freebase, Wikipedia,
last.fm, Digg, and even CS50 all have APIs that you can use to work with
a variety of interesting data. Have another source in mind? There's
probably an APP for that. Oops, I mean an API. All familiarity levels
welcome, and those in search of ideas for a cool final project are
particularly encouraged to attend.

* http://cs50.tv/2012/fall/seminars/programmer_intro/programmer_intro-720p.mp4[Video]


=== Android Apps (Now with Jelly Beans!)

_by Jordan Jozwiak '14_

As of September 2012, Android had a 68% market share on smart phones(iOS trailed with only 17% share). Android has matured substantially inthe last few years and is undoubtedly here to stay. What are thedifferences between iOS and Android? How has Android changed with therelease of ICS and Jelly Bean? And, most importantly, how can you getstarted developing for Android using Java and Eclipse?

* http://cdn.cs50.net/2012/fall/seminars/android_apps/android_apps.pdf[Slides]
* http://cs50.tv/2012/fall/seminars/android_apps/android_apps-720p.mp4[Video]


=== Defending Behind The Device: Mobile Application Security

_by Chris Wysopal_

Risks to mobile devices are similar to those of traditional software
applications and a result of insecure coding practices, privacy
violating design, and malicious intent. But mobile devices aren’t just
small computers: they are designed around personal and communication
functionality. This makes the top mobile applications risks different
from the top traditional computing risks - and an easier opportunity for
those with malicious intent. This presentation will discuss the threat
landscape and how developers and enterprise IT can tackle mobile app
risk.

* http://cdn.cs50.net/2012/fall/seminars/mobile_application_security/mobile_application_security.pdf[Slides]
* http://cs50.tv/2012/fall/seminars/mobile_application_security/mobile_application_security-720p.mp4[Video]


=== ICT4D: Technology for Good

_by Alisa Nguyen '15 and Joy Ming '15_

Information Communication Technology for Development is a field where
technology is applied to areas such as global health or mobile health,
education and literacy, food production and distribution, and more. This
seminar will demonstrate how technology can create things that are not
only flashy and awesome but can change the world.

* http://cdn.cs50.net/2012/fall/seminars/ict4d/ict4d.pdf[Slides]
* http://cs50.tv/2012/fall/seminars/ict4d/ict4d-720p.mp4[Video]


=== iOS: Writing Apps like a Boss

_by Tommy MacWilliam '13_

Looking to create a project your friends and family can download on the
App Store? Learn how easy it is to write software for iPhone and iPad.
Topics include Objective-C, XCode, and design patterns, and sample apps
include tic-tac-toe and a sports news reader.

* http://cdn.cs50.net/2012/fall/seminars/ios/ios.pdf[Slides]
* http://cdn.cs50.net/2012/fall/seminars/ios/ios.zip[Source Code]
* http://cs50.tv/2012/fall/seminars/ios/ios-720p.mp4[Video]


=== jQuery

_by Vipul Shekhawat '14_

Javascript is a client-side web programming language, used to create all
sorts of functionality on websites. This seminar focuses on jQuery, one
of the most widely used Javascript libraries. jQuery allows programmers
to easily select and manipulate elements on an HTML page, animate
elements effortlessly, send HTTP requests to servers, and much more.
According to builtwith.com, over 24 million websites use jQuery,
including nearly 60% of the top 10,000 websites on the Internet. Make
web programming a lot easier -- come to this seminar and learn jQuery!

* http://cdn.cs50.net/2012/fall/seminars/jquery/jquery.pdf[Slides]
* http://cdn.cs50.net/2012/fall/seminars/jquery/jquery.zip[Source Code]
* http://cloud.cs50.net/~vshekhawat/jquery[Link to Interactive Slides]
* http://cs50.tv/2012/fall/seminars/jquery/jquery-720p.mp4[Video]


=== JavaScript Frameworks: Why and How?

_by Kevin Schimd '15_

JavaScript! It's awesome when you want to add interactive, client-side
features to a website. But coding large projects in JavaScript can be
difficult: it's tough to keep track of events, and maintain organization
of the code! Enter in JavaScript frameworks, which are useful in solving
these kinds of issues. In this seminar, we'll dive into the details and
aspects of some frameworks, and discuss what kind of design challenges
they address. Some knowledge of JavaScript, such as events and objects,
is ideal, but not necessary.

* http://cdn.cs50.net/2012/fall/seminars/javascript_frameworks/javascript_frameworks.zip[Source
Code]
* http://cs50.tv/2012/fall/seminars/javascript_frameworks/javascript_frameworks-720p.mp4[Video]


=== Kohana: A Lightweight PHP Framework

_by Brandon Liu '14_

Web frameworks are absolutely essential for making websites: They
organize your code so that it's more maintainable, and they take care of
common problems like user input sanitation and data model validation so
that you don't have to reinvent the wheel every single time. There are
dozens of web frameworks out there, but Kohana is one of the easiest to
learn, while still providing plenty of features. It's written in PHP, so
there's no need to learn a new language! The seminar will be a
live-coding session, building a blog from the ground up using Kohana.
Students are free to code along, but I will be moving quickly to cover
more ground.

* http://cdn.cs50.net/2012/fall/seminars/kohana/kohana.pdf[Slides]
* http://cdn.cs50.net/2012/fall/seminars/kohana/kohana.zip[Source Code]
* http://cs50.tv/2012/fall/seminars/kohana/kohana-720p.mp4[Video]


=== Make an Attractive Website with CSS

_by Ben Shryock '15_

Learn to make websites even sexier than CS50 Finance with the use of
Cascading Style Sheets (CSS). CSS allows precise control over visual
appearance of a page, from overall layout to details such as font and
margins, all from a single style sheet.

* http://cdn.cs50.net/2012/fall/seminars/css/css.pdf[Slides]
* http://cdn.cs50.net/2012/fall/seminars/css/css.zip[Source Code]
* http://cs50.tv/2012/fall/seminars/css/css-720p.mp4[Video]


=== Pattern Matching with Regular Expressions

_by John Mussman '12_

Regular expressions are templates that allow computers to find and match
patterns in text. Pattern matching is useful when analyzing user input
on consumer websites, cleaning experimental data, or mining source texts
for statistical information. This seminar gives students conceptual
strategies for converting patterns into regular expressions; practice
using the Python re library to solve puzzles; and background to use the
many implementations of regular expressions in command-line tools and
languages including Python, Perl, Ruby, Java, C#, PHP, and MYSQL.

* http://cdn.cs50.net/2012/fall/seminars/pattern_matching/pattern_matching.pdf[Slides]
* http://cs50.tv/2012/fall/seminars/pattern_matching/pattern_matching-720p.mp4[Video]


=== Preparing Your Site for the Web

_by Yuechen Zhao '15_

Designing and launching a website today is a more complex than simply
whipping up some HTML and CSS. You must also take additional steps to
ensure that your site is ready for the web, as websites are being viewed
on different browsers and platforms by people all over the world. How
can you be certain that your site will thrive under all conditions?
Topics to be discussed include cross-browser/platform compatibility, web
security, error handling, and performance optimization.

* http://cdn.cs50.net/2012/fall/seminars/preparing_your_site/preparing_your_site.pdf[Slides]
* http://cs50.tv/2012/fall/seminars/preparing_your_site/preparing_your_site-720p.mp4[Video]


=== Surviving the Internet

_by Esmond Kane_

This seminar will be a truncated version of the National Cyber Security
Awareness Month presentations available here: http://hvrd.me/Rx1Se9
During this year, a record number of popular online service providers,
ranging from email, to social media, to cloud file sharing, were
compromised resulting in our data being exposed. Now, more than ever, we
need to be mindful of the need for constant vigilance when it comes to
computer security. To protect yourself from cyber risks, here are some
things you can do: 1. Ensure your computer has been set to automatically
update 2. Enable your computer's operating system firewall 3. Install
antivirus software and ensure it is set to automatically update 4.
Install HTTPS and anti-tracking extensions 5. Only save your passwords
to a password safe, never save passwords to your browser 6. Select a
unique password for each of your accounts, do not use a common password
for all of your accounts 7. Use two-factor authentication for accounts
that offer it, for example, Google, PayPal, Dropbox, Facebook and many
others offer free or low cost two-factor authentication 8. Be suspicious
of opening email you were not expecting, or from someone you do not
know, and never reply to an email asking for your password 9. Consider
encrypting your hard disk using your computer's operating system
encryption program, for example, FileVault or BitLocker 10. Back up your
hard disk; make a local backup AND make an online backup of important
data.

* http://cdn.cs50.net/2012/fall/seminars/surviving_the_internet/surviving_the_internet.pdf[Slides]
* http://cs50.tv/2012/fall/seminars/surviving_the_internet/surviving_the_internet-720p.mp4[Video]


=== Technical Interviews

_by Kenny Yu '14_

This will be a workshop presenting the format of technical interviews,
which are common in the recruiting process for software engineering
roles at many tech companies. I'll be presenting tips and resources on
getting through the interview, as well as walking through hands-on
examples of representative problems you might see in interviews.

* http://cdn.cs50.net/2012/fall/seminars/technical_interviews/technical_interviews.pdf[Slides]
* http://cdn.cs50.net/2012/fall/seminars/technical_interviews/technical_interviews.zip[Source
Code]
* http://cs50.tv/2012/fall/seminars/technical_interviews/technical_interviews-720p.mp4[Video]


=== Unix Shells, Environments

_by Douglas Kline_

Unix shells consist of and depend on environments and other provisions
that differ from those of other operating systems. Unix offers several
different shells which have some things in common with each other. One,
bash, is now becoming available on other operating systems and may
become shell-lingua franca. Understanding the bases of the shells, their
various capabilities, and how they differ from each other can greatly
increase one's capabilities of using Unix and also illustrate the
history and development of the shells and the operating system in
general. Understanding how they differ from shells of other operating
systems can promote understanding of both and forestall confusion and
mistakes. I intend this primarily as a practical seminar as the topic
isn't really theoretical and the broader historical implications have
more to do with the irregular, idiosyncratic origins of Unix rather than
principles of computer science.

* http://cdn.cs50.net/2012/fall/seminars/unix_shells_environments/unix_shells_environments.pdf[Text]
* http://cs50.tv/2012/fall/seminars/unix_shells_environments/unix_shells_environments-720p.mp4[Video]


=== Vim: Speed and Power at your Fingertips

_by Brandon Liu '14_

Vim is one of the most popular text editors used by programmers. It is
generally agreed that Vim allows for faster text editing than any other
application, but there is a misconception that Vim has a extremely steep
learning curve. With the proper instruction and guidance, you'll find
yourself coding in Vim in no time, faster than ever before! This seminar
will start with a showcase of what Vim is capable of, and then break out
into a hands-on workshop where everyone gets their hands dirty with some
Vim practice!

* http://cdn.cs50.net/2012/fall/seminars/vim/vim.pdf[Slides]
* http://bit.ly/SGgrya[Vim exercises]
* http://cs50.tv/2012/fall/seminars/vim/vim-720p.mp4[Video]


=== Web Development: From Idea to Implementation

_by Billy Janitsch '15 and Ben Kuhn '15_

So. You have a great idea for a website. What's next? This seminar will
guide you through the process of web development, from designing a solid
architecture to creating a functional and beautiful user interface.
Topics include project management, planning/prioritizing features,
iterating over designs, and an overview of useful libraries and
frameworks. We'll move quickly, but all familiarity levels are welcome.
We'll be happy to field questions during and after the seminar.

* http://cdn.cs50.net/2012/fall/seminars/web_development/web_development.pdf[Slides]
* http://cs50.tv/2012/fall/seminars/web_development/web_development-720p.mp4[Video]


=== Windows 8 App/Game Development with HTML5

_by Edwin Guarin and Chris Bowen_

Are you thinking about what you want to do for your CS50 final project?
Attend this session to learn how to build a Windows 8 App and/or game in
HTML5. If you decide to use this for your final project, we will help
you publish it in the Windows store (using a free Windows Store
developer account we give you) and provide some technical guidance
during the hackathon. You will also have a chance to win a Windows 8
slate device or XBOX 360! Don’t miss out!

* http://cs50.tv/2012/fall/seminars/windows_8/windows_8-720p.mp4[Video]


== Fall 2011


=== Accelerating Science with the Open Science Grid

by Ian Stokes-Rees

In the mid-1990s, the high-energy physics community (think
http://en.wikipedia.org/wiki/Fermilab[FermiLab] and
http://en.wikipedia.org/wiki/Cern[CERN]) started planning for the
http://en.wikipedia.org/wiki/Large_Hadron_Collider[Large Hadron
Collider]. Managing the http://en.wikipedia.org/wiki/Petabyte[petabytes]
of data that would be generated by the facility and sharing it with the
globally distributed community of over 10,000 researchers would be a
major infrastructure and technology problem. This same community that
brought us the web has now developed standards, software, and
infrastructure for http://en.wikipedia.org/wiki/Grid_computing[grid
computing]. In this seminar I'll present some of the exciting science
that is being done on the
http://en.wikipedia.org/wiki/Open_Science_Grid[Open Science Grid], the
US national
http://en.wikipedia.org/wiki/Cyberinfrastructure[cyberinfrastructure]
linking 60 institutions (Harvard included) into a massive
http://en.wikipedia.org/wiki/Distributed_computing[distributed
computing] and http://en.wikipedia.org/wiki/Data_processing_system[data
processing system].

* http://cdn.cs50.net/2011/fall/seminars/acceleratingScience/acceleratingScience.pdf[Slides]
* http://cs50.tv/2011/fall/seminars/acceleratingScience/acceleratingScience.mp4[Video]


=== Acing Your Technical Interviews

by Tony Ho '14

At Harvard, there aren't many programs that help people practice their
interviews, especially if there is coding involved. To help with this, I
would like to teach people about resources that are out there that can
help with making sure everyone can ace their interviews.

Most coding interviews are like another coding competition. I would like
to start by talking about resources like
http://projecteuler.net/[Project Euler], Poj,
http://en.wikipedia.org/wiki/USACO[USACO],
http://codeforces.com/[Codeforces],
http://en.wikipedia.org/wiki/TopCoder[Topcoder]. Then I will move into
the broad topics that everyone needs to know to answer simple questions.
Finally, I will end with a hands-on period where we will try some
problems and go over some problems that I have personally seen and find
very interesting.

* http://cdn.cs50.net/2011/fall/seminars/acing_technical_interviews/acing_technical_interviews.pdf[Slides]
* http://cdn.cs50.net/2011/fall/seminars/acing_technical_interviews/acing_technical_interviews_src.zip[Source
Code]
* http://cs50.tv/2011/fall/seminars/acing_technical_interviews/acing_technical_interviews.mp4[Video]


=== Android Application Development

by Jordan Jozwiak '14

Learn the basics of the http://code.google.com/android/[Android]
Application Interface and developing
http://en.wikipedia.org/wiki/Java_%28software_platform%29[Java]
applications using
http://en.wikipedia.org/wiki/Eclipse_%28software%29[Eclipse].

* http://cdn.cs50.net/2011/fall/seminars/Android_applicationDevelopment/Android_applicationDevelopment.pdf[Slides]
* http://cs50.tv/2011/fall/seminars/Android_applicationDevelopment/Android_applicationDevelopment.mp4[Video]


=== appLab.Phone(Mango) Session One

by Edwin Guarin of Microsoft

You will learn how to get started on that next great app for the Windows
Phone. Session One will attempt to cover: Introduction to Windows Phone
7.5 for Developers; Building Windows Phone 7.5 Apps with Visual Studio
and Silverlight; Getting Started with Sample Code and other resource;
Publishing and Monetizing your App in the Marketplace at no cost. For
this seminar, install the Windows Phone 7.5 SDK from
http://create.msdn.com/en-us/home/getting_started. And create a free
Dreamspark and AppHub account using the instructions from
http://bit.ly/r2dqFr. This will give you the ability to publish your
phone apps and monetize for free.

* Resources
** http://cdn.cs50.net/2011/fall/seminars/appLab_Phone_Mango/Jump_Start_Windows_Phone_Mango.zip[Jump
Start Windows Phone Mango]
** http://cdn.cs50.net/2011/fall/seminars/appLab_Phone_Mango/Windows_Phone_7_Silverlight_Toolkit_Refresh_Aug_2011.zip[Windows
Phone 7 Silverlight Toolkit Refresh Aug 2011]
** http://cdn.cs50.net/2011/fall/seminars/appLab_Phone_Mango/Windows_Phone_7_Training_Course.zip[Windows
Phone 7 Training Course]
** http://cdn.cs50.net/2011/fall/seminars/appLab_Phone_Mango/Windows_Phone_Training_Labs.zip[Windows
Phone Training Labs]
** http://cdn.cs50.net/2011/fall/seminars/appLab_Phone_Mango/Windows_Phone_Training_Presentations.zip[Windows
Phone Training Presentations]
* http://cs50.tv/2011/fall/seminars/appLab_Phone_Mango/appLab_Phone_Mango.mp4[Video]


=== Beyond Google Maps: Spatial is Special

by Kirk Goldsberry

There's an ongoing http://en.wikipedia.org/wiki/Geospatial[geospatial]
revolution happening right now. Unfortunately, despite the rapid rise of
geospatial technologies, here at Harvard there are few if any courses
that focus on
http://en.wikipedia.org/wiki/Geographic_Information_Science[Geographic
Information Science]. I propose to lead a brief seminar that introduces
the basics of GIScience and hopes to inspire students to generate
exciting new spatially aware mobile applications that pick up where
popular location-based services such as
http://en.wikipedia.org/wiki/Google_maps[Google Maps] and
[http://en.wikipedia.org/wiki/Yelp,_Inc. Yelp] leave off. Since a large
percentage of http://en.wikipedia.org/wiki/Application_software["apps"]
have a spatial component, this topic should be of interest to students
looking to design new
http://en.wikipedia.org/wiki/Mobile_computing[mobile computing]
software.

* http://cs50.tv/2011/fall/seminars/beyond_GoogleMaps/beyond_GoogleMaps.mp4[Video]


=== Building Applications in C#

by Mike Teodorescu '11

This seminar is a concentrated introduction to
http://en.wikipedia.org/wiki/C_Sharp_%28programming_language%29[C#] and
will cover
http://en.wikipedia.org/wiki/Object-oriented_programming[object-oriented
programming] in C#,
http://en.wikipedia.org/wiki/Collection_%28computing%29[collections] in
C#, http://en.wikipedia.org/wiki/Exception_handling[exception handling],
http://en.wikipedia.org/wiki/Regular_expression_examples[regular
expressions], http://en.wikipedia.org/wiki/XML[XML]
http://en.wikipedia.org/wiki/Parsing[parsing],
http://en.wikipedia.org/wiki/C_file_input/output[file I/O], and
http://en.wikipedia.org/wiki/Debugging[debugging] in
http://en.wikipedia.org/wiki/Microsoft_Visual_Studio[Visual Studio]. By
the end of the course, students should have a solid grasp of this
powerful language, which is packed with handy shortcuts and libraries.

* http://cdn.cs50.net/2011/fall/seminars/C_sharp/C_sharp.pdf[Slides]
* http://cdn.cs50.net/2011/fall/seminars/C_sharp/C_sharp_src.zip[Source
Code]
* http://cs50.tv/2011/fall/seminars/C_sharp/C_sharp.mp4[Video]


=== CSS for a Beautiful Website

by Charles Bandes

Proper use of http://en.wikipedia.org/wiki/Cascading_Style_Sheets[CSS]
allows a tremendous degree of control over both the layout and visual
design of a web page. Careful application of
http://en.wikipedia.org/wiki/Style_sheet_%28web_development%29[style
sheets] can be the difference between a basic page and a really polished
site.

* http://cdn.cs50.net/2011/fall/seminars/CSS/CSS_src.zip[Source Code]
* http://cs50.tv/2011/fall/seminars/CSS/CSS.mp4[Video]


=== Develop for the BlackBerry... Like a Boss

by Jason Hirschorn '14 and Marta Bralic '12

Learn how to develop applications for
http://en.wikipedia.org/wiki/BlackBerry[BlackBerry] smartphone. Imagine
integrating the http://en.wikipedia.org/wiki/BlackBerry_Messenger[BBM]
platform into your application or coding the next
http://en.wikipedia.org/wiki/Brick_Breaker[Brick Breaker]. The
possibilities are endless!

* http://cdn.cs50.net/2011/fall/seminars/develop_for_the_BlackBerry/develop_for_the_BlackBerry.pdf[Slides]
* http://cs50.tv/2011/fall/seminars/develop_for_the_BlackBerry/develop_for_the_BlackBerry.mp4[Video]


=== Educational Software

by Katie Vale

Interested in writing software to support teaching and learning? This
session will discuss how to plan and execute an instructional project,
including how to do requirements gathering, how to choose development
platforms, and how to assess your project. The instructor has over 20
years' experience in designing and producing educational software.

* http://cdn.cs50.net/2011/fall/seminars/educationalSoftware/educationalSoftware.pdf[Slides]
* http://cs50.tv/2011/fall/seminars/educationalSoftware/educationalSoftware.mp4[Video]


=== Emacs

by Matthew Chartier '12

http://en.wikipedia.org/wiki/Emacs[Emacs] is an alternative to
http://en.wikipedia.org/wiki/Gedit[gedit] which empowers you to write
code more efficiently.
http://en.wikipedia.org/wiki/Extensible[Extensible] and highly
customizable, Emacs allows users to streamline their editing process by
modifying the editor itself to suit their needs. Topics covered will
include http://en.wikipedia.org/wiki/Keyboard_shortcuts[keyboard
shortcuts] to navigate text files quickly, using
http://en.wikipedia.org/wiki/Data_buffer[buffers] to more effectively
work with code spanning multiple files, and automating repetitive and
tedious editing tasks on the fly.

* http://cdn.cs50.net/2011/fall/seminars/Emacs/Emacs.pdf[Slides]
* http://cs50.tv/2011/fall/seminars/Emacs/Emacs.mp4[Video]


=== From Innovation to Production: Making It Work is Just the Beginning

by Dennis Ravenelle

Thomas Edison is credited with saying that invention is 1 percent
inspiration and 99 percent perspiration. Getting an innovative solution
from the lab (or the garage) into a real production environment can be
an arduous process. But until something delivers real value in a
real-world environment, it's just a novelty. Here are some things to
consider.

* http://cdn.cs50.net/2011/fall/seminars/innovation_to_production/innovation_to_production.pdf[Slides]
* http://cs50.tv/2011/fall/seminars/innovation_to_production/innovation_to_production.mp4[Video]


=== Getting a Job in the Tech Industry

by Matthew Chartier '12 and Melissa Niu '13

A seminar to discuss opportunities available to Harvard students in the
tech industry and details about the interview process. The seminar will
consist of a presentation and Q&A session with a panel of students with
prior experience interviewing for and working in positions in the tech
industry.

* http://cdn.cs50.net/2011/fall/seminars/techIndustry/techIndustry.pdf[Slides]
* http://cs50.tv/2011/fall/seminars/techIndustry/techIndustry.mp4[Video]


=== Getting Started with Node.js

by Beardsley Ruml

An introduction to http://en.wikipedia.org/wiki/Node.js[Node.js], a
http://en.wikipedia.org/wiki/Server-side[server-side]
http://en.wikipedia.org/wiki/Javascript[JavaScript] environment with
http://en.wikipedia.org/wiki/Asynchronous_I/O[non-blocking IO], and its
most popular modules, such as http://expressjs.com/[Express] (built on
Connect) and http://socket.io/[Socket-IO]. The opportunities for
real-time browser-based interactions will be demonstrated with a new
http://en.wikipedia.org/wiki/Open_source[open-source] implementation of
http://backchan.nl/[backchan.nl]. (See
http://www.github.com/bruml2/backchannel/)

* http://cdn.cs50.net/2011/fall/seminars/Node_js/Node_js.pdf[Slides]
* http://cs50.tv/2011/fall/seminars/Node_js/Node_js.mp4[Video]


=== Git Magic: Versioning Files Like a Boss

by Tommy MacWilliam '13

Tired of sudoku_why_is_it_3_am.c and sudoku_OMG_FINALLY_WORKS.c? Learn
how software is developed in the real world with
http://git-scm.com/[git], a distributed revision control system. Track
down bugs faster, manage file histories, and deploy code with efficiency
and confidence.

* http://cdn.cs50.net/2011/fall/seminars/Git_magic/Git_magic.pdf[Slides]
* http://cs50.tv/2011/fall/seminars/Git_magic/Git_magic.mp4[Video]


=== iOS

by Larry Ehrhardt

Quick tour of http://en.wikipedia.org/wiki/IOS[iOS] and how to build a
tab-based http://en.wikipedia.org/wiki/Application_software[app] with a
view, table, and web view.

* http://cdn.cs50.net/2011/fall/seminars/iOS/iOS.pdf[Slides]
* http://cdn.cs50.net/2011/fall/seminars/iOS/iOS_src.zip[Source Code]
* http://cs50.tv/2011/fall/seminars/iOS/iOS.mp4[Video]


=== jQuery: How to Make Your Website Shiny

by Alex Hugon '11

Stolen from http://en.wikipedia.org/wiki/JQuery[jQuery's] site: "jQuery
is a fast and concise JavaScript Library that simplifies
http://en.wikipedia.org/wiki/Html[HTML] document traversing, event
handling, animating, and
http://en.wikipedia.org/wiki/Ajax_%28programming%29[Ajax] interactions
for rapid web development. jQuery is designed to change the way that you
write http://en.wikipedia.org/wiki/Javascript[JavaScript]."

What this means for you is that you can make your websites prettier,
more interactive, and more dynamic than ever. If you're considering
making a website for your final project, you should check jQuery out!

* http://cdn.cs50.net/2011/fall/seminars/jQuery/jQuery_src.zip[Source
Code]
* http://cs50.tv/2011/fall/seminars/jQuery/jQuery.mp4[Video]


=== Ruby on Rails

by Lexi Ross '13

http://en.wikipedia.org/wiki/Ruby_on_Rails[Ruby on Rails] is an exciting
new web development framework that lets you build awesome, dynamic
websites in a short amount of time. Ever used
http://en.wikipedia.org/wiki/Twitter[Twitter] or
http://en.wikipedia.org/wiki/Groupon[Groupon]? Then you've used a Rails
application. The Rails framework utilizes the
http://www.ruby-lang.org/en/[Ruby programming language], so we'll be
learning basic Ruby syntax as well as the tools you need to get started
building a Rails app. Bonus: Ruby is insanely fun to code in!

* http://cdn.cs50.net/2011/fall/seminars/Ruby_on_Rails/ROR.pdf[Slides]
* http://cdn.cs50.net/2011/fall/seminars/Ruby_on_Rails/ROR_depot_src.zip[ROR depot Source Code]
* http://cdn.cs50.net/2011/fall/seminars/Ruby_on_Rails/ROR_finance_skeleton_src.zip[ROR finance skeleton Source Code]
* http://cs50.tv/2011/fall/seminars/Ruby_on_Rails/Ruby_on_Rails.mp4[Video]


=== Search and Browse Superpowers: an Introduction to Solr

by Ben Gaucherin

Search and browse capabilities are core to most applications these days.
This seminar will review basic concepts behind search, including the
more recent development known as
http://en.wikipedia.org/wiki/Faceted_search[faceted search]. We will
then use http://en.wikipedia.org/wiki/Solr[Solr], one of the most
popular http://en.wikipedia.org/wiki/Open_source[open-source] faceted
http://en.wikipedia.org/wiki/Search_engine[search engines], to see how
one can incorporate advanced search and browse capabilities into an
application.

* http://cdn.cs50.net/2011/fall/seminars/intro_to_Solr/intro_to_Solr.pdf[Slides]
* http://cs50.tv/2011/fall/seminars/intro_to_Solr/intro_to_Solr.mp4[Video]
* http://cdn.cs50.net/2011/fall/seminars/intro_to_Solr/intro_to_Solr.ova[Virtual Machine]


=== User Experience (UX) Design

by Julia Mitelman '13

Ever stumbled upon a product that frustrated you because you couldn't
figure out how to use it? Learn how to create products that are
intuitive and convenient—no user manual necessary! A sneak peek of
CS179, this seminar teaches you what you need to keep in mind when
making products so you can create a great best user experience—because
it's always the designer's fault!

* http://cdn.cs50.net/2011/fall/seminars/user_UX_design/user_UX_design.pdf[Slides]
* http://cs50.tv/2011/fall/seminars/user_UX_design/user_UX_design.mp4[Video]


=== Web Security

by Carl Jackson '13

You know how to build websites, but do you know how to make them secure?
We'll teach you about some of the most common Web Security
vulnerabilities and how to fix them.

* http://cdn.cs50.net/2011/fall/seminars/Web_security/Web_security.pdf[Slides]
* http://cdn.cs50.net/2011/fall/seminars/Web_security/Web_security.zip[Source Code]
* http://cs50.tv/2011/fall/seminars/Web_security/Web_security.mp4[Video]


== Fall 2010


=== Beyond Git: Forging SDLC

by Esmond Kane

Given the forthcoming launch of the http://forge.gov/[forge.gov]
http://en.wikipedia.org/wiki/Systems_Development_Life_Cycle[SDLC]
portal, building on the already deployed http://forge.mil/[forge.mil],
collaborative development lifecycle portals are officially mainstream.
The presenter will speak to the goals, quirks, maturation and future of
a 6-year software development hosted portal for academia _et al._ in
Harvard. The Harvard ABCD Forge is available at
https://forge.abcd.harvard.edu/[forge.abcd.harvard.edu].

* http://cdn.cs50.net/2010/fall/seminars/BeyondGit_ForgingSDLC/BeyondGit_ForgingSDLC.pdf[Slides]
* http://cs50.tv/2010/fall/seminars/BeyondGit_ForgingSDLC/BeyondGit_ForgingSDLC.mp4[Video]


=== BlackBerry Application Development

by Tian Feng '11

Learn the basics of the http://en.wikipedia.org/wiki/BlackBerry[BlackBerry] Application
Interface and developing http://en.wikipedia.org/wiki/Java_(programming_language)[Java]
applications.

* http://cdn.cs50.net/2010/fall/seminars/BlackBerryApplicationDevelopment/BlackBerryApplicationDevelopment.pdf[Slides]
* http://cs50.tv/2010/fall/seminars/BlackBerryApplicationDevelopment/BlackBerryApplicationDevelopment.mp4[Video]


=== Crash Course in Java

by Matthew Chartier '12

Comprehensive introduction to the syntax, features, advantages, and limitations of the
http://en.wikipedia.org/wiki/Java_(programming_language)[Java]
programming language, relating back to
http://en.wikipedia.org/wiki/C_(programming_language)[C]. Introducing
basic topics in http://en.wikipedia.org/wiki/Object-oriented_programming[object-oriented programming].

* http://cdn.cs50.net/2010/fall/seminars/CrashCourseInJava/CrashCourseInJava.pdf[Slides]
* http://cdn.cs50.net/2010/fall/seminars/CrashCourseInJava/CrashCourseInJava.zip[Source Code]
* http://cs50.tv/2010/fall/seminars/CrashCourseInJava/CrashCourseInJava.mp4[Video]


=== Creating Awesome Websites with Ruby on Rails

by Tommy MacWilliam '13

http://en.wikipedia.org/wiki/Ruby_on_Rails[Ruby on Rails] is a web
application framework for the
http://en.wikipedia.org/wiki/Ruby_(programming_language)[Ruby]
programming language. With Rails, interacting with complex database
structures is a snap and site organization is literally done for you,
allowing you to focus on creating an awesome website rather than
worrying about petty low-level details. In this seminar, we'll take a
look at the Ruby programming language, the
http://en.wikipedia.org/wiki/Model–View–Controller[MVC] design pattern,
and how to create and deploy a killer Rails website in minutes (that's
right, minutes).

* http://cdn.cs50.net/2010/fall/seminars/CreatingAwesomeWebsitesWithRubyOnRails/CreatingAwesomeWebsitesWithRubyOnRails.pdf[Slides]
* http://cs50.tv/2010/fall/seminars/CreatingAwesomeWebsitesWithRubyOnRails/CreatingAwesomeWebsitesWithRubyOnRails.mp4[Video]


=== Data Visualization and Graphics with Processing

by Mike Teodorescu '11

Used in visualizing the human genome, social networks, word maps of
presidential speeches,
http://en.wikipedia.org/wiki/Processing_(programming_language)[Processing]
provides a complete framework for interactive visual applications. The
seminar is structured as a tutorial to enable you to get started quickly
with the
http://en.wikipedia.org/wiki/Java_(programming_language)[Java]-based
Processing and off to a final project! A survey of visual applications
using Processing will be made to give you more implementation ideas for
your project.

* http://cdn.cs50.net/2010/fall/seminars/DataVisualizationAndGraphicsWithProcessing/DataVisualizationAndGraphicsWithProcessing.pdf[Slides]
* http://cdn.cs50.net/2010/fall/seminars/DataVisualizationAndGraphicsWithProcessing/DataVisualizationAndGraphicsWithProcessing.zip[Source Code]
* http://cs50.tv/2010/fall/seminars/DataVisualizationAndGraphicsWithProcessing/DataVisualizationAndGraphicsWithProcessing.mp4[Video]


=== Developing Apps for iOS: iPhone, iPad, and iPod Touch

by Scott Crouch '13

In this seminar, students will learn the fundamentals of
http://en.wikipedia.org/wiki/Objective-C[Objective-C],
http://en.wikipedia.org/wiki/Xcode[Xcode], the iPhone and iPad
simulator, http://en.wikipedia.org/wiki/Interface_Builder[Interface
Builder] and Instruments. Topics in Objective-C include the
http://en.wikipedia.org/wiki/Model–View–Controller[model-view-controller]
paradigm, basic syntax, memory management, Core Data, and UI elements.
Students will learn the basics of creating simple, table, tab bar and
split view controller applications.

* http://cdn.cs50.net/2010/fall/seminars/DevelopingAppsFor_iOS_iPhone_iPad_And_iPodTouch/DevelopingAppsFor_iOS_iPhone_iPad_And_iPodTouch.pdf[Slides]
* http://cdn.cs50.net/2010/fall/seminars/DevelopingAppsFor_iOS_iPhone_iPad_And_iPodTouch/CS50_Practice_iOS_App.zip[Source Code], _should be run on Simulator 4.2 Debug with LLVM Compiler 1.6_
* http://cs50.tv/2010/fall/seminars/DevelopingAppsFor_iOS_iPhone_iPad_And_iPodTouch/DevelopingAppsFor_iOS_iPhone_iPad_And_iPodTouch.mp4[Video]


=== Educational Software Development

by Katie Vale

Interested in writing software to support teaching and learning? This
session will discuss how to plan and execute an instructional project,
including how to do requirements gathering, how to choose development
platforms, and how to assess your project. The instructor has over 20
years experience in designing and producing educational software.

* http://cs50.tv/2010/fall/seminars/EducationalSoftwareDevelopment/EducationalSoftwareDevelopment.mp4[Video]


=== Linux Demystified

by Jeremy Cushman '12

Come learn about arguably the most successful collective action effort
in the history of the world. Dive into the tool used by the pros and
learn what it takes. Bring along your laptop so you can play along.

* http://cdn.cs50.net/2010/fall/seminars/LinuxDemystified/LinuxDemystified.pdf[Slides]
* http://cs50.tv/2010/fall/seminars/LinuxDemystified/LinuxDemystified.mp4[Video]


=== Modern Client-Side Web Programming

by Filip Zembowicz '11

Recent developments in the http://en.wikipedia.org/wiki/HTML5[HTML5] and
http://en.wikipedia.org/wiki/Cascading_Style_Sheets[CSS] specifications
as well as powerful http://en.wikipedia.org/wiki/JavaScript[JavaScript]
libraries like http://en.wikipedia.org/wiki/JQuery[jQuery] have extended
the realm of possibilities of what can be displayed in a browser. This
seminar will be a high-level overview of the new possibilities, such as
embedding video directly, using a canvas to draw arbitrary objects,
dynamically storing data in the browser using localStorage, and
animating and transforming your webpages to your heart's content.

* http://cs50.tv/2010/fall/seminars/ModernClient-SideWebProgramming/ModernClient-SideWebProgramming.mp4[Video]


=== Search Engine Optimization (SEO)

by Katie Fifer '08

Ever wondered how Google picks certain websites to show up before others
in search results? Ever wondered how much traffic (and money) is at
stake when it comes to being number 1 on Google? Come learn how to
optimize your website to make it more search-engine-friendly and boost
your search engine ranking. We'll cover everything from html tags, to
URLs, links, keyword strategy, and overall content.

* http://cdn.cs50.net/2010/fall/seminars/SearchEngineOptimization_SEO/SearchEngineOptimization_SEO.pdf[Slides]
* http://cs50.tv/2010/fall/seminars/SearchEngineOptimization_SEO/SearchEngineOptimization_SEO.mp4[Video]


=== SMS 101: Mobile Applications for ALL Types of Phones

by Jeff Solnet '12 and Punit Shah '12

This seminar will cover the basics of developing
http://en.wikipedia.org/wiki/SMS[SMS]-based mobile applications. We will
discuss and demonstrate how to use the
http://www.zeepmobile.com/developers/[Zeep Mobile] and
http://lite.textmarks.com/dev/[TextMarks Lite] APIs, in conjunction with
http://en.wikipedia.org/wiki/PHP[PHP] scripts, to develop interactive
SMS applications. SMS (i.e. text messages) is a nearly-universal
technology on cell phones. It allows developers to create mobile
applications that are cheap and compatible with all phones, whether
you're using a smartphone (iPhone, Blackberry, G1) or your parents' old
black-and-white Nokia. If you're thinking about changing the world, SMS
has been a useful platform for the developing world where few serviced
populations have access to advanced mobile devices. Farmers in many
African countries are now able to get up-to-date pricing and other
agricultural data thanks to SMS applications. In Kenya, mobile (SMS)
banking is rapidly changing the way Kenyans create and conduct business.
Whether you're interested in updating
http://shuttleboy.cs50.net/[Shuttleboy] or solving world peace, this
seminar will be a good starting point.

* http://cdn.cs50.net/2010/fall/seminars/SMS101_MobileApplicationsForAllTypesOfPhones/SMS101_MobileApplicationsForAllTypesOfPhones.pdf[Slides]
* http://cs50.tv/2010/fall/seminars/SMS101_MobileApplicationsForAllTypesOfPhones/SMS101_MobileApplicationsForAllTypesOfPhones.mp4[Video]


=== Socialize Your Apps with Facebook Platform

by Keito Uchiyama '11

How to get started with http://developers.facebook.com/[Facebook's
Platform product], including use of the
http://developers.facebook.com/docs/api[Graph API] and how to use the
http://github.com/facebook/php-sdk/[SDKs in PHP]. An overview of the
features in the API and examples of possible integrations.

* http://cdn.cs50.net/2010/fall/seminars/SocializeYourAppsWithFacebookPlatform/SocializeYourAppsWithFacebookPlatform.pdf[Slides]
* http://cdn.cs50.net/2010/fall/seminars/SocializeYourAppsWithFacebookPlatform/SocializeYourAppsWithFacebookPlatform.zip[Source Code]
* http://cs50.tv/2010/fall/seminars/SocializeYourAppsWithFacebookPlatform/SocializeYourAppsWithFacebookPlatform.mp4[Video]


=== Vim

by Gabrielle Ehrlich '13

Learn how to use http://en.wikipedia.org/wiki/Vim_(text_editor)[Vim], a
text editor. It's awesome.

* http://cs50.tv/2010/fall/seminars/Vim/Vim.mp4[Video]


== Fall 2009


=== Amazon EC2

by David J. Malan '99

Overview of http://aws.amazon.com/ec2/[Amazon EC2]. How We've Used It.
What It Costs. Q&A.

* https://manual.cs50.net/Amazon_EC2[Outline]
* Video
** http://cdn.cs50.net/2009/fall/seminars/EC2_seminar.flv?play[Flash]
** http://cdn.cs50.net/2009/fall/seminars/EC2_seminar.mp3?download[MP3]
** http://cdn.cs50.net/2009/fall/seminars/EC2_seminar.mov?download[QuickTime]


=== Android Apps with App Inventor

by Alex Hugon '11 and Filip Zembowicz '11

http://sites.google.com/site/appinventorhelp/[App Inventor for Android]
is a http://scratch.mit.edu/[Scratch]-like environment that lets you
create new mobile applications. With it, you can explore communication,
location-awareness, social networking, and massive Web-based data
collections. This is a great way to try out mobile apps, and to
collaborate with a community of developers at Google and other colleges
participating in the App Inventor alpha.

* http://cdn.cs50.net/2009/fall/seminars/AndroidAppsWithAppInventor.flv?play[Flash]
* http://cdn.cs50.net/2009/fall/seminars/AndroidAppsWithAppInventor.mp3?download[MP3]
* http://cdn.cs50.net/2009/fall/seminars/AndroidAppsWithAppInventor.mov?download[QuickTime]


=== Android Apps with Java

by Kent Rakip '11

http://code.google.com/android/[Android] is a software stack for mobile
devices that includes an operating system, middleware and key
applications. The Android SDK provides the tools and APIs necessary to
begin developing applications that run on Android-powered devices.

* http://cdn.cs50.net/2009/fall/seminars/AndroidAppswithJava.pdf[Slides]
* Video
** http://cdn.cs50.net/2009/fall/seminars/AndroidAppsWithJava.flv?play[Flash]
** http://cdn.cs50.net/2009/fall/seminars/AndroidAppsWithJava.mp3?download[MP3]
** http://cdn.cs50.net/2009/fall/seminars/AndroidAppsWithJava.mov?download[QuickTime]


=== Beginning iPhone Development: Resources, Tips & Tricks

by Winston Yan '10 and Jonathan Yip '12

Interested in developing an app for the iPhone or iPod touch? This
seminar aims to not only be a tutorial on beginning iPhone development,
but will also 1) introduce a number of resources we've found useful
during the development of Rover and 2) provide you with a number of
tips, tricks, and customizations that we've learned through trial and
error. Hopefully from our experience, we can make your life a lot
easier!

* http://cdn.cs50.net/2009/fall/seminars/Beginning_iPhoneDevelopment.flv?play[Flash]
* http://cdn.cs50.net/2009/fall/seminars/Beginning_iPhoneDevelopment.mp3?download[MP3]
* http://cdn.cs50.net/2009/fall/seminars/Beginning_iPhoneDevelopment.mov?download[QuickTime]


=== Building Social Applications with the Facebook Platform

by Keito Uchiyama '11

When you "SuperPoke" someone on Facebook or play "Farmville", you're
using applications built on the http://developers.facebook.com/[Facebook
Platform], an extensive infrastructure designed to make it easy for
developers to leverage the social graph of the world's largest social
networking website. Now that the Facebook Platform is available outside
facebook.com as Facebook Connect and in many other languages beyond PHP,
an increasingly large number of notable websites are using the Platform
to add the social element to their websites and other applications.
Learn how to create such an application yourself and join the social
web.

* http://cdn.cs50.net/2009/fall/seminars/BuildingSocialApplicationsWithFacebookPlatform.flv?play[Flash]
* http://cdn.cs50.net/2009/fall/seminars/BuildingSocialApplicationsWithFacebookPlatform.mp3?download[MP3]
* http://cdn.cs50.net/2009/fall/seminars/BuildingSocialApplicationsWithFacebookPlatform.mov?download[QuickTime]


=== Dynamic Websites on Rails

by Greg Brockman

Ruby on Rails is a framework for building web applications that makes
complicated tasks easy, fast, and fun. By taking care of low-level
details such as talking to your database as if it were an object, Rails
frees you to deal with the interesting parts that make your site unique
to you. In this talk, we'll go through some of the basic concepts of
Rails, ultimately building a dynamic application in mere minutes. Give
in to peer pressure and join sites like Hulu, Twitter, and Jobster in
riding the Rails.

* http://cdn.cs50.net/2009/fall/seminars/DynamicWebsitesOnRails.flv?play[Flash]
* http://cdn.cs50.net/2009/fall/seminars/DynamicWebsitesOnRails.mp3?download[MP3]
* http://cdn.cs50.net/2009/fall/seminars/DynamicWebsitesOnRails.mov?download[QuickTime]


=== Hadoop for Large-Scale Computation

by Zak Stone '04

Welcome to the era of Big Data, in which petabytes of information are
accumulating at an accelerating rate and desperately need you to analyze
them. Computation on billions of web pages or photos or log entries
requires new tools and a new way of thinking about programming; this
seminar will introduce you to http://hadoop.apache.org/[Hadoop], the
most prominent open-source ecosystem of tools for working with exciting
new large-scale datasets.

* http://cdn.cs50.net/2009/fall/seminars/Hadoop.flv?play[Flash]
* http://cdn.cs50.net/2009/fall/seminars/Hadoop.mp3?download[MP3]
* http://cdn.cs50.net/2009/fall/seminars/Hadoop.mov?download[QuickTime]


=== Interactive Data Applications

by Mike Tucker '03

Build an interactive, data-driven application using
http://www.endeca.com/[Endeca]'s commercial-grade data tools with
http://en.wikipedia.org/wiki/XQuery[XQuery], a standards-based
programming language tuned to working with
http://en.wikipedia.org/wiki/Xml[XML].

Endeca provides a platform for search applications that allows users to
navigate through data based on record attributes. This means that you
can take any dataset that you have in mind and open it up to the world
with the type of high quality text search and faceted navigation that
you find on the top e-commerce and media sites including
http://HomeDepot.com[HomeDepot.com], http://NewEgg.com[NewEgg.com],
http://NewsSift.com[NewsSift.com] and http://Time.com[Time.com].

Endeca provides access to these features and more through APIs that are
exposed in a standard query language for XML databases called XQuery, in
which you can write arbitrarily complex programs. These programs can
then be hosted in your Endeca application as web-services, meaning that
they can be invoked from your
http://en.wikipedia.org/wiki/Ajax_(programming)[Ajax] or
http://www.adobe.com/products/flex/[Flex]-based User Interface.

* http://cdn.cs50.net/2009/fall/seminars/InteractiveDataApplications.flv?play[Flash]
* http://cdn.cs50.net/2009/fall/seminars/InteractiveDataApplications.mp3?download[MP3]
* http://cdn.cs50.net/2009/fall/seminars/InteractiveDataApplications.mov?download[QuickTime]


=== Scraping Data from the Internet

by Keito Uchiyama '11

Stocks, sports scores, dining menus--there's a plethora of information
out there on the Internet that's not available by easily accessible
http://en.wikipedia.org/wiki/Application_programming_interface[Application
Programming Interfaces] (APIs).
http://en.wikipedia.org/wiki/Web_scraping[Web scraping], or screen
scraping in general, helps extract that data by parsing the HTML on web
pages, making data from any website on the Internet accessible to your
application and prime for mashing up in whatever creative way you can
imagine. We'll go over an example,
http://CrimsonDining.org/[CrimsonDining.org], which uses robust scraping
to retrieve menu data from Dining Services. The techniques covered in
this seminar will apply to any programming language or framework.

* http://cdn.cs50.net/2009/fall/seminars/ScrapingDataFromInternet.zip[Source Code]
* Video
** http://cdn.cs50.net/2009/fall/seminars/ScrapingDataFromInternet.flv?play[Flash]
** http://cdn.cs50.net/2009/fall/seminars/ScrapingDataFromInternet.mp3?download[MP3]
** http://cdn.cs50.net/2009/fall/seminars/ScrapingDataFromInternet.mov?download[QuickTime]


=== Visualizing Data and Data Art with Processing

by Filip Zembowicz '11

http://www.processing.org[Processing] is an open-source programming
language based on Java and designed with visualization in mind. It is
for students, artists, designers, researchers, and hobbyists for
learning, prototyping, and production of graphics, both static and
interactive. It is used intensively in the class CS 171: Visualization,
taught by Hanspeter Pfister. This tutorial will cover basic processing
fundamentals, including loading data, drawing complex shapes from
primitives, physics, and handling user interaction. These programs can
then be run online or through downloadable executables.

* http://cdn.cs50.net/2009/fall/seminars/VisualizingData_DataArtWithProcessing.flv?play[Flash]
* http://cdn.cs50.net/2009/fall/seminars/VisualizingData_DataArtWithProcessing.mp3?download[MP3]
* http://cdn.cs50.net/2009/fall/seminars/VisualizingData_DataArtWithProcessing.mov?download[QuickTime]


=== Visualizing Data Interactively: A Primer on Actionscript, Flex, and the Flare Visualization Library

by Filip Zembowicz '11

Large datasets are everywhere nowadays: information on populations,
biology, voting, prices, and distances are just a few of the various
categories of data easily accessible online. However, many of these
resources suffer from poor user interface design--it is hard for a user
to see the information holistically, to see patterns in data, to observe
how the data changes over time, and to remain engaged with static blocks
of text and images. Information visualization allows for the facile
design of engaging ways to explore data. In this tutorial, I will
introduce Actionscript (the language that powers Flash animations) and
http://www.adobe.com/products/flex/[Flex] (an Adobe product that allows
rapid development of web-based flash apps), specifically focusing on how
the http://flare.prefuse.org/[Flare] visualization library can be
utilized to load, display, and interact with quantitative, qualitative,
and relative data. Examples of beautiful visualizations:
http://www.visualcomplexity.com/vc/.

Adobe has recently announced that the forthcoming Flash CS5 will be able
to run on iPhone -- this represents a tremendous opportunity for getting
into the mobile wave.

* http://cdn.cs50.net/2009/fall/seminars/VisualizingDataInteractively.flv?play[Flash]
* http://cdn.cs50.net/2009/fall/seminars/VisualizingDataInteractively.mp3?download[MP3]
* http://cdn.cs50.net/2009/fall/seminars/VisualizingDataInteractively.mov?download[QuickTime]


=== Voice Application Development

by Wellie Chao '98

Provide information and services to users over the phone using speech
synthesis,
http://en.wikipedia.org/wiki/Dual-tone_multi-frequency[dual-tone
multi-frequency] (DTMF) capture, and
http://en.wikipedia.org/wiki/Public_switched_telephone_network[public
switched telephone network] (PSTN) connectivity. Build voice telephony
applications using scripting languages such as Perl and Python
configured with XML. http://en.wikipedia.org/wiki/FreeSWITCH[FreeSWITCH]
is a
http://en.wikipedia.org/wiki/Session_Initiation_Protocol[SIP]-compliant
softswitch that lets you talk to other softswitches, softphones, IP
phones, and (via SIP) the PSTN to reach (or be reached by) any mobile
phone or landline around the world. The CS50
http://shuttleboy.cs50.net[Shuttleboy Voice] application (617-BUG-CS50 /
617-284-2750) is built on FreeSWITCH. Organizations such as
http://www.delta.com/[Delta Airlines],
http://www.capitalone.com/[Capital One],
http://www.citibank.com/[Citibank], and even
http://www.harvard.edu/[Harvard] use
http://en.wikipedia.org/wiki/Interactive_voice_response[interactive
voice response] (IVR) systems to provide information to customers such
as flight times, bank balances, and dinner menus, and to allow customers
to perform transactions such as booking tickets, transferring money,
making payments. With FreeSWITCH and your favorite programming language
(C/Java/Perl/Python/PHP/Javascript/Ruby/etc.), building such systems is
a snap. In addition, FreeSWITCH has some cool features such as receiving
faxes, sending dynamically generated faxes, integration with
http://www.google.com/talk/[Google Talk], mixing of audio streams from
multiple sources such as other phone lines for conferencing or local
files/shoutcast.

* http://cdn.cs50.net/2009/fall/seminars/VoiceApplicationDevelopment.flv?play[Flash]
* http://cdn.cs50.net/2009/fall/seminars/VoiceApplicationDevelopment.mp3?download[MP3]
* http://cdn.cs50.net/2009/fall/seminars/VoiceApplicationDevelopment.mov?download[QuickTime]


== Fall 2008


=== Accepting Payments with Google Checkout

by Mike Tucker '03

* http://cdn.cs50.net/2008/fall/seminars/GoogleCheckout.flv?play[Flash]
* http://cdn.cs50.net/2008/fall/seminars/GoogleCheckout.mp3?download[MP3]
* http://cdn.cs50.net/2008/fall/seminars/GoogleCheckout.mov?download[QuickTime]


=== Advanced Ajax and JavaScript

by Josh Bolduc '11

* http://cdn.cs50.net/2008/fall/seminars/AdvAjax_JS/jquery/[Code]
* http://cdn.cs50.net/2008/fall/seminars/AdvAjax_JS/jquery.pdf[Slides]
* Video
** http://cdn.cs50.net/2008/fall/seminars/AdvAjax_JS.flv?play[Flash]
** http://cdn.cs50.net/2008/fall/seminars/AdvAjax_JS.mp3?download[MP3]
** http://cdn.cs50.net/2008/fall/seminars/AdvAjax_JS.mov?download[QuickTime]


=== Android

by Brett Thomas '10

* http://cdn.cs50.net/2008/fall/seminars/Android.flv?play[Flash]
* http://cdn.cs50.net/2008/fall/seminars/Android.mp3?download[MP3]
* http://cdn.cs50.net/2008/fall/seminars/Android.mov?download[QuickTime]


=== ASP.NET

by Patrick Schmid

* http://cdn.cs50.net/2008/fall/seminars/ASP_NET.flv?play[Flash]
* http://cdn.cs50.net/2008/fall/seminars/ASP_NET.mp3?download[MP3]
* http://cdn.cs50.net/2008/fall/seminars/ASP_NET.mov?download[QuickTime]


=== BlackBerry Apps

by Brett Thomas '10

* http://cdn.cs50.net/2008/fall/seminars/BB_Apps.flv?play[Flash]
* http://cdn.cs50.net/2008/fall/seminars/BB_Apps.mp3?download[MP3]
* http://cdn.cs50.net/2008/fall/seminars/BB_Apps.mov?download[QuickTime]


=== Django

by Andy Lei '09

* http://cdn.cs50.net/2008/fall/seminars/Django/django.code.tar.bz2[Code]
* http://cdn.cs50.net/2008/fall/seminars/Django/django.outline.pdf[Outline]
* Video
** http://cdn.cs50.net/2008/fall/seminars/Django.flv?play[Flash]
** http://cdn.cs50.net/2008/fall/seminars/Django.mp3?download[MP3]
** http://cdn.cs50.net/2008/fall/seminars/Django.mov?download[QuickTime]


=== Facebook Apps

by Linfeng Yang '11

* http://cdn.cs50.net/2008/fall/seminars/FacebookApps/Facebook%20App%20Seminar.pdf[Slides]
* Video
** http://cdn.cs50.net/2008/fall/seminars/FacebookApps.flv?play[Flash]
** http://cdn.cs50.net/2008/fall/seminars/FacebookApps.mp3?download[MP3]
** http://cdn.cs50.net/2008/fall/seminars/FacebookApps.mov?download[QuickTime]


=== Firefox Add-Ons

by Brett Thomas '10

* http://cdn.cs50.net/2008/fall/seminars/FirefoxAddOns.flv?play[Flash]
* http://cdn.cs50.net/2008/fall/seminars/FirefoxAddOns.mp3?download[MP3]
* http://cdn.cs50.net/2008/fall/seminars/FirefoxAddOns.mov?download[QuickTime]


=== iPhone Apps

by Vivek Sant '11

* http://cdn.cs50.net/2008/fall/seminars/iPhoneApps/HelloWorld.zip[Hello World]
* http://cdn.cs50.net/2008/fall/seminars/iPhoneApps/iCalculator.zip[iCalculator]
* http://cdn.cs50.net/2008/fall/seminars/iPhoneApps/iPhone_Dev_Seminar_Slides.pdf[Slides]
* Video
** http://cdn.cs50.net/2008/fall/seminars/iPhoneApps.flv?play[Flash]
** http://cdn.cs50.net/2008/fall/seminars/iPhoneApps.mp3?download[MP3]
** http://cdn.cs50.net/2008/fall/seminars/iPhoneApps.mov?download[QuickTime]


=== Java 3D

by Sanjay Gandhi '10

* http://cdn.cs50.net/2008/fall/seminars/Java3D.flv?play[Flash]
* http://cdn.cs50.net/2008/fall/seminars/Java3D.mp3?download[MP3]
* http://cdn.cs50.net/2008/fall/seminars/Java3D.mov?download[QuickTime]


=== Java Swing/AWT

by David Wu '11

* http://cdn.cs50.net/2008/fall/seminars/JavaSwingAWT.flv?play[Flash]
* http://cdn.cs50.net/2008/fall/seminars/JavaSwingAWT.mp3?download[MP3]
* http://cdn.cs50.net/2008/fall/seminars/JavaSwingAWT.mov?download[QuickTime]


=== Real-world PHP

by Keito Uchiyama '11

* http://cdn.cs50.net/2008/fall/seminars/RealWorldPHP/RealWorldPHP.pdf[Slides]
* Video
** http://cdn.cs50.net/2008/fall/seminars/RealWorldPHP.flv?play[Flash]
** http://cdn.cs50.net/2008/fall/seminars/RealWorldPHP.mp3?download[MP3]
** http://cdn.cs50.net/2008/fall/seminars/RealWorldPHP.mov?download[QuickTime]


=== Ruby on Rails

by Aaron Oehlschlaeger '11 and Linfeng Yang '11

* http://cdn.cs50.net/2008/fall/seminars/RubyOnRails.flv?play[Flash]
* http://cdn.cs50.net/2008/fall/seminars/RubyOnRails.mp3?download[MP3]
* http://cdn.cs50.net/2008/fall/seminars/RubyOnRails.mov?download[QuickTime]


== Fall 2007


=== C++/Object Oriented Programming

by Thomas Carriero '08

* http://cdn.cs50.net/2007/fall/seminars/seminar_OOP.flv?play[Flash]
* http://cdn.cs50.net/2007/fall/seminars/seminar_OOP.mp3?download[MP3]
* http://cdn.cs50.net/2007/fall/seminars/seminar_OOP.mov?download[QuickTime]


=== Choosing the Right Languages/Libraries

by Kelly Heffner and Paul Govereau

* http://cdn.cs50.net/2007/fall/seminars/seminar_LL.flv?play[Flash]
* http://cdn.cs50.net/2007/fall/seminars/seminar_LL.mp3?download[MP3]
* http://cdn.cs50.net/2007/fall/seminars/seminar_LL.mov?download[QuickTime]


=== Event-Driven Programming

by Kelly Heffner

* http://cdn.cs50.net/2007/fall/seminars/seminar_EDP.flv?play[Flash]
* http://cdn.cs50.net/2007/fall/seminars/seminar_EDP.mp3?download[MP3]
* http://cdn.cs50.net/2007/fall/seminars/seminar_EDP.mov?download[QuickTime]


[[How_to_Write_SMS-Based_Programs]]
=== How to Write SMS-Based Programs

by Chris Power

* http://cdn.cs50.net/2007/fall/seminars/seminar_SMS.flv?play[Flash]
* http://cdn.cs50.net/2007/fall/seminars/seminar_SMS.mp3?download[MP3]
* http://cdn.cs50.net/2007/fall/seminars/seminar_SMS.mov?download[QuickTime]


=== Intro to Ruby on Rails

by Kevin Bombino '08

_Warning: Rails has changed significantly since this seminar._

* http://cdn.cs50.net/2007/fall/seminars/seminar_ROR.flv?play[Flash]
* http://cdn.cs50.net/2007/fall/seminars/seminar_ROR.mp3?download[MP3]
* http://cdn.cs50.net/2007/fall/seminars/seminar_ROR.mov?download[QuickTime]


=== Network Programming

by Paul Govereau

* http://cdn.cs50.net/2007/fall/seminars/seminar_NP.flv?play[Flash]
* http://cdn.cs50.net/2007/fall/seminars/seminar_NP.mp3?download[MP3]
* http://cdn.cs50.net/2007/fall/seminars/seminar_NP.mov?download[QuickTime]


=== OpenGL (Graphics Library)

by Paul Govereau

* http://cdn.cs50.net/2007/fall/seminars/seminar_OpenGL.flv?play[Flash]
* http://cdn.cs50.net/2007/fall/seminars/seminar_OpenGL.mp3?download[MP3]
* http://cdn.cs50.net/2007/fall/seminars/seminar_OpenGL.mov?download[QuickTime]


=== SDL (Graphics Library)

by Thomas Carriero

* http://cdn.cs50.net/2007/fall/seminars/seminar_SDL.flv?play[Flash]
* http://cdn.cs50.net/2007/fall/seminars/seminar_SDL.mp3?download[MP3]
* http://cdn.cs50.net/2007/fall/seminars/seminar_SDL.mov?download[QuickTime]

