// enable self-linked titles
:sectlinks:

= CS50x FAQs

Here are answers to some frequently asked questions (FAQs). For answers to other questions, do just strike up a https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/[discussion] with classmates!

[[can-i-use-cs50-ide-offline]]
== Can I use CS50 IDE offline?

Yes, if you have particularly slow, expensive, or infrequent Internet access, see https://manual.cs50.net/cs50-ide/offline.html[CS50 IDE Offline] for details on how you can run your own copy of CS50 IDE locally on your own computer.

'''

[[does-cs50x-have-a-test-or-quiz]]
== Does CS50x have a test or quiz?

Nope! CS50 at Harvard University and Yale University does have a test and quiz, but CS50x does not.

'''

[[does-cs50x-have-office-hours]]
== Does CS50x have office hours?

No, afraid CS50x is too large, but you can still start a https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/[discussion] with classmates!

'''

[[does-cs50x-have-sections]]
== Does CS50x have sections?

No, afraid CS50x is too large, but you can still start a https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/[discussion] with classmates!

'''

[[difference-between-less-comfortable-and-more-comfortable-problems]]
== What's the difference between "less comfortable" and "more comfortable" problems? Do I have to do both?

The "less comfortable" are what you might consider the "standard" version of the problem, designed for students who have little or no prior experience. The "more comfortable" are the "challenge" version, designed for students who consider themselves more comfortable due to prior study/experience before this class.  As such, they may require more concepts than have been covered in the course so far.  

You don't get any extra points for doing the "more comfortable" problems. If you submit both, the one with the highest grade will count towards your overall pset grade.

'''


[[do-I-have-to-choose-verification-before-starting-the-course]]
== Do I have to choose Verification before starting the course?
Nope!  If you would like an edX Verified Certificate, you can pay for verification at any point during the year, even after completing all of the coursework.

'''

[[if-i-paid-for-a-verified-certificate-before-2017-do-i-need-to-pay-again]]
== If I paid for a verified certificate before 2017, do I need to pay again?

No, you should be able to re-verify yourself via edX's https://courses.edx.org/dashboard[dashboard].

'''

[[if-i-started-cs50x-before-2017-can-i-resume]]
== If I started CS50x before 2017, can I resume?

Yes, any scores you received on past years' problem sets will (soon) be imported into CS50x 2017. (We're still updating CS50x 2017's gradebook.) However, moving forward, you must submit CS50x 2017's problem sets, per the https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/dfface6ffc1c43e6882a245c945f7feb/[syllabus].

'''

[[is-my-child-too-young-to-take-cs50x]]
== Is my child too young to take CS50x?

CS50x is perhaps best suited for ages 12 and up. Younger students might need a hand from a parent.

'''

[[how-to-import-scores-from-previous-years-into-cs50-me-gradebook]]
== How to import scores from previous years into CS50.me/gradebook?

To import scores from previous years, head to https://cs50.me/account[CS50.me/account], and link your edX account under *Connected Accounts*.

'''

[[when-are-verified-certificates-generated]]
== When are Verified Certificates generated?

At the end of each month, CS50's staff provides edX with a list of students who have satisfied CS50x's requirements (by receiving scores of at least 70% on every one of the course's nine problem sets as well as on the final project). Within a few days, edX then generates students' Verified Certificates, at which point they should appear automatically on edX's https://courses.edx.org/dashboard[dashboard].

'''

[[when-are-deadlines]]
== When are deadlines?

CS50x does not have deadlines for problem sets or for the final project. You are welcome to work on and submit at your own pace.

'''

[[email-or-password-incorrect]]
== I registered for edX using my Facebook, Google, or Microsoft account, and can't log in to submit Problem Set 0.  What should I do?

Unfortunately, edX's open ID (which we use for authentication) doesn't support logging in with Facebook, Google, or Microsoft accounts yet. To get around this, for now, you should try resetting your password (even though you may have never set any before) from your https://courses.edx.org/account/settings[Account Settings] page on edX.  Then try the pset0 form again, logging in with the email associated with your Facebook, Google, or Microsoft account you use to log into edX, and the password you just set.

'''

[[why-is-pset0-not-graded-yet]]
== Why is pset0 not graded yet?

If it's been a while since you submitted Problem Set 0, but you're still not seeing a grade for it in https://cs50.me/[CS50.me], be sure you've linked your edX account at https://cs50.me/account[CS50.me/account]!

'''

[[why-does-edx-think-my-grade-0]]
== Why does edX think my grade 0%?

CS50x doesn't use edX's built-in gradebook, so all students' scores appear (in edX's gradebook) as 0%. Not to worry, see https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/05722c69041f4754ae097af65aae2083/[CS50x's gradebook] for your actual scores.
